# Not autogenerated.
"""Consume an existing server's order feed using the custom adapter API."""

from lobo.replay.adapters import CustomAdapter, Protocol
from lobo.replay.adapters import expressions as le
from lobo.replay.adapters import models as lm


def protocol() -> Protocol:
    """Map the server's directory, snapshots and sequenced order commands."""
    registration = lm.Register(
        symbol=le.Field("symbol"),
        price_decimals=le.Field("price_decimals"),
        quantity_decimals=le.Field("quantity_decimals"),
        policy=le.Choose(le.Field("policy").exists(), le.Field("policy"), "full"),
    )
    return Protocol(
        lm.Json(
            lm.Message(
                le.Field("type").eq("directory"),
                lm.Directory(
                    le.Field("books"),
                    registration,
                    symbol=le.Field("symbol"),
                    on_remove=(le.Remember("sequence", le.Variable("symbol"), None),),
                ),
            ),
            lm.Message(
                le.Field("type").eq("snapshot"),
                le.When(
                    le.Field("book", "symbol").lookup("sequence").exists()
                    & le.Field("sequence").gt(
                        le.Field("book", "symbol").lookup("sequence")
                    )
                    | le.Field("book", "symbol")
                    .lookup("sequence")
                    .exists()
                    .eq(other=False),
                    le.ForEach([le.Root("book")], registration),
                    lm.Book(
                        le.Field("book", "symbol"),
                        le.ForEach(
                            le.Field("orders"),
                            lm.OrderCommand(
                                {"op": "add", "order": le.Field("order")},
                                timestamp=le.Field("timestamp_ns"),
                            ),
                        ),
                        snapshot=True,
                        timestamp=le.Field("timestamp_ns"),
                    ),
                    le.Remember(
                        "sequence", le.Field("book", "symbol"), le.Field("sequence")
                    ),
                    le.CheckSequence(
                        le.Field("sequence"), key=le.Field("book", "symbol"), reset=True
                    ),
                ),
            ),
            lm.Message(
                le.Field("type").eq("update"),
                le.When(
                    le.Field("sequence").gt(le.Field("book").lookup("sequence")),
                    le.CheckSequence(le.Field("sequence"), key=le.Field("book")),
                    lm.Book(
                        le.Field("book"),
                        lm.OrderCommand(le.Field("command")),
                        timestamp=le.Field("timestamp_ns"),
                    ),
                    le.Remember("sequence", le.Field("book"), le.Field("sequence")),
                ),
            ),
        )
    )


def build_adapter(endpoint: str, *, symbol: str = "BOOK") -> CustomAdapter:
    """Connect the declaration to an existing server's WebSocket feed."""
    return CustomAdapter(
        protocol(),
        lm.Source.websocket(endpoint),
        symbol=symbol,
        name="Order API",
        mode=lm.FeedMode.Live,
        level=lm.BookLevel.L3,
    )
