# Not autogenerated.
"""Check the Rust declaration bindings, published documentation, and example parity."""

# ruff: noqa: S101, D103, ANN401, FBT003
import ast
import importlib.util
import inspect
import json
import pydoc
import re
import textwrap
from collections.abc import Callable, Iterator
from pathlib import Path
from typing import Any, NoReturn

import pytest
import lobo

from lobo.replay.adapters import CustomAdapter, Protocol
from lobo.replay.adapters import expressions as le
from lobo.replay.adapters import models as lm

ROOT = Path(__file__).resolve().parents[3]
PUBLIC_CLASSES = [
    CustomAdapter,
    Protocol,
    *[
        obj
        for module in (lm, le)
        for obj in vars(module).values()
        if isinstance(obj, type) and obj.__module__.startswith("lobo.replay.adapters")
    ],
]


@pytest.mark.parametrize("mode", [lm.FeedMode.Live, lm.FeedMode.Replay])
@pytest.mark.parametrize("level", [lm.BookLevel.L1, lm.BookLevel.L2, lm.BookLevel.L3])
def test_capability_enums_round_trip(mode: lm.FeedMode, level: lm.BookLevel) -> None:
    info = lm.AdapterInfo("test", "Test", mode=mode, level=level, default_symbol="BOOK")
    assert info.mode == mode
    assert info.level == level
    adapter = CustomAdapter(
        Protocol(lm.Json()),
        lm.Source.packets([]),
        mode=mode,
        level=level,
    )
    assert adapter.info["mode"] == mode
    assert adapter.info["level"] == level


@pytest.mark.parametrize("argument,value", [("mode", "live"), ("level", "l2")])
def test_capabilities_require_enum_values(argument: str, value: str) -> None:
    with pytest.raises(TypeError):
        CustomAdapter(
            Protocol(lm.Json()),
            lm.Source.packets([]),
            **{argument: value},
        )


@pytest.mark.parametrize("interval", [0, -1, float("inf"), float("nan")])
def test_heartbeat_interval_is_checked_at_construction(interval: float) -> None:
    with pytest.raises(ValueError):
        lm.TextHeartbeat("PING", "PONG", interval=interval)


def public_methods(cls: type) -> Iterator[tuple[str, Callable[..., Any]]]:
    for name in vars(cls):
        if not name.startswith("_") and callable(getattr(cls, name)):
            yield name, getattr(cls, name)


def assert_arguments_documented(
    callable_: Callable[..., Any], documentation: str
) -> None:
    for name, parameter in inspect.signature(callable_).parameters.items():
        if name in {"self", "cls"}:
            continue
        assert re.search(rf"(?m)^\s*\*{{0,2}}{re.escape(name)}:", documentation), (
            callable_,
            parameter,
        )


@pytest.mark.parametrize("cls", PUBLIC_CLASSES, ids=lambda cls: cls.__name__)
def test_python_help_documents_every_constructor_argument(cls: type) -> None:
    documentation = inspect.getdoc(cls)
    assert documentation and "Examples:" in documentation
    if cls not in (lm.Source, lm.BinaryField, lm.Format):
        assert_arguments_documented(cls, documentation)
    assert "Build the declaration from its arguments" not in documentation


FUNCTIONS = [le.expression, lm.specification]

METHODS = [
    (f"{cls.__name__}.{name}", method)
    for cls in PUBLIC_CLASSES
    for name, method in public_methods(cls)
]


METHODS.extend((function.__name__, function) for function in FUNCTIONS)


@pytest.mark.parametrize("name,method", METHODS, ids=[name for name, _ in METHODS])
def test_python_help_documents_method_arguments_and_results(
    name: str, method: Callable[..., Any]
) -> None:
    documentation = inspect.getdoc(method)
    assert documentation, name
    assert_arguments_documented(method, documentation)
    # Methods that return a value describe it. Mutators and lifecycle methods
    # instead explain their effect and errors in prose.
    if name.startswith(("Expression.", "Source.")):
        assert "Returns:" in documentation


EXAMPLES = []
for cls in PUBLIC_CLASSES:
    for name, obj in [(cls.__name__, cls), *public_methods(cls)]:
        for index, code in enumerate(
            re.findall(r"```python\n(.*?)```", inspect.getdoc(obj) or "", re.DOTALL)
        ):
            EXAMPLES.append((f"{cls.__name__}.{name}.{index}", textwrap.dedent(code)))


for function in FUNCTIONS:
    for index, code in enumerate(
        re.findall(r"```python\n(.*?)```", inspect.getdoc(function) or "", re.DOTALL)
    ):
        EXAMPLES.append((f"{function.__name__}.{index}", textwrap.dedent(code)))


@pytest.mark.parametrize("name,code", EXAMPLES, ids=[name for name, _ in EXAMPLES])
def test_documented_python_examples_execute(name: str, code: str) -> None:
    namespace = {}
    exec(compile(code, f"<help({name})>", "exec"), namespace)  # noqa: S102


def test_protocol_help_explains_discovery_and_subscriptions() -> None:
    documentation = pydoc.render_doc(Protocol, renderer=pydoc.plaintext)
    assert "before a live" in documentation
    assert "separate from book snapshots" in documentation
    assert 'Variable("symbol")' in documentation
    assert "250 milliseconds" in documentation
    assert "does not limit the adapter's ticker directory" in documentation


def test_declarations_are_immutable_rust_objects_with_detached_exports() -> None:
    field = le.Field("price")
    assert not hasattr(field, "__dict__")
    with pytest.raises(AttributeError):
        field.data = {}
    exported = field.data
    exported["path"][0] = "other"
    assert field.data["path"] == ["price"]
    assert le.Expression(field.data).data == field.data
    action = lm.Add(id=1, side="buy", price=100, quantity=25)
    raw_action = action.data
    assert (
        lm.Action(
            raw_action["action"],
            **{k: v for k, v in raw_action.items() if k != "action"},
        ).data
        == raw_action
    )


def test_adapter_construction_does_not_export_or_serialize_protocol(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    protocol = Protocol(lm.Json())

    def unexpected_export(*_args: object, **_kwargs: object) -> NoReturn:
        raise AssertionError("Adapter construction must consume the Rust declaration")

    monkeypatch.setattr(json, "dumps", unexpected_export)
    monkeypatch.setattr(lm, "specification", unexpected_export)
    with CustomAdapter(protocol, lm.Source.packets([])) as adapter:
        assert adapter.info["name"] == "Custom adapter"


def test_exact_constants_and_expression_containers() -> None:
    large_id = 2**128 - 1
    template = le.expression(
        {"id": large_id, "wire": b"B", "symbols": [le.Variable("symbol"), "XYZ"]}
    )
    exported = lm.specification(template)
    assert exported["op"] == "object"
    values = dict(zip(exported["path"], exported["args"], strict=True))
    assert values["id"]["value"] == large_id
    assert values["wire"]["value"] == "B"
    assert values["symbols"]["op"] == "array"
    assert le.expression([1, "two", None]).data["op"] == "literal"
    with pytest.raises(TypeError, match=r"Use &"):
        bool(le.Field("enabled"))
    with pytest.raises(ValueError, match="finite"):
        le.expression(float("nan"))
    with pytest.raises(ValueError, match="ASCII"):
        le.expression(b"\xff")


def test_validation_occurs_when_protocol_is_constructed() -> None:
    with pytest.raises(ValueError, match="reconcile_capacity"):
        Protocol(lm.Json(), reconcile_capacity=0)
    with pytest.raises(ValueError, match="checksum"):
        Protocol(
            lm.Json(lm.Message(True, lm.Book("BOOK", checksum=lm.Checksum(0, depth=0))))
        )
    with pytest.raises(ValueError, match="outside"):
        lm.Record(size=2, fields={"id": lm.UInt(1, 8)}, actions=())
    with pytest.raises(TypeError, match="path"):
        le.Field("price", None)


def test_generator_arguments_are_consumed_once() -> None:
    visited = []

    def connection_actions() -> Iterator[lm.Action]:
        visited.append("connect")
        yield le.Let("ready", True)

    def instruments() -> Iterator[lm.Instrument]:
        visited.append("instrument")
        yield lm.Instrument("BOOK", 2, 0)

    protocol = Protocol(lm.Json(), connect=connection_actions())
    with CustomAdapter(
        protocol, lm.Source.packets([]), instruments=instruments()
    ) as adapter:
        assert adapter.tickers() == ["BOOK"]
    assert visited == ["connect", "instrument"]


def normalized(value: Any) -> Any:
    """Apply the shared schema's serde defaults to saved declaration dictionaries."""
    if isinstance(value, list):
        return [normalized(item) for item in value]
    if not isinstance(value, dict):
        return value
    value = {str(key): normalized(item) for key, item in value.items()}
    if "op" in value and value["op"] in {
        "literal",
        "array",
        "object",
        "field",
        "root",
        "variable",
        "eq",
        "ne",
        "gt",
        "lt",
        "and",
        "or",
        "exists",
        "is_array",
        "length",
        "abs",
        "trim",
        "strip_prefix",
        "map",
        "lookup",
        "get",
        "decimal",
        "timestamp",
        "choose",
        "concat",
    }:
        for key, default in {"args": [], "path": [], "name": "", "value": None}.items():
            value.setdefault(key, default)
    if value.get("type") in {"uint", "text"}:
        value.setdefault("byteorder", "big")
    return value


@pytest.mark.parametrize(
    "example,fixture,args",
    [
        ("itch", "itch", ()),
        ("kraken", "kraken", (10,)),
        ("bitfinex", "bitfinex", ()),
        ("order_feed", "server", ()),
    ],
)
def test_example_declarations_match_existing_rust_parity_inputs(
    example: str, fixture: str, args: tuple[int, ...]
) -> None:
    path = ROOT / "python/examples" / example / "adapter.py"
    spec = importlib.util.spec_from_file_location(f"example_{example}", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    saved = json.loads(
        (
            ROOT / "rust/crates/lobo_replay/tests/definitions" / f"{fixture}.json"
        ).read_text()
    )
    assert normalized(lm.specification(module.protocol(*args))) == normalized(saved)


def test_generated_stubs_include_rust_documentation_and_public_exports() -> None:
    package = Path(lobo.__file__).resolve().parent
    generated = package / "_lobo/_lobo/replay"
    classes = {}
    for path in generated.rglob("*.pyi"):
        module = ast.parse(path.read_text())
        assert "AUTOGENERATED FROM RUST" in ast.get_docstring(module)
        classes.update(
            {node.name: node for node in module.body if isinstance(node, ast.ClassDef)}
        )
    for cls in PUBLIC_CLASSES:
        assert cls.__module__.startswith("lobo.replay.adapters")
        assert ast.get_docstring(classes[cls.__name__]) == inspect.getdoc(cls)
    for path in (package / "replay/adapters").glob("*.pyi"):
        assert not any(
            isinstance(node, (ast.ClassDef, ast.FunctionDef))
            for node in ast.parse(path.read_text()).body
        )
    assert not (package / "replay/custom/__init__.py").exists()
