# Not autogenerated.
"""A Python-only adapter exposes discovery and subscriptions to browser clients."""

# ruff: noqa: S101, D103, S310
import json
from pathlib import Path
from queue import Queue
from threading import Thread
from urllib.error import HTTPError
from urllib.request import Request, urlopen

import pytest
from websockets.exceptions import ConnectionClosed
from websockets.sync.client import connect
from websockets.sync.server import ServerConnection, serve

from lobo import server_context
from lobo.replay.adapters import CustomAdapter, Protocol
from lobo.replay.adapters import expressions as le
from lobo.replay.adapters import models as lm


def read_json(url: str, data: dict | None = None) -> object:
    request = Request(
        url,
        data=None if data is None else json.dumps(data).encode(),
        headers={"Content-Type": "application/json"},
    )
    with urlopen(request, timeout=5) as response:
        return None if response.status == 204 else json.load(response)


@pytest.mark.parametrize("restricted", [False, True])
def test_hosted_directory_selection_and_python_scope(
    tmp_path: Path,
    *,
    restricted: bool,
) -> None:
    subscriptions: Queue[str] = Queue()

    def stream(socket: ServerConnection) -> None:
        try:
            symbol = json.loads(socket.recv(timeout=5))["symbol"]
            subscriptions.put(symbol)
            socket.send(json.dumps({"symbol": symbol}))
            for _ in socket:
                pass
        except ConnectionClosed:
            pass

    with serve(stream, "127.0.0.1", 0) as upstream:
        thread = Thread(target=upstream.serve_forever)
        thread.start()
        try:
            declaration = Protocol(
                lm.Json(
                    lm.Message(
                        True,  # noqa: FBT003
                        lm.Book(
                            le.Field("symbol"),
                            lm.Level(side="sell", price=60, quantity=3),
                            snapshot=True,
                            timestamp=1000,
                        ),
                    )
                ),
                connect=(lm.Subscribe(),),
                subscriptions=(lm.Send({"symbol": le.Variable("symbol")}),),
                symbols_per_connection=1,
            )
            adapter = CustomAdapter(
                declaration,
                lm.Source.websocket(
                    f"ws://127.0.0.1:{upstream.socket.getsockname()[1]}"
                ),
                instruments=[lm.Instrument(s, 2, 0) for s in ("AAA", "BBB", "CCC")],
                symbol="AAA",
                scope=["AAA"] if restricted else None,
                level=lm.BookLevel.L2,
            )
            (tmp_path / "index.html").write_text("<title>Test terminal</title>")
            with server_context(
                adapters=[adapter], port=0, web_root=tmp_path
            ) as server:
                assert subscriptions.get(timeout=5) == "AAA"
                config = read_json(f"{server.url}/api/server-context")
                endpoint = config["adapters"][0]["subscriptionsEndpoint"]
                feed_url = server.url.replace("http:", "ws:") + "/api/adapters/0/feed"
                with connect(feed_url) as socket:
                    initial = json.loads(socket.recv(timeout=5))
                    expected = ["AAA"] if restricted else ["AAA", "BBB", "CCC"]
                    assert [i["symbol"] for i in initial["instruments"]] == expected
                    assert all(
                        i["policy"] == "no_updates" for i in initial["instruments"]
                    )
                    assert not any(
                        a["action"] == "book" and a["symbol"]["value"] == "BBB"
                        for a in initial["actions"]
                    )
                    # Validate the whole request before subscribing any member.
                    with pytest.raises(HTTPError) as rejected:
                        read_json(
                            server.url + endpoint,
                            {"symbols": ["BBB", "UNKNOWN"], "selected": "AAA"},
                        )
                    assert rejected.value.code == 422
                    assert subscriptions.empty()
                    if restricted:
                        with pytest.raises(HTTPError) as rejected:
                            read_json(server.url + endpoint, {"selected": "BBB"})
                        assert rejected.value.code == 422
                    else:
                        read_json(
                            server.url + endpoint,
                            {"symbols": ["BBB", "CCC"], "selected": "BBB"},
                        )
                        assert {
                            subscriptions.get(timeout=5),
                            subscriptions.get(timeout=5),
                        } == {"BBB", "CCC"}
                        while True:
                            update = json.loads(socket.recv(timeout=5))
                            if any(
                                a.get("action") == "book"
                                and a["symbol"]["value"] == "BBB"
                                for a in update.get("actions", [])
                            ):
                                break
                        assert adapter.levels("BBB")[0]["quantity"] == 3
        finally:
            upstream.shutdown()
            thread.join(timeout=5)
