# Not autogenerated.
"""Hosted replay controls operate on source time and reconstruct shared books."""

# ruff: noqa: S101, D103, S310
import gzip
import json
from collections.abc import Callable
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from threading import Thread
from time import monotonic, sleep
from urllib.error import HTTPError
from urllib.request import Request, urlopen

import pytest
from websockets.sync.client import connect

from lobo import server_context
from lobo.replay.adapters import CustomAdapter, Protocol
from lobo.replay.adapters import expressions as le
from lobo.replay.adapters import models as lm

ORIGIN = 34_200_000_000_000
SECOND = 1_000_000_000


def replay(
    tmp_path: Path, kind: str = "json_lines", url: str | None = None
) -> CustomAdapter:
    (tmp_path / "index.html").write_text("<title>Replay test</title>")
    times = [ORIGIN + i * SECOND for i in range(4)]
    if kind == "binary":
        protocol = Protocol(
            lm.Binary(
                length=lm.UInt(0, 1),
                tag=lm.UInt(0, 1),
                key=lm.UInt(1, 1),
                timestamp=lm.UInt(2, 8),
                records={
                    1: lm.Record(
                        size=12,
                        fields={
                            "id": lm.UInt(10, 1),
                            "quantity": lm.UInt(11, 1),
                        },
                        actions=(
                            lm.Register(
                                symbol="TEST",
                                key=le.Variable("key"),
                                price_decimals=0,
                                quantity_decimals=0,
                            ),
                            lm.Add(
                                id=le.Field("id"),
                                side="buy",
                                price=100,
                                quantity=le.Field("quantity"),
                            ),
                        ),
                    )
                },
            )
        )
        content = b"".join(
            bytes([12, 1, 1]) + t.to_bytes(8, "big") + bytes([i + 1, 10])
            for i, t in enumerate(times)
        )
        path = tmp_path / "replay.bin.gz"
        path.write_bytes(gzip.compress(content))
        source = (
            lm.Source.http(url, chunk_size=17)
            if url
            else lm.Source.file(path, chunk_size=17)
        )
    else:
        # An explicitly partial initial state stays unsynchronized throughout.
        protocol = Protocol(
            lm.Json(
                lm.Message(
                    True,  # noqa: FBT003
                    lm.Book(
                        "TEST",
                        lm.Level(side="buy", price=100, quantity=le.Field("quantity")),
                        timestamp=le.Field("timestamp"),
                        snapshot=le.Field("initial"),
                        ready=False,
                    ),
                )
            )
        )
        packets = [
            json.dumps(
                {"timestamp": t, "quantity": (i + 1) * 10, "initial": i == 0}
            ).encode()
            for i, t in enumerate(times)
        ]
        if kind == "packets":
            source = lm.Source.packets(packets)
        else:
            path = tmp_path / "replay.jsonl.gz"
            path.write_bytes(gzip.compress(b"\n".join(packets) + b"\n"))
            source = lm.Source.json_lines(path)
    return CustomAdapter(
        protocol,
        source,
        instruments=[lm.Instrument("TEST", 0, 0)],
        symbol="TEST",
        mode=lm.FeedMode.Replay,
        level=lm.BookLevel.L3 if kind == "binary" else lm.BookLevel.L2,
        name="Recorded sample · PARTIAL",
    )


def request(url: str, command: dict | None = None) -> dict:
    with urlopen(
        Request(
            url,
            data=None if command is None else json.dumps(command).encode(),
            headers={"Content-Type": "application/json"},
        ),
        timeout=10,
    ) as response:
        return json.load(response)


def quantity(adapter: CustomAdapter) -> int:
    return sum(level["quantity"] for level in adapter.levels("TEST"))


def until(predicate: Callable[[], bool], timeout: float = 5) -> None:
    deadline = monotonic() + timeout
    while not predicate():
        assert monotonic() < deadline, "Replay did not reach the expected state"
        sleep(0.01)


@pytest.mark.parametrize("kind", ["json_lines", "packets", "binary"])
def test_hosted_replay_pause_seek_speed_and_eof(tmp_path: Path, kind: str) -> None:
    adapter = replay(tmp_path, kind)
    with server_context(adapters=[adapter], port=0, web_root=tmp_path) as server:
        config = request(server.url + "/api/server-context")["adapters"][0]
        assert config["mode"] == "replay"
        assert "PARTIAL" in config["name"]
        assert config["playback"]["paused"]
        endpoint = server.url + config["playbackEndpoint"]
        sleep(0.05)
        assert adapter.status()["messages"] == 0
        assert request(endpoint)["clock_ns"] == 0

        # Both public control surfaces share the same state and acknowledge seeks.
        state = request(endpoint, {"action": "seek", "timestamp_ns": ORIGIN + SECOND})
        assert state["paused"] and state["clock_ns"] == ORIGIN + SECOND
        assert quantity(adapter) == 20
        frozen = adapter.status()
        sleep(0.08)
        assert adapter.status() == frozen
        if kind != "binary":
            assert not frozen["synchronized"]

        # Backwards seeks and restart replace books instead of duplicating records.
        assert adapter.seek(ORIGIN + SECOND // 2)["clock_ns"] == ORIGIN + SECOND // 2
        assert quantity(adapter) == 10
        assert adapter.restart()["clock_ns"] == ORIGIN
        assert quantity(adapter) == 10

        with connect(
            server.url.replace("http:", "ws:") + "/api/adapters/0/feed"
        ) as socket:
            snapshot = json.loads(socket.recv(timeout=5))
            assert snapshot["clock_ns"] == ORIGIN
            assert not snapshot["complete"]
            adapter.seek(ORIGIN + 2 * SECOND)
            while True:
                snapshot = json.loads(socket.recv(timeout=5))
                if snapshot["type"] == "snapshot":
                    break
            assert snapshot["clock_ns"] == ORIGIN + 2 * SECOND
            assert quantity(adapter) == 30

        # A source second takes substantially less wall time at 10x than at 1x.
        durations = []
        for speed in (1, 10):
            adapter.pause()
            adapter.restart()
            request(endpoint, {"action": "speed", "speed": speed})
            assert adapter.playback["speed"] == speed
            started = monotonic()
            adapter.play()
            until(lambda: quantity(adapter) >= 20)
            durations.append(monotonic() - started)
            adapter.pause()
            frozen = adapter.status()
            sleep(0.05)
            assert adapter.status() == frozen
        assert durations[0] > 0.75
        assert durations[1] < durations[0] * 0.6

        adapter.set_speed(1000)
        adapter.play()
        adapter.wait()
        state = adapter.playback
        assert state["complete"] and state["paused"]
        assert state["clock_ns"] == ORIGIN + 3 * SECOND
        assert quantity(adapter) == 40
        sleep(0.05)
        assert adapter.playback == state
        assert adapter.play()["paused"]
        assert adapter.seek(ORIGIN + 99 * SECOND)["clock_ns"] == ORIGIN + 3 * SECOND
        assert adapter.restart()["complete"] is False
        assert quantity(adapter) == 10
        adapter.play()
        beyond = adapter.seek(ORIGIN + 99 * SECOND)
        assert beyond["complete"] and beyond["paused"]


def test_public_start_and_validation(tmp_path: Path) -> None:
    with replay(tmp_path) as adapter:
        adapter.start(paused=True, speed=5)
        assert adapter.playback["paused"]
        assert adapter.playback["speed"] == 5
        for speed in (0, -1, float("inf"), float("nan"), 1001):
            with pytest.raises(RuntimeError, match="speed"):
                adapter.set_speed(speed)
        assert adapter.playback["speed"] == 5
        adapter.seek(ORIGIN + 2 * SECOND)
        assert quantity(adapter) == 30
    with replay(tmp_path) as adapter:
        adapter.start()
        adapter.wait()
        assert quantity(adapter) == 40
        with pytest.raises(RuntimeError, match="no playback controls"):
            adapter.pause()


def test_http_control_validation(tmp_path: Path) -> None:
    with server_context(
        adapters=[replay(tmp_path)], port=0, web_root=tmp_path
    ) as server:
        endpoint = server.url + "/api/adapters/0/playback"
        for command in (
            {"action": "speed", "speed": 0},
            {"action": "seek", "timestamp_ns": -1},
            {"action": "unknown"},
        ):
            with pytest.raises(HTTPError) as error:
                request(endpoint, command)
            assert error.value.code == 422
        assert request(endpoint)["paused"]


def test_paced_http_reopens_and_reconstructs(tmp_path: Path) -> None:
    requests = []

    class Handler(BaseHTTPRequestHandler):
        def do_GET(self) -> None:
            requests.append(self.path)
            body = (tmp_path / "replay.bin.gz").read_bytes()
            self.send_response(200)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def log_message(self, *args: object) -> None:
            pass

    with ThreadingHTTPServer(("127.0.0.1", 0), Handler) as upstream:
        thread = Thread(target=upstream.serve_forever)
        thread.start()
        try:
            with replay(
                tmp_path, "binary", f"http://127.0.0.1:{upstream.server_port}/replay.gz"
            ) as adapter:
                adapter.start(paused=True)
                adapter.seek(ORIGIN + 2 * SECOND)
                assert quantity(adapter) == 30
                adapter.restart()
                assert quantity(adapter) == 10
                assert len(requests) >= 2
                adapter.set_speed(1000)
                adapter.play()
                adapter.wait()
                assert adapter.playback["complete"]
                assert quantity(adapter) == 40
        finally:
            upstream.shutdown()
            thread.join(timeout=5)


def test_autoplay_and_failed_seek_report_state(tmp_path: Path) -> None:
    adapter = replay(tmp_path)
    with server_context(
        adapters=[adapter],
        port=0,
        web_root=tmp_path,
        replay_paused=False,
        replay_speed=1000,
    ):
        adapter.wait()
        assert quantity(adapter) == 40
        (tmp_path / "replay.jsonl.gz").write_bytes(gzip.compress(b"not json\n"))
        with pytest.raises(RuntimeError):
            adapter.restart()
        assert adapter.playback["paused"]
        assert adapter.playback["error"]
        assert not adapter.playback["seeking"]
