# Not autogenerated.
from uuid import UUID, uuid4

import pytest

import lobo
from lobo.orders import IcebergOrder, LimitOrder, MarketOrder, Order, Side
from lobo.storage import BidAskStore, OrderStorage, UserOutstandingLiquidity


def test_public_modules_and_side_enum_are_registered() -> None:
    assert lobo.__all__ == [
        "Book",
        "CheckSum",
        "Cancel",
        "Execution",
        "Fill",
        "MarketImpact",
        "MatchedFill",
        "Report",
        "Reports",
        "Summary",
        "server_context",
    ]
    assert int(Side.Buy) == 0
    assert int(Side.Sell) == 1
    assert Side.Buy != Side.Sell
    assert repr(Side.Buy) == "Side.Buy"
    assert Order.__module__ == "lobo.orders"
    assert OrderStorage.__module__ == "lobo.storage"
    assert BidAskStore.__module__ == "lobo.storage"
    assert UserOutstandingLiquidity.__module__ == "lobo.storage"
    assert int(lobo.Execution.Mutating) == 0
    assert int(lobo.Execution.Simulation) == 1
    assert lobo.Execution.Mutating != lobo.Execution.Simulation
    assert repr(lobo.Execution.Mutating) == "Execution.Mutating"


@pytest.mark.parametrize(
    ("order", "expected_fields"),
    [
        (
            MarketOrder(3, uuid4(), Side.Buy),
            ["quantity", "trader", "side"],
        ),
        (
            LimitOrder(101, 4, uuid4(), Side.Sell),
            ["price", "quantity", "trader", "side"],
        ),
        (
            IcebergOrder(102, 5, uuid4(), Side.Buy, 7),
            ["price", "quantity", "trader", "side", "hidden_quantity"],
        ),
    ],
)
def test_order_constructors_and_display_protocol(
    order: Order,
    expected_fields: list[str],
) -> None:
    assert order.__display_fields__ == expected_fields
    representation = repr(order)
    assert representation.startswith(f"{type(order).__name__}(")
    for field in expected_fields:
        assert f"{field}=" in representation

    html = order._repr_html_()
    assert html.startswith('<table style="border-collapse:collapse')
    assert f">{type(order).__name__}</caption>" in html
    for field in expected_fields:
        assert f">{field}</th>" in html


def test_limit_fill_cancel_and_live_storage_views() -> None:
    book = lobo.Book()
    seller = uuid4()
    buyer = uuid4()
    storage = book.orders
    bids = storage.bids
    asks = storage.asks

    assert book.best_bid is None
    assert book.best_ask is None
    assert bids.order_count == asks.order_count == 0
    assert bids.visible_quantity == asks.visible_quantity == 0
    assert bids.hidden_quantity == asks.hidden_quantity == 0

    resting = book.fill(LimitOrder(101, 5, seller, Side.Sell))
    assert isinstance(resting.remaining_order_id, UUID)
    assert resting.report is None
    assert not hasattr(resting, "order_id")
    assert not hasattr(resting, "filled_quantity")
    assert not hasattr(resting, "realized_price")
    assert book.best_ask == 101
    assert asks.order_count == 1
    assert asks.visible_quantity == 5

    matched = book.fill(
        LimitOrder(101, 2, buyer, Side.Buy),
        lobo.Reports(include_summary=True),
    )
    assert matched.remaining_order_id is None
    assert matched.report is not None
    assert matched.report.fills is None
    assert matched.report.market_impact is None
    summary = matched.report.summary
    assert summary is not None
    assert summary.trader_id == buyer
    assert summary.side == Side.Buy
    assert summary.filled_quantity == 2
    assert summary.realized_price == 101
    assert asks.visible_quantity == 3

    seller_summary = book.get_user_order_summary(seller)
    assert seller_summary.order_count == 1
    assert seller_summary.visible_quantity == 3
    assert seller_summary.hidden_quantity == 0
    assert seller_summary.quantity == 3
    assert seller_summary.visible_value == 303
    assert seller_summary.visible_vwap == 101.0
    assert seller_summary.hidden_value == 0
    assert seller_summary.hidden_vwap == 0.0
    assert seller_summary.value == 303
    assert seller_summary.vwap == 101.0
    assert "UserOutstandingLiquidity(order_count=1" in repr(seller_summary)
    assert ">visible_quantity</th><td>3</td>" in seller_summary._repr_html_()

    canceled = book.cancel(resting.remaining_order_id)
    assert canceled.order_id == resting.remaining_order_id
    assert book.best_ask is None
    assert asks.order_count == 0


def test_iceberg_replenishment_updates_hidden_and_visible_views() -> None:
    book = lobo.Book()
    seller = uuid4()
    buyer = uuid4()
    resting = book.fill(IcebergOrder(100, 2, seller, Side.Sell, 4))
    asks = book.orders.asks

    assert asks.order_count == 1
    assert asks.visible_quantity == 2
    assert asks.hidden_quantity == 4

    summary_report = lobo.Reports(include_summary=True)

    first = book.fill(MarketOrder(2, buyer, Side.Buy), summary_report)
    assert first.report.summary.filled_quantity == 2
    assert first.report.summary.realized_price == 100
    assert asks.visible_quantity == 2
    assert asks.hidden_quantity == 2

    second = book.fill(MarketOrder(2, buyer, Side.Buy), summary_report)
    assert second.report.summary.filled_quantity == 2
    assert second.report.summary.realized_price == 100
    assert asks.visible_quantity == 2
    assert asks.hidden_quantity == 0

    final = book.fill(MarketOrder(2, buyer, Side.Buy), summary_report)
    assert final.report.summary.filled_quantity == 2
    assert asks.order_count == 0
    assert asks.visible_quantity == 0
    assert asks.hidden_quantity == 0

    with pytest.raises(RuntimeError, match="order state error"):
        book.cancel(resting.remaining_order_id)


def test_unmatched_market_and_invalid_base_order_do_not_rest() -> None:
    book = lobo.Book()
    result = book.fill(
        MarketOrder(5, uuid4(), Side.Buy),
        lobo.Reports(include_summary=True),
    )
    assert result.report.summary.filled_quantity == 0
    assert result.report.summary.realized_price == 0
    assert result.remaining_order_id is None
    assert book.best_bid is None
    assert book.best_ask is None

    with pytest.raises(TypeError, match="unsupported order type"):
        book.fill(Order())

    with pytest.raises(RuntimeError, match="order state error"):
        book.cancel(uuid4())


def test_fills_report_does_not_calculate_summary() -> None:
    book = lobo.Book()
    seller = uuid4()
    buyer = uuid4()
    resting = book.fill(LimitOrder(100, 3, seller, Side.Sell))

    result = book.fill(
        MarketOrder(2, buyer, Side.Buy),
        lobo.Reports(include_fills=True),
    )

    assert result.report is not None
    assert result.report.summary is None
    assert result.report.market_impact is None
    assert result.report.fills is not None
    assert len(result.report.fills) == 1
    matched_fill = result.report.fills[0]
    assert isinstance(matched_fill, lobo.MatchedFill)
    assert matched_fill.maker_order_id == resting.remaining_order_id
    assert matched_fill.fill_quantity == 2
    assert matched_fill.price == 100


def test_report_objects_support_text_and_html_display_protocols() -> None:
    book = lobo.Book()
    seller = uuid4()
    reports = lobo.Reports(
        include_fills=True,
        include_summary=True,
        include_market_impact=True,
    )
    book.fill(LimitOrder(100, 2, seller, Side.Sell))
    result = book.fill(MarketOrder(1, uuid4(), Side.Buy), reports)

    assert reports.__display_fields__ == [
        "include_fills",
        "include_summary",
        "include_market_impact",
    ]
    assert repr(reports) == (
        "Reports(include_fills=True, include_summary=True, "
        "include_market_impact=True)"
    )

    assert result.report is not None
    assert result.report.fills is not None
    assert result.report.summary is not None
    assert result.report.market_impact is not None
    display_objects = [
        (
            reports,
            "Reports",
            ["include_fills", "include_summary", "include_market_impact"],
        ),
        (
            result.report,
            "Report",
            ["fills", "summary", "market_impact"],
        ),
        (
            result.report.fills[0],
            "MatchedFill",
            [
                "maker_order_id",
                "taker_order_id",
                "fill_quantity",
                "maker_depleted",
                "maker_trader_id",
                "price",
                "fill_time",
            ],
        ),
        (
            result.report.summary,
            "Summary",
            [
                "order_id",
                "trader_id",
                "side",
                "filled_quantity",
                "realized_price",
            ],
        ),
        (
            result.report.market_impact,
            "MarketImpact",
            [
                "avg_price",
                "worst_price",
                "slippage",
                "slippage_bps",
                "levels_consumed",
                "total_quantity_available",
            ],
        ),
    ]

    for value, class_name, fields in display_objects:
        assert value.__display_fields__ == fields
        representation = repr(value)
        assert representation.startswith(f"{class_name}(")
        for field in fields:
            assert f"{field}=" in representation

        html = value._repr_html_()
        assert f">{class_name}</caption>" in html
        for field in fields:
            assert f">{field}</th>" in html


def test_simulation_matches_mutating_execution_without_changing_book() -> None:
    book = lobo.Book()
    seller = uuid4()
    buyer = uuid4()
    book.fill(LimitOrder(100, 2, seller, Side.Sell))
    book.fill(LimitOrder(102, 2, seller, Side.Sell))
    asks = book.orders.asks
    reports = lobo.Reports(
        include_fills=True,
        include_summary=True,
        include_market_impact=True,
    )
    taker = MarketOrder(3, buyer, Side.Buy)

    simulated = book.fill(
        taker,
        reports,
        execution=lobo.Execution.Simulation,
    )

    assert asks.order_count == 2
    assert asks.visible_quantity == 4
    assert book.best_ask == 100

    # Omitting execution exercises the Mutating default.
    mutated = book.fill(taker, reports)

    assert asks.order_count == 1
    assert asks.visible_quantity == 1
    assert book.best_ask == 102
    assert simulated.remaining_order_id == mutated.remaining_order_id

    assert simulated.report is not None
    assert mutated.report is not None
    simulated_summary = simulated.report.summary
    mutated_summary = mutated.report.summary
    assert simulated_summary is not None
    assert mutated_summary is not None
    assert (
        simulated_summary.trader_id,
        simulated_summary.side,
        simulated_summary.filled_quantity,
        simulated_summary.realized_price,
    ) == (
        mutated_summary.trader_id,
        mutated_summary.side,
        mutated_summary.filled_quantity,
        mutated_summary.realized_price,
    )

    simulated_impact = simulated.report.market_impact
    mutated_impact = mutated.report.market_impact
    assert simulated_impact is not None
    assert mutated_impact is not None
    assert (
        simulated_impact.avg_price,
        simulated_impact.worst_price,
        simulated_impact.slippage,
        simulated_impact.slippage_bps,
        simulated_impact.levels_consumed,
        simulated_impact.total_quantity_available,
    ) == (
        mutated_impact.avg_price,
        mutated_impact.worst_price,
        mutated_impact.slippage,
        mutated_impact.slippage_bps,
        mutated_impact.levels_consumed,
        mutated_impact.total_quantity_available,
    )

    simulated_fills = simulated.report.fills
    mutated_fills = mutated.report.fills
    assert simulated_fills is not None
    assert mutated_fills is not None
    assert [
        (
            fill.maker_order_id,
            fill.fill_quantity,
            fill.maker_depleted,
            fill.maker_trader_id,
            fill.price,
        )
        for fill in simulated_fills
    ] == [
        (
            fill.maker_order_id,
            fill.fill_quantity,
            fill.maker_depleted,
            fill.maker_trader_id,
            fill.price,
        )
        for fill in mutated_fills
    ]


def test_market_impact_uses_pre_fill_depth_and_side_aware_slippage() -> None:
    book = lobo.Book()
    seller = uuid4()
    buyer = uuid4()
    book.fill(LimitOrder(100, 2, seller, Side.Sell))
    book.fill(IcebergOrder(102, 1, seller, Side.Sell, 3))

    result = book.fill(
        MarketOrder(3, buyer, Side.Buy),
        lobo.Reports(include_market_impact=True),
    )

    assert result.report is not None
    assert result.report.fills is None
    assert result.report.summary is None
    impact = result.report.market_impact
    assert impact is not None
    assert impact.avg_price == pytest.approx(302 / 3)
    assert impact.worst_price == 102
    assert impact.slippage == 2
    assert impact.slippage_bps == pytest.approx(200.0)
    assert impact.levels_consumed == 2
    assert impact.total_quantity_available == 6
    assert impact.can_fill(6)
    assert not impact.can_fill(7)
    assert impact.fill_ratio(12) == pytest.approx(0.5)


def test_checksum_options_form_hashable_constructor_keys():
    from lobo import Book, CheckSum

    books = {
        (users, checksum, hidden): Book(
            update_user_map=users, check_sum_spec=checksum, update_hidden=hidden
        )
        for users in (False, True)
        for checksum in (CheckSum.Null, CheckSum.BitFinex, CheckSum.Kraken)
        for hidden in (False, True)
    }
    assert len(books) == 12
    assert {type(book) for book in books.values()} == {Book}
    for (users, checksum, hidden), book in books.items():
        assert book.update_user_map is users
        assert book.check_sum_spec == checksum
        assert book.update_hidden is hidden
        assert book.checksum() == 0
