# Not autogenerated.
"""Check shipped adapter bindings against their existing wire recordings."""

# ruff: noqa: S101, D103
import importlib
import json
import zlib
from pathlib import Path

import pytest

from examples.bitfinex.adapter import protocol as bitfinex_protocol
from examples.kraken.adapter import protocol as kraken_protocol
from lobo.replay.adapters import AdapterSession, CustomAdapter, bitfinex, itch, kraken
from lobo.replay.adapters import models as lm

FIXTURES = (
    Path(__file__).resolve().parents[3] / "rust/crates/lobo_adapters/tests/fixtures"
)


def encoded(value: object) -> bytes:
    return json.dumps(value).encode()


def kraken_source(*, corrupt: bool = False) -> lm.Source:
    directory = encoded(
        {
            "channel": "instrument",
            "type": "snapshot",
            "data": {
                "pairs": [
                    {
                        "symbol": "BTC/USD",
                        "price_precision": 1,
                        "qty_precision": 8,
                        "status": "online",
                    },
                    {
                        "symbol": "ETH/USD",
                        "price_precision": 2,
                        "qty_precision": 8,
                        "status": "online",
                    },
                ]
            },
        }
    )
    update = json.loads((FIXTURES / "kraken_update.json").read_text())
    if corrupt:
        update["data"][0]["checksum"] = 0
    return lm.Source.packets(
        [
            directory,
            (FIXTURES / "kraken_snapshot.json").read_bytes(),
            encoded(update),
        ]
    )


def bitfinex_source(*, corrupt: bool = False, ask_quantity: int = 3) -> lm.Source:
    checksum = zlib.crc32(f"10:1:30:-{ask_quantity}:20:2".encode())
    signed_checksum = checksum if checksum < 2**31 else checksum - 2**32
    packets = [
        {"event": "conf", "status": "OK", "flags": 229376},
        {
            "event": "subscribed",
            "chanId": 1,
            "channel": "book",
            "prec": "R0",
            "symbol": "tBTCUSD",
        },
        {"event": "subscribed", "chanId": 2, "channel": "trades", "symbol": "tBTCUSD"},
        [
            1,
            [[20, 100, 2], [30, 101, -ask_quantity], [10, 100, 1]],
            1,
            1_700_000_000_000,
        ],
        [1, "cs", 0 if corrupt else signed_checksum, 2, 1_700_000_000_001],
    ]
    return lm.Source.packets(
        [encoded(packet) for packet in packets],
        bootstrap=[("instruments", b'[["BTCUSD","ETHUSD"]]')],
    )


def test_public_modules_export_the_actual_binding_classes() -> None:
    for module, name in [
        (itch, "ItchSource"),
        (kraken, "KrakenSource"),
        (bitfinex, "BitfinexSource"),
    ]:
        cls = getattr(module, name)
        assert (
            cls.__module__
            == f"lobo.replay.adapters.{module.__name__.rsplit('.', 1)[-1]}"
        )
        assert getattr(importlib.import_module(cls.__module__), name) is cls
    assert kraken.KrakenSource().symbol == "BTC/USD"
    assert bitfinex.BitfinexSource().symbol == "BTCUSD"
    assert kraken.KrakenSource("eth/usd", 25).symbol == "ETH/USD"


def test_kraken_binding_preserves_snapshot_update_checksum_and_l2_simulation() -> None:
    with kraken.KrakenSource(source=kraken_source()).start() as session:
        assert isinstance(session, AdapterSession)
        session.wait()
        assert session.finished
        assert session.info.mode == lm.FeedMode.Live
        assert session.info.level == lm.BookLevel.L2
        assert session.tickers() == ["BTC/USD", "ETH/USD"]
        assert session.status()["checksum_checks"] == 2
        assert session.status()["checksum_failures"] == 0
        assert session.status()["synchronized"]
        before = session.levels("BTC/USD")
        assert any(
            level["price"] == "452840" and level["quantity"] == 30_000_000
            for level in before
        )
        with CustomAdapter(
            kraken_protocol(10),
            kraken_source(),
            symbol="BTC/USD",
            mode=lm.FeedMode.Live,
            level=lm.BookLevel.L2,
        ) as custom:
            custom.start()
            custom.wait()
            assert custom.levels("BTC/USD") == before
        session.simulate("buy", 1000)
        result = session.simulation_report()
        assert result["simulated"] and result["filled"] == 1000
        assert not result["alternate_timeline"]
        assert session.levels("BTC/USD") == before
    with pytest.raises(RuntimeError, match="closed"):
        session.levels("BTC/USD")
    session.close()


def test_bitfinex_binding_preserves_checksum_fifo_and_l3_simulation() -> None:
    with bitfinex.BitfinexSource(source=bitfinex_source()).start() as session:
        session.wait()
        assert session.info.level == lm.BookLevel.L3
        assert session.tickers() == ["BTCUSD", "ETHUSD"]
        assert session.status()["checksum_checks"] == 1
        assert session.status()["synchronized"]
        assert [
            (row[0], row[2])
            for row in session.queue("BTCUSD", "buy", 0, 20_000_000_000)
        ] == [(10, 100_000_000), (20, 200_000_000)]
        before = session.levels("BTCUSD")
        session.simulate("buy", 100_000_000, price=100 * 100_000_000)
        report = session.simulation_report()
        assert report["alternate_timeline"]
        assert report["remaining"] == 100_000_000
        session.return_to_main()
        assert session.levels("BTCUSD") == before


@pytest.mark.parametrize("venue", ["kraken", "bitfinex"])
def test_bad_checksum_uses_the_existing_resynchronization_path(venue: str) -> None:
    source = (
        kraken.KrakenSource(source=kraken_source(corrupt=True))
        if venue == "kraken"
        else bitfinex.BitfinexSource(source=bitfinex_source(corrupt=True))
    )
    with source.start() as session:
        if venue == "bitfinex":
            with pytest.raises(RuntimeError, match="checksum mismatch"):
                session.wait()
        else:
            session.wait()
        assert session.status()["checksum_failures"] == 1
        assert not session.status()["synchronized"]


def test_invalid_source_configuration_is_rejected_before_start() -> None:
    with pytest.raises(ValueError, match="depth"):
        kraken.KrakenSource(depth=12)
    with pytest.raises(ValueError):
        bitfinex.BitfinexSource("")


@pytest.mark.parametrize("ask_quantity", [2, 3], ids=["positive-crc", "negative-crc"])
def test_custom_bitfinex_checksum_matches_builtin_reference(ask_quantity: int) -> None:
    # Construction compiles the protocol. Starting a second instance must reuse
    # prepared checksum settings from that cached program, including its sign.
    with CustomAdapter(
        bitfinex_protocol(),
        bitfinex_source(ask_quantity=ask_quantity),
        symbol="BTCUSD",
        mode=lm.FeedMode.Live,
        level=lm.BookLevel.L3,
    ):
        pass
    with bitfinex.BitfinexSource(
        source=bitfinex_source(ask_quantity=ask_quantity)
    ).start() as session:
        session.wait()
        with CustomAdapter(
            bitfinex_protocol(),
            bitfinex_source(ask_quantity=ask_quantity),
            symbol="BTCUSD",
            mode=lm.FeedMode.Live,
            level=lm.BookLevel.L3,
        ) as custom:
            custom.start()
            custom.wait()
            assert custom.status()["checksum_checks"] == 1
            assert custom.status()["checksum_failures"] == 0
            assert custom.status()["synchronized"]
            assert custom.levels("BTCUSD") == session.levels("BTCUSD")
            assert custom.queue("BTCUSD", "buy", 0, 20_000_000_000) == session.queue(
                "BTCUSD", "buy", 0, 20_000_000_000
            )


def test_custom_bitfinex_rejects_corrupted_checksum() -> None:
    with CustomAdapter(
        bitfinex_protocol(),
        bitfinex_source(corrupt=True),
        symbol="BTCUSD",
        mode=lm.FeedMode.Live,
        level=lm.BookLevel.L3,
    ) as custom:
        custom.start()
        with pytest.raises(RuntimeError, match="checksum mismatch"):
            custom.wait()
        assert custom.status()["checksum_checks"] == 1
        assert custom.status()["checksum_failures"] == 1
        assert not custom.status()["synchronized"]
