# Not autogenerated.
"""Exercise the example with public-feed message shapes and a local WebSocket."""

# ruff: noqa: S101, D103
import json
import time
from io import BytesIO
from threading import Event, Thread
from urllib.parse import parse_qs, urlsplit

import pytest
from websockets.sync.server import ServerConnection, serve

from examples.polymarkets import adapter as polymarket
from examples.polymarkets.adapter import build_adapter, discover_instruments, protocol
from lobo.replay.adapters import CustomAdapter
from lobo.replay.adapters import models as lm

TOKENS = {"YES": "1" * 77, "NO": "2" * 77}


def snapshot(symbol: str, size: str = "3") -> dict:
    return {
        "event_type": "book",
        "asset_id": TOKENS[symbol],
        "timestamp": "1000",
        "bids": [{"price": "0.40", "size": "5"}],
        "asks": [{"price": "0.60", "size": size}],
    }


def recorded(*messages: object) -> CustomAdapter:
    return CustomAdapter(
        protocol(TOKENS),
        lm.Source.packets([json.dumps(message).encode() for message in messages]),
        instruments=(lm.Instrument(symbol, 6, 6) for symbol in TOKENS),
        symbol="YES",
        mode=lm.FeedMode.Live,
        level=lm.BookLevel.L2,
    )


@pytest.mark.parametrize("array_frame", [False, True])
def test_snapshot_shapes_and_l2_simulation(*, array_frame: bool) -> None:
    first = snapshot("YES")
    with recorded([first] if array_frame else first) as adapter:
        adapter.start()
        adapter.wait()
        before = adapter.levels("YES")
        adapter.simulate("buy", 5_000_000)
        result = adapter.simulation_report()
        assert result["filled"] == 3_000_000
        assert result["remaining"] == 2_000_000
        assert result["average_price"] == 600_000
        assert result["simulated"]
        assert not result["alternate_timeline"]
        assert adapter.levels("YES") == before


def test_absolute_updates_deletions_and_replacement_snapshot() -> None:
    update = {
        "event_type": "price_change",
        "timestamp": "2000",
        "price_changes": [
            {"asset_id": TOKENS["YES"], "side": "BUY", "price": "0.40", "size": "2"},
            {"asset_id": TOKENS["YES"], "side": "SELL", "price": "0.60", "size": "0"},
            {"asset_id": TOKENS["YES"], "side": "SELL", "price": "0.61", "size": "4"},
        ],
    }
    with recorded([snapshot("YES"), snapshot("NO")], update) as adapter:
        adapter.start()
        adapter.wait()
        assert [(v["price"], v["quantity"]) for v in adapter.levels("YES")] == [
            ("400000", 2_000_000),
            ("610000", 4_000_000),
        ]
        assert adapter.levels("NO")[1]["quantity"] == 3_000_000

    with recorded(snapshot("YES"), update, snapshot("YES", "1.234567")) as adapter:
        adapter.start()
        adapter.wait()
        assert [(v["price"], v["quantity"]) for v in adapter.levels("YES")] == [
            ("400000", 5_000_000),
            ("600000", 1_234_567),
        ]


def test_trade_drives_bars_without_reducing_book_again() -> None:
    release = Event()
    connected = Event()
    complete = Event()
    heartbeat_seen = Event()

    def stream(socket: ServerConnection) -> None:
        subscription = json.loads(socket.recv(timeout=5))
        assert subscription == {"type": "market", "assets_ids": [TOKENS["YES"]]}
        connected.set()
        assert release.wait(5)
        socket.send(json.dumps([snapshot("YES")]))
        socket.send(
            json.dumps(
                {
                    "event_type": "last_trade_price",
                    "asset_id": TOKENS["YES"],
                    "timestamp": "2000",
                    "side": "BUY",
                    "price": "0.60",
                    "size": "1.234567",
                }
            )
        )
        assert socket.recv(timeout=5) == "PING"
        socket.send("PONG")
        heartbeat_seen.set()
        complete.wait(5)

    with serve(stream, "127.0.0.1", 0) as server:
        thread = Thread(target=server.serve_forever)
        thread.start()
        endpoint = f"ws://127.0.0.1:{server.socket.getsockname()[1]}"
        try:
            with CustomAdapter(
                protocol({"YES": TOKENS["YES"]}),
                lm.Source.websocket(
                    endpoint, heartbeat=lm.TextHeartbeat("PING", "PONG", interval=0.05)
                ),
                instruments=[lm.Instrument("YES", 6, 6)],
                symbol="YES",
                mode=lm.FeedMode.Live,
                level=lm.BookLevel.L2,
            ) as adapter:
                adapter.start()
                assert connected.wait(5)
                adapter.set_bar_aggregation("ticks", 1)
                release.set()
                bars = []
                deadline = time.monotonic() + 5
                while not bars and time.monotonic() < deadline:
                    bars = adapter.drain_bars()
                    time.sleep(0.01)
                assert heartbeat_seen.wait(5)
                assert len(bars) == 1
                assert bars[0]["volume"] == 1_234_567
                assert bars[0]["open"] == bars[0]["close"] == 600_000
                assert bars[0]["ticks"] == 1
                assert adapter.levels("YES")[1]["quantity"] == 3_000_000
        finally:
            complete.set()
            server.shutdown()
            thread.join(timeout=5)


@pytest.mark.parametrize(
    "tokens",
    [{}, {"YES": "abc"}, {"YES": "123", "NO": "123"}, {"yes": "123", "YES": "456"}],
)
def test_bad_configuration_fails_before_connecting(tokens: dict[str, str]) -> None:
    with pytest.raises(ValueError):
        build_adapter(tokens)


def market(market_id: int, **changes: object) -> dict:
    return {
        "id": str(market_id),
        "slug": "a-long-market-question-" * 5,
        "active": True,
        "closed": False,
        "archived": False,
        "enableOrderBook": True,
        "acceptingOrders": True,
        "outcomes": '["Yes", "No"]',
        "clobTokenIds": json.dumps([str(market_id * 2), str(market_id * 2 + 1)]),
        "volume24hr": market_id,
        **changes,
    }


def test_discovery_paginates_filters_and_preserves_outcome_identity(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    pages = [
        {"markets": [market(1), market(2, closed=True)], "next_cursor": "next+/="},
        {
            "markets": [
                market(3, acceptingOrders=False),
                market(4),
                market(5, archived=True),
            ]
        },
    ]
    requests = []

    def fetch(request: object, *, timeout: float) -> BytesIO:
        assert timeout == 20
        requests.append(request)
        return BytesIO(json.dumps(pages.pop(0)).encode())

    monkeypatch.setattr(polymarket, "urlopen", fetch)
    tokens = discover_instruments()
    assert len(tokens) == 4
    assert set(tokens.values()) == {"2", "3", "8", "9"}
    assert next(iter(tokens)).endswith("-1-0-YES")
    assert all(len(label) <= 64 and label.isascii() for label in tokens)
    assert parse_qs(urlsplit(requests[1].full_url).query)["after_cursor"] == ["next+/="]
    assert "liquidity_num_min" in requests[0].full_url


@pytest.mark.parametrize(
    "page",
    [
        {"markets": []},
        {"markets": [market(1, outcomes='["Yes"]')]},
        {"markets": [market(1, clobTokenIds='["invalid", "2"]')]},
        {"markets": [market(1)], "next_cursor": "repeated"},
        {"unexpected": []},
    ],
)
def test_invalid_discovery_fails_clearly(
    page: dict,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def fetch(request: object, *, timeout: float) -> BytesIO:  # noqa: ARG001
        return BytesIO(json.dumps(page).encode())

    monkeypatch.setattr(polymarket, "urlopen", fetch)
    with pytest.raises(RuntimeError, match="Polymarket"):
        discover_instruments()


def test_no_argument_builder_registers_discovered_directory(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(polymarket, "discover_instruments", lambda **_: TOKENS)
    with build_adapter() as adapter:
        assert adapter.tickers() == ["NO", "YES"]


def test_discovery_stops_at_1000_markets_sorted_by_liquidity(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    requested = 0

    def fetch(request: object, *, timeout: float) -> BytesIO:  # noqa: ARG001
        nonlocal requested
        params = parse_qs(urlsplit(request.full_url).query)
        assert params["order"] == ["liquidityNum"]
        assert params["ascending"] == ["false"]
        assert params["limit"] == ["100"]
        first = requested * 100 + 1
        requested += 1
        assert requested <= 10
        return BytesIO(
            json.dumps(
                {
                    "markets": [market(i) for i in range(first, first + 100)],
                    "next_cursor": str(requested),
                }
            ).encode()
        )

    monkeypatch.setattr(polymarket, "urlopen", fetch)
    assert len(discover_instruments()) == 2000
    assert requested == 10
