# Not autogenerated.
from datetime import UTC, date, datetime, time, timedelta, timezone, tzinfo
from inspect import signature
from pathlib import Path
from struct import pack
from zoneinfo import ZoneInfo

import polars as pl
import pytest

from lobo import Book
from lobo.levels import levels_lazy
from lobo.replay import ReplayContext
from lobo.replay.adapters import itch


def itch_message(
    tag: str,
    stock_locate: int,
    tracking_number: int,
    timestamp: int,
    body: bytes,
) -> bytes:
    payload = (
        tag.encode("ascii")
        + pack(">HH", stock_locate, tracking_number)
        + timestamp.to_bytes(6, "big")
        + body
    )
    return pack(">H", len(payload)) + payload


def add_message(
    *,
    stock_locate: int,
    tracking_number: int,
    timestamp: int,
    reference: int,
    side: str,
    shares: int,
    stock: str,
    price: int,
) -> bytes:
    return itch_message(
        "A",
        stock_locate,
        tracking_number,
        timestamp,
        pack(
            ">QcI8sI",
            reference,
            side.encode("ascii"),
            shares,
            stock.encode().ljust(8),
            price,
        ),
    )


def stock_directory_message(
    *,
    stock_locate: int,
    tracking_number: int,
    timestamp: int,
    stock: str,
) -> bytes:
    return itch_message(
        "R",
        stock_locate,
        tracking_number,
        timestamp,
        pack(
            ">8sccIcc2scccccIc",
            stock.encode().ljust(8),
            b"Q",
            b"N",
            100,
            b"N",
            b"C",
            b"C ",
            b"P",
            b"N",
            b"N",
            b"1",
            b"N",
            1,
            b"N",
        ),
    )


@pytest.fixture
def itch_path(tmp_path: Path) -> Path:
    second = 1_000_000_000
    messages = [
        itch_message("S", 0, 1, 7 * 60 * 60 * second, b"O"),
        stock_directory_message(
            stock_locate=1,
            tracking_number=2,
            timestamp=(7 * 60 * 60 + 1) * second,
            stock="AAPL",
        ),
        stock_directory_message(
            stock_locate=2,
            tracking_number=3,
            timestamp=(7 * 60 * 60 + 2) * second,
            stock="MSFT",
        ),
        add_message(
            stock_locate=1,
            tracking_number=4,
            timestamp=8 * 60 * 60 * second,
            reference=1,
            side="B",
            shares=100,
            stock="AAPL",
            price=1_010_000,
        ),
        add_message(
            stock_locate=2,
            tracking_number=5,
            timestamp=(8 * 60 * 60 + 1) * second,
            reference=2,
            side="S",
            shares=50,
            stock="MSFT",
            price=2_000_000,
        ),
        itch_message(
            "X",
            1,
            6,
            (8 * 60 * 60 + 2) * second,
            pack(">QI", 1, 25),
        ),
        itch_message(
            "U",
            1,
            7,
            (8 * 60 * 60 + 3) * second,
            pack(">QQII", 1, 3, 80, 1_020_000),
        ),
        itch_message(
            "E",
            1,
            8,
            (8 * 60 * 60 + 4) * second,
            pack(">QIQ", 3, 30, 99),
        ),
        itch_message(
            "D",
            2,
            9,
            (8 * 60 * 60 + 5) * second,
            pack(">Q", 2),
        ),
    ]
    path = tmp_path / "sample.itch"
    path.write_bytes(b"".join(messages))
    return path


def test_itch_source_is_reusable_and_exposes_typed_lazy_frames(
    itch_path: Path,
) -> None:
    source = itch.ItchSource(str(itch_path), "AAPL")

    assert isinstance(source, itch.ItchSource)
    assert Path(source) == itch_path
    assert source.path == str(itch_path)
    assert source.ticker == "AAPL"

    lazy_frame = source.to_lazy_frame()
    assert isinstance(lazy_frame, pl.LazyFrame)
    assert lazy_frame.collect_schema() == pl.Schema(
        {
            "message_type": pl.String,
            "stock_locate": pl.UInt32,
            "tracking_number": pl.UInt32,
            "timestamp": pl.Time,
            "stock": pl.String,
            "operation": pl.String,
            "reference": pl.UInt64,
            "new_reference": pl.UInt64,
            "side": pl.String,
            "shares": pl.UInt32,
            "price": pl.UInt32,
            "execution_price": pl.UInt32,
            "body": pl.String,
        }
    )

    first_read = lazy_frame.select("message_type", "operation").collect()
    second_read = source.to_lazy_frame().select("message_type", "operation").collect()
    assert first_read.equals(second_read)
    assert first_read.height == 9
    assert first_read["message_type"].to_list() == [
        "S",
        "R",
        "R",
        "A",
        "A",
        "X",
        "U",
        "E",
        "D",
    ]
    assert first_read["operation"].to_list() == [
        None,
        None,
        None,
        "add",
        "add",
        "cancel",
        "replace",
        "execute",
        "delete",
    ]

    limited = (
        source.to_lazy_frame()
        .filter(pl.col("operation").is_not_null())
        .select("stock", "operation")
        .head(2)
        .collect()
    )
    assert limited.to_dict(as_series=False) == {
        "stock": ["AAPL", "MSFT"],
        "operation": ["add", "add"],
    }
    assert source.to_lazy_frame().filter(pl.col("stock") == "ZZZZ").collect().is_empty()
    assert source.to_lazy_frame().head(2).collect()["message_type"].to_list() == [
        "S",
        "R",
    ]


def test_itch_source_reads_ticker_directory(itch_path: Path) -> None:
    tickers = itch.ItchSource.read_tickers(str(itch_path))

    assert isinstance(tickers, pl.DataFrame)
    assert tickers.schema == pl.Schema(
        {
            "ticker": pl.String,
            "stock_locate": pl.UInt32,
        }
    )
    assert tickers.to_dict(as_series=False) == {
        "ticker": ["AAPL", "MSFT"],
        "stock_locate": [1, 2],
    }


def test_adapted_messages_retain_full_polars_lazyframe_support(
    itch_path: Path,
) -> None:
    source = itch.ItchSource(str(itch_path), "AAPL")
    messages = source.adapt()

    assert isinstance(messages, itch.ReplayMessages)
    assert not hasattr(messages, "as_lazy_frame")
    assert isinstance(messages.to_lazy_frame(), pl.LazyFrame)
    assert messages.to_lazy_frame().collect().height == 6

    run = (
        messages.to_lazy_frame()
        .filter(pl.col("timestamp").is_between(time(8, 0), time(17, 0)))
        .with_columns(pl.col("stock").str.to_uppercase())
        .sort(["timestamp", "tracking_number"])
    )
    assert isinstance(run, pl.LazyFrame)
    assert run.select("stock").collect()["stock"].to_list() == [
        "AAPL",
        "MSFT",
        "AAPL",
        "AAPL",
        "AAPL",
        "MSFT",
    ]

    raw_aapl = source.to_lazy_frame().filter(
        (pl.col("stock") == "AAPL") & pl.col("operation").is_not_null()
    )
    assert raw_aapl.collect()["operation"].to_list() == [
        "add",
        "cancel",
        "replace",
        "execute",
    ]


def test_itch_source_rejects_an_unknown_ticker(itch_path: Path) -> None:
    with pytest.raises(RuntimeError, match="ticker ZZZZ not found"):
        _ = itch.ItchSource(str(itch_path), "ZZZZ")


def test_replay_context_builds_all_available_ticker_books_in_one_pass(
    itch_path: Path,
) -> None:
    sources = itch.ItchSource.all_available(str(itch_path))
    assert [source.ticker for source in sources] == ["AAPL", "MSFT"]

    with ReplayContext(source=sources, collect_stats=True, cutoff_time=None) as books:
        assert books.keys() == ["aapl", "msft"]
        assert books.message_count == 6
        assert books["aapl"].best_bid == 1_020_000
        assert books["aapl"].orders.bids.visible_quantity == 50
        assert books["msft"].best_bid is None
        assert books["msft"].best_ask is None


def test_replay_context_accepts_multiple_sources(itch_path: Path) -> None:
    sources = [itch.ItchSource(str(itch_path), "AAPL"), itch.ItchSource(str(itch_path), "MSFT")]

    with ReplayContext(source=sources, collect_stats=True, cutoff_time=None) as books:
        assert books.keys() == ["aapl", "msft"]
        assert books.message_count == 6


def test_replay_context_can_skip_statistics_without_changing_books(
    itch_path: Path,
) -> None:
    with ReplayContext(
        source=itch.ItchSource.all_available(str(itch_path)),
        collect_stats=False,
        cutoff_time=None,
    ) as books:
        assert books.keys() == ["aapl", "msft"]
        assert books.message_count == 0
        assert books["aapl"].best_bid == 1_020_000
        assert books["aapl"].orders.bids.visible_quantity == 50
        assert books["msft"].best_bid is None
        assert books["msft"].best_ask is None


def test_replay_context_uses_native_source_book_and_live_level_views(
    itch_path: Path,
) -> None:
    context = ReplayContext(
        source=itch.ItchSource(str(itch_path), "AAPL"), collect_stats=True, cutoff_time=None
    )

    with pytest.raises(RuntimeError, match="must be entered"):
        _ = context["aapl"]

    with context as books:
        assert books is context
        assert len(books) == 1
        assert books.keys() == ["aapl"]
        assert "AAPL" in books
        assert books.message_count == 4
        assert books.skipped_message_count == 0

        apple_book = books["aapl"]
        assert apple_book.best_bid == 1_020_000
        assert apple_book.best_ask is None
        assert apple_book.orders.bids.order_count == 1
        assert apple_book.orders.bids.visible_quantity == 50
        assert apple_book.orders.asks.order_count == 0
        assert levels_lazy(apple_book.orders.bids).collect().to_dict(
            as_series=False
        ) == {
            "price": [1_020_000],
            "quantity": [50],
            "hidden_quantity": [0],
            "order_count": [1],
        }
        assert levels_lazy(apple_book.orders.bids).filter(
            pl.col("quantity") > 0
        ).select("price").collect().to_dict(as_series=False) == {"price": [1_020_000]}


def test_replay_uses_the_public_book_type(itch_path: Path) -> None:
    with ReplayContext(
        source=itch.ItchSource(str(itch_path), "AAPL"), cutoff_time=None
    ) as books:
        assert type(books["aapl"]) is Book


def test_replay_context_uses_the_source_ticker_setting(itch_path: Path) -> None:
    with ReplayContext(
        source=itch.ItchSource(str(itch_path), "MSFT"), collect_stats=True, cutoff_time=None
    ) as books:
        assert books.keys() == ["msft"]
        assert books.message_count == 2
        assert books["msft"].best_bid is None
        assert books["msft"].best_ask is None


@pytest.mark.parametrize("collect_stats", [False, True])
@pytest.mark.parametrize("concurrent", [False, True])
@pytest.mark.parametrize(
    "cutoff",
    [
        datetime(2026, 1, 15, 13, 0, 2, tzinfo=UTC),
        datetime(2026, 7, 15, 12, 0, 2, tzinfo=UTC),
        datetime(2026, 7, 15, 8, 0, 2, tzinfo=ZoneInfo("America/New_York")),
        datetime(
            2026, 7, 15, 17, 30, 2, tzinfo=timezone(timedelta(hours=5, minutes=30))
        ),
    ],
)
def test_cutoff_is_inclusive_across_timezones_and_replay_modes(
    itch_path: Path, cutoff: datetime, collect_stats: bool, concurrent: bool
) -> None:
    options = {}
    if "concurrent" in signature(ReplayContext).parameters:
        options["concurrent"] = concurrent
    elif concurrent:
        pytest.skip("extension was built without concurrent replay")

    with ReplayContext(
        source=itch.ItchSource.all_available(str(itch_path)),
        cutoff_time=cutoff,
        collect_stats=collect_stats,
        **options,
    ) as books:
        assert books.cutoff_time == cutoff.astimezone(UTC)
        assert books["aapl"].best_bid == 1_010_000
        assert books["aapl"].orders.bids.visible_quantity == 75
        assert books["msft"].best_ask == 2_000_000
        assert books["msft"].orders.asks.visible_quantity == 50
        assert books.message_count == (3 if collect_stats else 0)


def test_none_and_omitted_cutoffs_replay_the_full_feed_after_source_reuse(
    itch_path: Path,
) -> None:
    source = itch.ItchSource(str(itch_path), "AAPL")
    with ReplayContext(
        source=source, cutoff_time=datetime(2026, 1, 15, 13, 0, 2, tzinfo=UTC)
    ) as partial:
        assert partial["aapl"].orders.bids.visible_quantity == 75
    for options in ({}, {"cutoff_time": None}):
        with ReplayContext(source=source, collect_stats=True, **options) as full:
            assert full.cutoff_time is None
            assert full.message_count == 4
            assert full["aapl"].best_bid == 1_020_000
            assert full["aapl"].orders.bids.visible_quantity == 50


def test_cutoff_preserves_microseconds_at_nanosecond_message_boundaries(
    tmp_path: Path,
) -> None:
    cutoff_ns = (8 * 3_600 + 2) * 1_000_000_000 + 321_817_000
    path = tmp_path / "precision.itch"
    path.write_bytes(
        stock_directory_message(
            stock_locate=1, tracking_number=1, timestamp=0, stock="AAPL"
        )
        + b"".join(
            add_message(
                stock_locate=1,
                tracking_number=reference + 1,
                timestamp=cutoff_ns + offset,
                reference=reference,
                side="B",
                shares=1,
                stock="AAPL",
                price=1_010_000,
            )
            for reference, offset in enumerate((-1, 0, 1), start=1)
        )
    )
    with ReplayContext(
        source=itch.ItchSource(str(path), "AAPL"),
        cutoff_time=datetime(
            2026, 7, 15, 8, 0, 2, 321_817, tzinfo=ZoneInfo("America/New_York")
        ),
        collect_stats=True,
    ) as books:
        assert books.message_count == 2
        assert books["aapl"].orders.bids.visible_quantity == 2


@pytest.mark.parametrize("fold", [0, 1])
def test_cutoff_normalization_respects_the_dst_fold(itch_path: Path, fold: int) -> None:
    cutoff = datetime(
        2026, 11, 1, 1, 30, tzinfo=ZoneInfo("America/New_York"), fold=fold
    )
    context = ReplayContext(
        source=itch.ItchSource(str(itch_path), "AAPL"), cutoff_time=cutoff
    )
    assert context.cutoff_time == datetime(2026, 11, 1, 5 + fold, 30, tzinfo=UTC)


class NoOffsetTimezone(tzinfo):
    def utcoffset(self, dt: datetime | None) -> None:
        return None


@pytest.mark.parametrize(
    "cutoff",
    [datetime(2026, 1, 15, 8), datetime(2026, 1, 15, 8, tzinfo=NoOffsetTimezone())],
)
def test_cutoff_rejects_naive_datetimes_at_construction(
    itch_path: Path, cutoff: datetime
) -> None:
    with pytest.raises(
        ValueError, match="cutoff_time must be a timezone-aware datetime"
    ):
        ReplayContext(source=itch.ItchSource(str(itch_path), "AAPL"), cutoff_time=cutoff)


@pytest.mark.parametrize(
    "cutoff", ["2026-01-15T13:00:02Z", 123, date(2026, 1, 15), time(8)]
)
def test_cutoff_rejects_non_datetime_values(itch_path: Path, cutoff: object) -> None:
    with pytest.raises(TypeError):
        ReplayContext(source=itch.ItchSource(str(itch_path), "AAPL"), cutoff_time=cutoff)


@pytest.mark.parametrize("collect_stats", [False, True])
def test_replay_feather_sink_stays_connected_for_followup_fills(
    itch_path: Path, tmp_path: Path, collect_stats: bool
) -> None:
    from uuid import UUID

    from lobo.orders import MarketOrder, Side
    from lobo.sinks import FeatherSink, read_feather

    sink = FeatherSink(tmp_path / "replay.feather", batch_size=2)
    with ReplayContext(
        source=itch.ItchSource(str(itch_path), "AAPL"),
        collect_stats=collect_stats,
        sinks=[sink],
    ) as books:
        books["aapl"].fill(MarketOrder(10, UUID(int=1), Side.Sell))
        assert not sink.finished
    frame = pl.read_ipc(sink.path)
    assert frame.equals(read_feather(sink))
    assert frame["visible_quantity"].to_list() == [100, 75, 0, 80, 50, 40]
    assert frame["sequence_number"].to_list() == [1, 2, 3, 4, 5, 6]
    assert frame["book_id"].n_unique() == 1
    assert sink.finished
