# Not autogenerated.
"""Python construction scopes and the HTTP API share native order books."""

# Local HTTP fixtures only.
# ruff: noqa: S101, D103, S310
import asyncio
import json
from concurrent.futures import ThreadPoolExecutor
from contextlib import nullcontext
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import Request, urlopen
from uuid import UUID

import pytest

from lobo import (
    Book,
    CheckSum,
    Execution,
    Reports,
    server_context,
)
from lobo.orders import IcebergOrder, LimitOrder, MarketOrder, Side


def read_json(url: str, command: dict | None = None) -> object:
    request = Request(
        url,
        data=None if command is None else json.dumps(command).encode(),
        headers={"Content-Type": "application/json"},
    )
    with urlopen(request, timeout=5) as response:
        return json.load(response)


@pytest.fixture
def web_root(tmp_path: Path) -> Path:
    (tmp_path / "index.html").write_text("<title>Native terminal</title>")
    return tmp_path


POLICIES = [
    ("full", True, True),
    ("no_user_map", False, True),
    ("no_hidden_quantity", True, False),
    ("no_updates", False, False),
]


@pytest.mark.parametrize("policy,users,hidden", POLICIES)
@pytest.mark.parametrize("hosted", [False, True])
@pytest.mark.parametrize("checksum", [CheckSum.Null, CheckSum.Kraken, CheckSum.BitFinex])
def test_concrete_policies_keep_matching_and_fifo_identical(
    web_root: Path,
    policy: str,
    *,
    users: bool,
    hidden: bool,
    hosted: bool,
    checksum: CheckSum,
) -> None:
    context = server_context(port=0, web_root=web_root) if hosted else nullcontext()
    with context as server:
        book = Book("POLICY", update_user_map=users, update_hidden=hidden, check_sum_spec=checksum)
        assert type(book) is Book
        assert book.check_sum_spec == checksum
        assert book.update_user_map is users
        assert book.update_hidden is hidden
        trader = UUID(int=1)
        reports = Reports(include_fills=True)
        iceberg = book.fill(IcebergOrder(100, 3, trader, Side.Sell, 6))
        limit = book.fill(LimitOrder(100, 4, trader, Side.Sell))
        assert book.orders.asks.visible_quantity == 7
        assert book.orders.asks.hidden_quantity == (6 if hidden else 0)
        summary = book.get_user_order_summary(trader)
        assert summary.order_count == (2 if users else 0)
        if hosted:
            assert type(server["POLICY"]) is Book
            assert type(server.book("POLICY")) is Book
            assert read_json(f"{server.url}/api/books")[0]["policy"] == policy

        # The selected native policy determines whether reserve is matchable.
        preview = book.fill(
            MarketOrder(13, UUID(int=2), Side.Buy),
            reports,
            execution=Execution.Simulation,
        )
        assert sum(fill.fill_quantity for fill in preview.report.fills) == (
            13 if hidden else 7
        )
        assert book.orders.asks.visible_quantity == 7
        book.fill(MarketOrder(3, UUID(int=3), Side.Buy))
        assert book.orders.asks.order_count == (2 if hidden else 1)
        assert book.get_user_order_summary(trader).order_count == (
            (2 if hidden else 1) if users else 0
        )
        filled = book.fill(
            MarketOrder(6 if hidden else 3, UUID(int=4), Side.Buy), reports
        )
        expected = (
            [(limit.remaining_order_id, 4), (iceberg.remaining_order_id, 2)]
            if hidden
            else [(limit.remaining_order_id, 3)]
        )
        assert [
            (f.maker_order_id, f.fill_quantity) for f in filled.report.fills
        ] == expected
        assert book.orders.asks.hidden_quantity == (3 if hidden else 0)
        book.cancel(iceberg.remaining_order_id if hidden else limit.remaining_order_id)
        assert book.orders.asks.visible_quantity == 0
        assert book.orders.asks.hidden_quantity == 0
        assert book.orders.asks.order_count == 0
        assert book.get_user_order_summary(trader).order_count == 0


def test_books_created_in_scope_share_python_and_api_state(web_root: Path) -> None:
    outside = Book("OUTSIDE")
    with server_context(port=0, web_root=web_root, price_decimals=2) as server:
        books = [Book("AAPL"), Book("MSFT")]
        assert server.keys() == ["AAPL", "MSFT"]
        config = read_json(f"{server.url}/api/server-context")
        assert [b["symbol"] for b in config["books"]] == server.keys()
        assert len(config["adapters"]) == 1
        assert config["adapters"][0]["id"] == "server"
        assert config["adapters"][0]["endpoint"] == "/api/feed"
        assert not config["adapters"][0].get("observer", False)
        result = books[0].fill(LimitOrder(10100, 10, UUID(int=1), Side.Sell))
        snapshot = read_json(f"{server.url}/api/books/AAPL")
        assert snapshot["orders"][0]["order"]["quantity"] == 10
        response = read_json(
            f"{server.url}/api/books/AAPL/orders",
            {
                "op": "execute",
                "id": str(result.remaining_order_id),
                "quantity": 4,
            },
        )
        assert response["filled"] == 4
        assert books[0].orders.asks.visible_quantity == 6
        assert server["AAPL"].orders.asks.visible_quantity == 6
        assert outside.best_bid is None
        with pytest.raises(ValueError, match="already exists"):
            Book("AAPL")
        assert Book().best_bid is None
    assert server.closed
    server.close()
    # Closing transport preserves book references held by the caller.
    books[0].fill(MarketOrder(6, UUID(int=2), Side.Buy))
    assert books[0].orders.asks.visible_quantity == 0


def test_simulation_is_explicit_and_never_changes_the_main_book(web_root: Path) -> None:
    with server_context(port=0, web_root=web_root) as server:
        book = Book("TEST")
        book.fill(LimitOrder(100, 20, UUID(int=1), Side.Sell))
        command = {
            "op": "simulate",
            "order": {
                "type": "market",
                "id": str(UUID(int=2)),
                "side": "buy",
                "quantity": 25,
            },
        }
        preview = read_json(f"{server.url}/api/books/TEST/orders", command)
        assert preview["simulated"] is True
        assert preview["filled"] == 20
        assert preview["remaining"] == 5
        assert preview["resting_order_id"] is None
        assert book.orders.asks.visible_quantity == 20
        book.fill(MarketOrder(5, UUID(int=3), Side.Buy), execution=Execution.Simulation)
        assert book.orders.asks.visible_quantity == 20


def test_nested_contexts_and_worker_threads_route_to_the_correct_server(
    web_root: Path,
) -> None:
    with server_context(port=0, web_root=web_root) as outer:
        Book("OUTER")
        with server_context(port=0, web_root=web_root) as inner:
            Book("INNER")
            assert inner.keys() == ["INNER"]
        Book("AFTER")
        assert outer.keys() == ["AFTER", "OUTER"]
        with ThreadPoolExecutor(max_workers=2) as workers:
            book = workers.submit(outer.book, "WORKER").result()
            workers.submit(
                book.fill, LimitOrder(100, 5, UUID(int=1), Side.Buy)
            ).result()
        assert (
            read_json(f"{outer.url}/api/books/WORKER")["orders"][0]["order"]["quantity"]
            == 5
        )


def test_async_construction_scopes_do_not_leak_between_tasks(web_root: Path) -> None:
    async def create(name: str) -> list[str]:
        with server_context(port=0, web_root=web_root) as server:
            await asyncio.sleep(0)
            Book(name)
            await asyncio.sleep(0)
            return server.keys()

    async def together() -> list[list[str]]:
        return await asyncio.gather(create("ONE"), create("TWO"))

    assert asyncio.run(together()) == [["ONE"], ["TWO"]]


def test_failed_requests_and_context_exceptions_leave_no_running_server(
    web_root: Path,
) -> None:
    with (
        pytest.raises(RuntimeError, match="test failure"),
        server_context(port=0, web_root=web_root) as server,
    ):
        Book("TEST")
        with pytest.raises(HTTPError) as failure:
            read_json(
                f"{server.url}/api/books/TEST/orders",
                {"op": "remove", "id": str(UUID(int=99))},
            )
        assert failure.value.code == 404
        raise RuntimeError("test failure")
    assert server.closed
    assert Book("TEST").best_bid is None


@pytest.mark.parametrize("metrics", [0, 1])
def test_gpu_observer_configuration_is_independent_of_book_policies(
    web_root: Path, metrics: int
) -> None:
    from lobo.sinks import GpuSink

    with server_context(
        port=0, web_root=web_root, sinks=[GpuSink(metrics=metrics)]
    ) as server:
        Book("FULL")
        Book("VISIBLE", update_hidden=False)
        config = read_json(f"{server.url}/api/server-context")
        assert config["metrics"] == metrics
        assert [book["policy"] for book in config["books"]] == [
            "full",
            "no_hidden_quantity",
        ]


@pytest.mark.parametrize("policy,users,hidden", POLICIES)
def test_iceberg_api_reports_only_quantities_enabled_by_the_native_policy(
    web_root: Path,
    policy: str,
    *,
    users: bool,
    hidden: bool,
) -> None:
    with server_context(port=0, web_root=web_root) as server:
        book = Book("TAKER", update_user_map=users, update_hidden=hidden)
        book.fill(LimitOrder(100, 1, UUID(int=1), Side.Sell))
        result = read_json(
            f"{server.url}/api/books/TAKER/orders",
            {
                "op": "fill",
                "order": {
                    "type": "iceberg",
                    "id": str(UUID(int=2)),
                    "side": "buy",
                    "quantity": 3,
                    "price": 100,
                    "peak_quantity": 3,
                    "hidden_quantity": 6,
                },
            },
        )
        assert result["filled"] == 1
        assert result["remaining"] == (8 if hidden else 2)
        snapshot = read_json(f"{server.url}/api/books/TAKER")
        assert snapshot["book"]["policy"] == policy
        assert snapshot["orders"][0]["order"]["type"] == (
            "iceberg" if hidden else "limit"
        )
        assert book.orders.bids.hidden_quantity == (6 if hidden else 0)
        assert book.get_user_order_summary(UUID(int=0)).order_count == (
            1 if users else 0
        )
