# Not autogenerated.
"""Python-defined protocols drive books, simulations, and the served feed."""

# Local HTTP fixtures only.
# ruff: noqa: S101, D103, S310
import json
from pathlib import Path
from urllib.request import Request, urlopen
from uuid import UUID

import pytest
from websockets.sync.client import connect

from lobo import server_context
from lobo.replay.adapters import CustomAdapter, Protocol
from lobo.replay.adapters import expressions as le
from lobo.replay.adapters import models as lm


def adapter(*, threshold: int = 0) -> CustomAdapter:
    # These wire names are defined here, not by an existing exchange adapter.
    protocol = Protocol(
        lm.Json(
            lm.Message(
                le.Field("event").eq("initial") & le.Field("ticket").gt(threshold),
                lm.Book(
                    "XYZ",
                    lm.Add(
                        id=le.Field("ticket"),
                        side=le.Field("direction").map({"supply": "sell"}),
                        price=le.Field("rate"),
                        quantity=le.Field("amount"),
                    ),
                    snapshot=True,
                    timestamp=100,
                ),
            )
        )
    )
    packet = {
        "event": "initial",
        "ticket": 2**64 - 1,
        "direction": "supply",
        "rate": 120,
        "amount": 100,
    }
    return CustomAdapter(
        protocol,
        lm.Source.packets([json.dumps(packet).encode()]),
        instruments=(lm.Instrument(symbol, 2, 0) for symbol in ["XYZ"]),
        symbol="XYZ",
        name="Test market",
    )


def read_json(url: str, command: dict | None = None) -> object:
    request = Request(
        url,
        data=None if command is None else json.dumps(command).encode(),
        headers={"Content-Type": "application/json"},
    )
    with urlopen(request, timeout=5) as response:
        return json.load(response)


def test_definition_drives_book_and_simulation() -> None:
    with adapter() as feed:
        feed.start()
        feed.wait()
        assert feed.tickers() == ["XYZ"]
        assert feed.levels("XYZ")[0]["quantity"] == 100
        assert feed.queue("XYZ", "sell", 0, 1000)[0][0] == 2**64 - 1
        feed.simulate("buy", 30)
        report = feed.simulation_report()
        assert report["filled"] == 30
        assert report["average_price"] == 120
        assert report["simulated"]
        assert not report["alternate_timeline"]
        assert feed.levels("XYZ")[0]["quantity"] == 100


def test_exact_order_ids_in_conditions() -> None:
    with adapter(threshold=2**64 - 2) as feed:
        feed.start()
        feed.wait()
        assert feed.queue("XYZ", "sell", 0, 1000)[0][0] == 2**64 - 1


def test_constructor_requires_a_protocol_definition() -> None:
    with pytest.raises(TypeError, match="Protocol"):
        CustomAdapter(object(), lm.Source.packets([]))


def test_binary_definition_preserves_side_aliases_and_default(tmp_path: Path) -> None:
    protocol = Protocol(
        lm.Binary(
            length=lm.UInt(0, 1),
            tag=lm.UInt(0, 1),
            key=lm.UInt(1, 1),
            timestamp=lm.UInt(2, 1),
            records={
                1: lm.Record(
                    size=6,
                    fields={"symbol": lm.Text(3, 3)},
                    actions=(
                        lm.Register(
                            symbol=le.Field("symbol"),
                            key=le.Variable("key"),
                            price_decimals=2,
                            quantity_decimals=0,
                        ),
                    ),
                ),
                2: lm.Record(
                    size=8,
                    fields={
                        "id": lm.UInt(3, 1),
                        "side": lm.UInt(4, 1),
                        "price": lm.UInt(5, 2),
                        "quantity": lm.UInt(7, 1),
                    },
                    actions=(
                        lm.Add(
                            id=le.Field("id"),
                            side=le.Field("side").map(
                                {1: "buy", 2: "buy", 3: "sell"}, default="sell"
                            ),
                            price=le.Field("price"),
                            quantity=le.Field("quantity"),
                        ),
                    ),
                ),
            },
        )
    )
    path = tmp_path / "market.records"
    path.write_bytes(
        b"\x06\x01\x01\x01XYZ"
        + bytes([8, 2, 1, 2, 10, 2, 0, 100, 5, 8, 2, 1, 3, 11, 99, 0, 110, 7])
    )
    with CustomAdapter(
        protocol, lm.Source.file(path), symbol="XYZ", mode=lm.FeedMode.Replay
    ) as feed:
        books = feed.run(concurrent=False)
        book = books["xyz"]
        assert (book.best_bid, book.best_ask) == (100, 110)
        assert (
            book.orders.bids.visible_quantity,
            book.orders.asks.visible_quantity,
        ) == (5, 7)
    with CustomAdapter(
        protocol, lm.Source.file(path), symbol="XYZ", mode=lm.FeedMode.Replay
    ) as feed:
        feed.start()
        feed.wait()
        assert [(row["price"], row["quantity"]) for row in feed.levels("XYZ")] == [
            ("100", 5),
            ("110", 7),
        ]


def test_served_adapter_shares_orders_and_publishes_updates(tmp_path: Path) -> None:
    (tmp_path / "index.html").write_text("<title>Test terminal</title>")
    feed = adapter()
    with server_context(adapters=[feed], port=0, web_root=tmp_path) as terminal:
        feed.wait()
        config = read_json(f"{terminal.url}/api/server-context")
        assert terminal.keys() == ["XYZ"]
        assert [book["symbol"] for book in config["books"]] == ["XYZ"]
        served = config["adapters"][0]
        assert served["observer"]
        assert served["level"] == "l3"
        endpoint = terminal.url.replace("http://", "ws://") + served["endpoint"]
        with connect(endpoint) as websocket:
            snapshot = json.loads(websocket.recv(timeout=5))
            assert snapshot["type"] == "snapshot"
            response = read_json(
                f"{terminal.url}/api/adapters/0/orders",
                {
                    "book": "XYZ",
                    "command": {
                        "op": "fill",
                        "order": {
                            "type": "market",
                            "side": "buy",
                            "quantity": 25,
                            "id": str(UUID(int=123)),
                        },
                    },
                },
            )
            assert response["filled"] == 25
            assert response["average_price"] == 120
            assert feed.levels("XYZ")[0]["quantity"] == 75
            update = json.loads(websocket.recv(timeout=5))
            while update["type"] == "heartbeat":
                update = json.loads(websocket.recv(timeout=5))
            assert update["type"] == "update"
            assert update["sequence"] == snapshot["sequence"] + 1
