# Not autogenerated.
"""Streaming Feather behavior through the public Python API."""

# ruff: noqa: S101, D103
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from threading import Event
from time import monotonic, sleep
from uuid import UUID

import polars as pl
import pytest

from lobo.context import Context
from lobo.orders import IcebergOrder, LimitOrder, MarketOrder, Side
from lobo.sinks import FeatherSink, GpuSink, PriceLevelMetrics, read_feather

TRADER = UUID(int=1)


def wait_for_rows(sink: FeatherSink, count: int) -> None:
    deadline = monotonic() + 5
    while sink.rows_written < count:
        if monotonic() > deadline:
            raise AssertionError(f"sink stalled at {sink.rows_written} rows")
        sleep(0.001)


def test_defaults_validation_and_connection_lifecycle(tmp_path: Path) -> None:
    sink = FeatherSink(tmp_path / "updates.feather")
    assert sink.batch_size == 8192
    assert sink.buffer_size == 262144
    assert Path(sink) == tmp_path / "updates.feather"
    assert not sink.started
    assert not Path(sink).exists()
    with pytest.raises(RuntimeError, match="not been connected"):
        read_feather(sink)
    with Context(sinks=[sink]) as context:
        assert sink.started
        assert read_feather(sink).is_empty()
        assert context.book("SIM") is context.book("SIM")
        assert len(context) == 1
        assert context.keys() == ["SIM"]
        assert context["SIM"] is context.book("SIM")
        with pytest.raises(KeyError):
            context["missing"]
        with pytest.raises(ValueError, match="empty"):
            context.book(" ")
    assert sink.finished
    assert pl.read_ipc(sink.path).is_empty()
    context.close()
    with pytest.raises(RuntimeError, match="closed"):
        context.book("new")
    with pytest.raises(ValueError, match="unused"):
        Context(sinks=[sink])
    for option in ("batch_size", "buffer_size"):
        with pytest.raises(ValueError, match="greater than zero"):
            FeatherSink(tmp_path / "invalid.feather", **{option: 0})


def test_sink_refuses_accidental_overwrite_and_missing_directory(
    tmp_path: Path,
) -> None:
    path = tmp_path / "existing.feather"
    path.write_bytes(b"keep this")
    with pytest.raises(FileExistsError):
        Context(sinks=[FeatherSink(path)])
    assert path.read_bytes() == b"keep this"
    with Context(sinks=[FeatherSink(path, overwrite=True)]):
        pass
    assert pl.read_ipc(path).is_empty()
    with pytest.raises(FileNotFoundError):
        Context(sinks=[FeatherSink(tmp_path / "missing" / "out.feather")])
    sink = FeatherSink(tmp_path / "duplicate.feather")
    with pytest.raises(ValueError, match="distinct"):
        Context(sinks=[sink, sink])
    assert not Path(sink).exists()


def test_feather_snapshots_are_from_disk_while_fills_continue(tmp_path: Path) -> None:
    sink = FeatherSink(tmp_path / "updates.feather", batch_size=2, buffer_size=4096)
    release_producer = Event()
    ready = Event()

    def fill() -> None:
        with Context(sinks=[sink]) as context:
            book = context.book("SIM")
            book.fill(LimitOrder(100, 5, TRADER, Side.Sell))
            book.fill(MarketOrder(2, TRADER, Side.Buy))
            ready.set()
            if not release_producer.wait(5):
                raise TimeoutError("test did not release fill worker")
            book.fill(MarketOrder(3, TRADER, Side.Buy))

    with ThreadPoolExecutor(max_workers=1) as executor:
        producer = executor.submit(fill)
        try:
            assert ready.wait(5)
            wait_for_rows(sink, 2)
            assert not producer.done()
            assert not sink.finished
            live = read_feather(sink)
            assert live["visible_quantity"].to_list() == [5, 3]
            assert live["sequence_number"].to_list() == [1, 2]
            assert live["side"].to_list() == [1, 1]
            assert live["book_id"].to_list() == ["SIM", "SIM"]
            assert [int.from_bytes(value, "big") for value in live["price"]] == [
                100,
                100,
            ]
        finally:
            release_producer.set()
        producer.result(timeout=5)
    assert sink.finished
    assert sink.rows_written == 3
    assert sink.batches_written == 2
    final = pl.read_ipc(sink.path)
    assert final.equals(read_feather(sink))
    assert final["visible_quantity"].to_list() == [5, 3, 0]
    assert final["number_of_orders"].to_list() == [1, 1, 0]


def test_multiple_sinks_and_iceberg_fill_updates(tmp_path: Path) -> None:
    first = FeatherSink(tmp_path / "first.feather", batch_size=2)
    second = FeatherSink(tmp_path / "second.feather", batch_size=3)
    with Context(sinks=[first, second]) as context:
        book = context.book("ICE")
        book.fill(IcebergOrder(100, 2, TRADER, Side.Buy, 4))
        book.fill(MarketOrder(2, TRADER, Side.Sell))
        book.fill(MarketOrder(1, TRADER, Side.Sell))
    expected = pl.read_ipc(first.path)
    assert expected.equals(pl.read_ipc(second.path))
    assert expected["visible_quantity"].to_list() == [2, 2, 1]
    assert expected["hidden_quantity"].to_list() == [4, 2, 2]
    assert expected["side"].to_list() == [0, 0, 0]
    # Books may outlive their context; they are disconnected at exit.
    book.fill(MarketOrder(1, TRADER, Side.Sell))
    assert first.rows_written == second.rows_written == 3


def test_body_exception_still_finalizes_partial_batch(tmp_path: Path) -> None:
    sink = FeatherSink(tmp_path / "exception.feather")
    with (
        pytest.raises(ValueError, match="body failure"),
        Context(sinks=[sink]) as context,
    ):
        context.book("SIM").fill(LimitOrder(100, 1, TRADER, Side.Buy))
        raise ValueError("body failure")
    assert sink.finished
    assert pl.read_ipc(sink.path).height == 1


def test_sink_metrics_filter_observers_without_changing_hidden_matching(
    tmp_path: Path,
) -> None:
    visible = FeatherSink(
        tmp_path / "visible.feather", batch_size=1, metrics=PriceLevelMetrics.NONE
    )
    reserves = FeatherSink(
        tmp_path / "reserves.feather",
        batch_size=1,
        metrics=PriceLevelMetrics.HIDDEN_QUANTITY,
    )
    with Context(sinks=[visible, reserves]) as context:
        book = context.book("RESERVES")
        book.fill(IcebergOrder(100, 3, TRADER, Side.Sell, 6))
        assert book.orders.asks.hidden_quantity == 6
        book.fill(MarketOrder(3, TRADER, Side.Buy))
        assert book.orders.asks.hidden_quantity == 3
        book.fill(MarketOrder(6, TRADER, Side.Buy))
        assert book.orders.asks.visible_quantity == 0
    plain = read_feather(visible)
    full = read_feather(reserves)
    assert plain.drop("hidden_quantity").equals(full.drop("hidden_quantity"))
    assert plain["hidden_quantity"].to_list() == [0] * plain.height
    assert full["hidden_quantity"].max() == 6
    assert GpuSink().metrics == PriceLevelMetrics.NONE
    assert GpuSink(metrics=PriceLevelMetrics.HIDDEN_QUANTITY).metrics == 1
    with pytest.raises(ValueError, match="metric"):
        GpuSink(metrics=2)
    with pytest.raises(ValueError, match="metric"):
        FeatherSink(tmp_path / "invalid.feather", metrics=2)
