# Not autogenerated.
from uuid import uuid4

import polars as pl

from lobo import Book
from lobo.levels import levels_lazy
from lobo.orders import LimitOrder, Side


def populated_bid_levels() -> tuple[Book, pl.LazyFrame]:
    book = Book()
    trader = uuid4()
    for price, quantity in [(99, 2), (101, 4), (100, 3)]:
        book.fill(LimitOrder(price, quantity, trader, Side.Buy))
    return book, levels_lazy(book.orders.bids)


def test_levels_lazy_collects_all_levels_in_book_priority_order() -> None:
    book, levels = populated_bid_levels()

    result = levels.collect()

    assert result.schema == {
        "price": pl.UInt64,
        "quantity": pl.UInt64,
        "hidden_quantity": pl.UInt64,
        "order_count": pl.UInt64,
    }
    assert result.to_dict(as_series=False) == {
        "price": [101, 100, 99],
        "quantity": [4, 3, 2],
        "hidden_quantity": [0, 0, 0],
        "order_count": [1, 1, 1],
    }
    assert book.best_bid == 101


def test_levels_lazy_pushes_projection_predicate_and_row_limit_to_source() -> None:
    _, levels = populated_bid_levels()

    result = (
        levels.filter(pl.col("price") >= 100)
        .select("price", "quantity")
        .head(1)
        .collect()
    )

    assert result.to_dict(as_series=False) == {
        "price": [101],
        "quantity": [4],
    }


def test_levels_lazy_handles_an_empty_side() -> None:
    book = Book()
    result = levels_lazy(book.orders.asks).collect()

    assert result.is_empty()
    assert result.columns == [
        "price",
        "quantity",
        "hidden_quantity",
        "order_count",
    ]
