"""
AUTOGENERATED FROM RUST. DO NOT EDIT.
"""

from collections.abc import Iterable
from typing import Any, final

from .models import Action, AdapterInfo, Bootstrap, Format

@final
class AdapterSession:
    """
    Access books, executions, and simulations while an adapter consumes its source.
    
    Obtain a session from a source's start() method. The worker continues receiving
    messages while Python inspects its books. Use a with block to stop the worker
    when leaving the scope, including when an exception occurs.
    
    Examples:
        ```python
        from lobo.replay.adapters import kraken
    
        with kraken.KrakenSource("BTC/USD").start() as session:
            available = session.tickers()
        ```
    """
    def __enter__(self, /) -> AdapterSession:
        """
        Return this running session and close it automatically when the scope exits.
        """
    def __exit__(self, /, _ty: Any, _value: Any, _trace: Any) -> None:
        """
        Close this session when its with block exits.
        
        Args:
            _ty: The exception type supplied by Python, or None.
            _value: The exception instance supplied by Python, or None.
            _trace: The exception traceback supplied by Python, or None.
        
        Returns:
            None. Exceptions from the context body are not suppressed.
        """
    def close(self, /) -> None:
        """
        Stop the worker and release its books. Repeated calls are safe.
        """
    def drain_bars(self, /) -> Any:
        """
        Take completed OHLC bars from the current timeline's output queue.
        
        Returns:
            A list of dictionaries with symbol, open, high, low, close, volume, ticks,
            index, start_ns, and end_ns. Price and volume use instrument atoms. Bars
            are removed from the queue, so a subsequent call returns only new output.
        
        Raises:
            RuntimeError: The adapter has no started session.
        """
    @property
    def finished(self, /) -> bool:
        """
        Whether the source has finished; wait() reports a completed source's error.
        """
    @property
    def info(self, /) -> AdapterInfo:
        """
        The running source's identity, feed mode, and book level.
        """
    def levels(self, /, symbol: str) -> Any:
        """
        Read price levels from a book on the currently displayed timeline.
        
        Args:
            symbol: The registered book symbol to inspect.
        
        Returns:
            A list of dictionaries with side, price, quantity, hidden, and orders.
            Price is decimal text containing integer atoms; quantities are integer atoms.
            Hidden totals can be zero when their book policy disables maintenance.
        
        Raises:
            RuntimeError: The adapter has no started session or the book is unavailable.
        """
    def queue(self, /, symbol: str, side: str, min_price: int, max_price: int) -> list[tuple[int, int, int, int]]:
        """
        Read resting L3 orders within an inclusive range of price levels.
        
        The view preserves each level's queue priority, including replenished iceberg
        orders. It does not reconstruct priority by sorting original timestamps.
        
        Args:
            symbol: The registered book symbol to inspect.
            side: "buy" or "sell".
            min_price: The inclusive lower price bound in integer atoms.
            max_price: The inclusive upper price bound in integer atoms.
        
        Returns:
            Tuples of (order_id, price, visible_quantity, created_at_ns), in the store's
            level and queue order. IDs are integers; prices and quantities use atoms.
        
        Raises:
            RuntimeError: The adapter has no started session or the book is unavailable.
            ValueError: side is neither "buy" nor "sell".
        """
    def return_to_main(self, /) -> None:
        """
        Discard the simulation branch and select the continuing main timeline.
        
        The main book has continued receiving source messages during the simulation.
        Calling this method does not restart the source or replay its earlier messages.
        
        Raises:
            RuntimeError: The adapter has no started session.
        """
    def select(self, /, symbol: str) -> None:
        """
        Select the active book and request its live subscription if needed.
        
        Args:
            symbol: A registered ticker inside the adapter's book scope. Previously
                visited live instruments retain their subscriptions.
        
        Raises:
            RuntimeError: The adapter has no started session, or the ticker is
                unavailable or outside scope.
        """
    def set_bar_aggregation(self, /, kind: str, size: int) -> None:
        """
        Choose how reported executions accumulate into OHLC bars.
        
        Changing aggregation resets the bar accumulator, including the simulation's
        accumulator when an alternate timeline exists.
        
        Args:
            kind: "volume" for quantity, "ticks" for execution count, "time" for
                source-time intervals, or "notional" for execution price times quantity.
            size: The positive bar threshold. Units are quantity atoms for volume,
                executions for ticks, nanoseconds for time, and price-atoms times
                quantity-atoms for notional.
        
        Raises:
            RuntimeError: The adapter has no started session.
            ValueError: kind is unknown or size is zero.
        """
    def simulate(self, /, side: str, quantity: int, *, price: int |None = None) -> None:
        """
        Preview a market order or start a simulated L3 resting limit order.
        
        Market previews report immediate fills without creating an alternate timeline.
        L3 limit simulations retain a branch for any resting remainder while source
        messages continue. The main timeline remains available through return_to_main().
        
        Args:
            side: The incoming order side, "buy" or "sell".
            quantity: The requested positive quantity in integer quantity atoms.
            price: An optional limit price in integer price atoms. None creates a market
                preview. A limit price requires an L3 source with a synchronized book.
        
        Raises:
            RuntimeError: The adapter has no started session, the book is not
                synchronized, or its order and simulation rules reject the request.
            ValueError: side is neither "buy" nor "sell".
        """
    def simulation_report(self, /) -> Any:
        """
        Read simulated fills and the remaining quantity on the selected timeline.
        
        Returns:
            None before a simulation, otherwise a dictionary with simulated, order_id,
            symbol, requested, filled, remaining, average_price, complete,
            alternate_timeline, ignored, stopped, and executions. Prices use price atoms.
            Each execution contains simulated, timestamp_ns, price, quantity, and sequence.
            A stopped alternate timeline remains selected until return_to_main().
        
        Raises:
            RuntimeError: The adapter has no started session.
        """
    def status(self, /) -> Any:
        """
        Read session progress and synchronization for the selected book.
        
        Returns:
            A dictionary containing symbol, messages, bytes, clock_ns, complete,
            synchronized, checksum_checks, checksum_failures, and books. clock_ns uses
            the source timeline; complete describes source completion.
        
        Raises:
            RuntimeError: The adapter has no started session.
        """
    def tickers(self, /) -> list[str]:
        """
        List the instrument symbols discovered so far.
        
        Returns:
            Normalized tickers. A live source may still be discovering its directory.
        
        Raises:
            RuntimeError: The session is closed.
        """
    def wait(self, /) -> None:
        """
        Wait for source completion and report any decoder or checksum failure.
        
        Finite recordings retain their books for inspection after this method returns.
        A live WebSocket normally continues until close() is called from another thread.
        
        Raises:
            RuntimeError: The session is closed or the source worker failed.
        """

@final
class Protocol:
    """
    Describe message decoding and the lifecycle of a custom adapter.
    
    Protocol is the complete declaration passed to CustomAdapter. It combines a
    wire format with optional discovery requests and connection actions. Its
    constructor validates the declaration; CustomAdapter prepares it for execution.
    No connection is opened merely by constructing a Protocol.
    
    Args:
        format: Binary record layouts or Json message rules describing incoming data.
        connect: Actions run each time a source connection opens, including reconnects.
            Use Send for a handshake and Subscribe if subscription can start immediately.
            Defaults to no actions. Connection lookup tables and sequence state are
            cleared before these actions run.
        subscriptions: Actions run once for each requested, available instrument on a
            ready connection. Variable("symbol") is that instrument. These actions
            usually contain Send requests. Subscribe marks the connection ready and
            sends pending subscriptions; call it after any required handshake reply.
            Defaults to no actions.
        bootstrap: Bootstrap requests processed in declaration order before a live
            connection opens. These HTTP JSON responses commonly discover symbols and
            precision. They are separate from book snapshots carried by the message
            stream. Recorded sources can supply responses under each request's name.
            Defaults to no requests.
        keepalive: Actions run on each connected WebSocket at the transport's periodic
            heartbeat, currently every fifteen seconds. Use Send if the source needs
            an application-level ping. Defaults to no actions.
        simulation_note: Optional text describing source-specific simulation limits,
            exposed with the adapter's simulation information. Defaults to None.
        reconcile_window_ns: Maximum source-time interval for associating separate
            public trades with absolute L3 order updates in an alternate simulation.
            Defaults to 250,000,000 nanoseconds (250 milliseconds). It does not delay
            the main book or apply to feeds with explicit order execution messages.
        reconcile_capacity: Maximum pending reconciliation entries retained for a
            simulation. Defaults to 4096 and must be positive. Exceeding the bound
            interrupts the simulation rather than retaining unbounded pending state.
        symbols_per_connection: Maximum subscribed instruments assigned to one
            connection. Zero, the default, puts all requested symbols on one connection.
            A positive value opens additional connections as symbols are requested;
            it does not limit the adapter's ticker directory or book scope.
    
    Raises:
        ValueError: An expression, action, checksum configuration, framing layout, or
            reconciliation capacity is invalid.
        TypeError: An argument is not the required declaration or sequence of declarations.
    
    Examples:
    ```python
    from lobo.replay.adapters import Protocol
    from lobo.replay.adapters import expressions as le
    from lobo.replay.adapters import models as lm
    
    protocol = Protocol(
        lm.Json(lm.Message(le.Field("type").eq("level"),
            lm.Book(le.Field("symbol"), lm.Level(side=le.Field("side"),
                price=le.Field("price").decimal(2), quantity=le.Field("size"))))),
        connect=(lm.Subscribe(),),
        subscriptions=(lm.Send({"method": "subscribe", "symbol": le.Variable("symbol")}),),
    )
    ```
    """
    def __new__(cls, /, format: Format, *, connect: Iterable[Action] |None = None, subscriptions: Iterable[Action] |None = None, bootstrap: Iterable[Bootstrap] |None = None, keepalive: Iterable[Action] |None = None, simulation_note: str |None = None, reconcile_window_ns: int = 250000000, reconcile_capacity: int = 4096, symbols_per_connection: int = 0) -> Protocol: ...
    @property
    def data(self, /) -> Any:
        """
        Return the complete protocol as a detached dictionary.
        
        Returns:
            A serializable definition for inspection or storage. CustomAdapter
            accepts Protocol directly and does not require this conversion.
        """
