"""
AUTOGENERATED FROM RUST. DO NOT EDIT.

Read incoming fields, transform values, and describe control flow.
Combine these expressions with the book operations in models when defining
a Protocol.
"""

from collections.abc import Iterable
from typing import Any, final

from .models import Action

@final
class CheckSequence(Action):
    """
    Check that source sequence numbers increase by exactly one.
    
    Args:
        value: An expression yielding the message's unsigned sequence number.
        key: An optional expression selecting a sequence stream within the
            connection, for example a channel ID. None uses the connection's
            default sequence stream.
        reset: If true, establish a new starting sequence without checking the
            previous number. Use it for a snapshot or other reset message.
    
    A gap fails the message and triggers the source's recovery behavior. State
    is isolated per connection and cleared on reconnect. The public custom
    module also exports this constructor as CheckSequence.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
    
        sequence = le.CheckSequence(le.Field("sequence"), key=le.Field("channel"))
        ```
    """
    def __new__(cls, /, value: Any, *, key: Any |None = None, reset: bool = False) -> CheckSequence:
        """
        Check that source sequence numbers increase by exactly one.
        
        Args:
            value: An expression yielding the message's unsigned sequence number.
            key: An optional expression selecting a sequence stream within the
                connection, for example a channel ID. None uses the connection's
                default sequence stream.
            reset: If true, establish a new starting sequence without checking the
                previous number. Use it for a snapshot or other reset message.
        
        A gap fails the message and triggers the source's recovery behavior. State
        is isolated per connection and cleared on reconnect. The public custom
        module also exports this constructor as CheckSequence.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            sequence = le.CheckSequence(le.Field("sequence"), key=le.Field("channel"))
            ```
        """

@final
class Choose(Expression):
    """
    Select between two values using a condition evaluated for each message.
    
    Args:
        condition: A boolean expression or constant. Only true selects yes.
        yes: The expression or constant to use when the condition is true.
        no: The expression or constant to use otherwise. The unselected branch
            is not evaluated, so it may refer to fields absent from that message.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
    
        side = le.Choose(le.Field("amount").gt(0), "buy", "sell")
        ```
    """
    def __new__(cls, /, condition: Any, yes: Any, no: Any) -> Choose:
        """
        Select between two values using a condition evaluated for each message.
        
        Args:
            condition: A boolean expression or constant. Only true selects yes.
            yes: The expression or constant to use when the condition is true.
            no: The expression or constant to use otherwise. The unselected branch
                is not evaluated, so it may refer to fields absent from that message.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            side = le.Choose(le.Field("amount").gt(0), "buy", "sell")
            ```
        """

@final
class Concat(Expression):
    """
    Join text and expression results to form a text value.
    
    Args:
        *values: Expressions or constants, concatenated in order. Text is used
            directly; other values use their JSON representation.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
    
        wire_symbol = le.Concat("t", le.Variable("symbol"))
        ```
    """
    def __new__(cls, /, *values) -> Concat:
        """
        Join text and expression results to form a text value.
        
        Args:
            *values: Expressions or constants, concatenated in order. Text is used
                directly; other values use their JSON representation.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            wire_symbol = le.Concat("t", le.Variable("symbol"))
            ```
        """

class Expression:
    """
    An immutable calculation used by a message condition or action argument.
    
    Use Field to read a source value, Variable to read protocol state, and methods
    such as decimal, eq, or map to transform those values. These objects describe
    calculations; they do not evaluate incoming messages in Python. Python boolean
    conversion is rejected: use &, |, and .eq() to build conditions.
    
    Args:
        data: For the low-level Expression constructor, an exported expression
            dictionary with an op name and its operands. Prefer Field, Variable,
            Choose, Concat, or expression(value) when writing an adapter.
    
    Examples:
    ```python
    from lobo.replay.adapters import expressions as le
    
    price = le.Field("price").decimal(2)
    is_update = le.Field("type").eq("update") & le.Field("price").exists()
    ```
    """
    def __and__(self, /, other: object) -> Expression:
        """
        Require both conditions, evaluating the right condition only if needed.
        
        Args:
            other: The second boolean expression or boolean constant.
        
        Returns:
            A boolean expression. Use parentheses around comparisons combined by &.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            valid = le.Field("price").exists() & le.Field("price").gt(0)
            ```
        """
    def __bool__(self, /) -> bool:
        """
        Reject immediate Python truth testing of an unevaluated expression.
        
        Raises:
            TypeError: Expressions describe future messages. Use &, |, When, or
                Choose instead of Python and, or, if, or bool(expression).
        """
    def __new__(cls, /, data: dict) -> Expression:
        """
        Read an expression from its exported dictionary representation.
        
        Prefer Field, Variable, Choose, and the expression methods when writing an
        adapter. This constructor is for restoring a previously exported expression.
        
        Args:
            data: The dictionary returned by specification(expression), containing
                an op name and that operator's operands or field path.
        
        Raises:
            ValueError: The operator, operands, or dictionary structure is invalid.
        """
    def __or__(self, /, other: object) -> Expression:
        """
        Accept either condition, evaluating the right condition only if needed.
        
        Args:
            other: The second boolean expression or boolean constant.
        
        Returns:
            A boolean expression to use in Message, When, or Choose.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            is_order = le.Field("event").eq("add") | le.Field("event").eq("update")
            ```
        """
    def absolute(self, /) -> Expression:
        """
        Remove the sign of a numeric value without converting it to a float.
        
        Returns:
            A nonnegative numeric expression. Apply decimal(places) afterwards
            when the source uses fractional quantities.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            quantity = le.Field("signed_amount").absolute().decimal(8)
            ```
        """
    @property
    def data(self, /) -> Any:
        """
        Return a detached dictionary describing this expression.
        
        Returns:
            A serializable dictionary. Editing it does not mutate this expression.
        """
    def decimal(self, /, places: Any) -> Expression:
        """
        Convert a decimal value to unsigned integer atoms at a chosen precision.
        
        Args:
            places: A decimal count or expression yielding that count, normally
                the instrument's price_decimals or quantity_decimals. For places=2,
                a source value of "12.34" becomes 1234 book atoms.
        
        Returns:
            An integer expression. Decimal conversion preserves the original wire
            width for level checksums. Nonzero digits beyond the declared precision
            produce a source error.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            price = le.Field("price").decimal(le.Variable("price_decimals"))
            ```
        """
    def eq(self, /, other: Any) -> Expression:
        """
        Compare this expression with another value for equality.
        
        Args:
            other: An expression or constant to compare with this expression.
        
        Returns:
            A boolean expression. Numeric comparisons preserve integer and decimal
            precision; this method does not evaluate a Python boolean immediately.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            is_add = le.Field("event").eq("add")
            ```
        """
    def exists(self, /) -> Expression:
        """
        Test whether the selected value exists and is not JSON null.
        
        Returns:
            A boolean expression. Zero, false, and an empty string count as present.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            has_execution_price = le.Field("execution_price").exists()
            ```
        """
    def get(self, /, *path: "str | int") -> Expression:
        """
        Select a nested field from the value produced by this expression.
        
        Args:
            *path: String object keys or integer array indices. Negative indices
                count backwards from the end of an array.
        
        Returns:
            An expression yielding the selected value, or None for a missing path.
        
        Raises:
            TypeError: A path component is neither a string nor an integer.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            last_price = le.Variable("rows").get(-1, "price")
            ```
        """
    def gt(self, /, other: Any) -> Expression:
        """
        Test whether this numeric expression is greater than another number.
        
        Args:
            other: A numeric constant or expression producing a number.
        
        Returns:
            A boolean expression using exact numeric comparison. Invalid numeric
            input is reported when the corresponding message is processed.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            is_bid = le.Field("signed_amount").gt(0)
            ```
        """
    def is_array(self, /) -> Expression:
        """
        Test whether the selected value is an array.
        
        Returns:
            A boolean expression, useful for distinguishing snapshot arrays from
            control messages before entering ForEach.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            contains_rows = le.Field("orders").is_array()
            ```
        """
    def length(self, /) -> Expression:
        """
        Count the selected array's items, object's keys, or text's bytes.
        
        Returns:
            An integer expression. Missing values and other scalar types produce 0.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            nonempty = le.Field("orders").length().gt(0)
            ```
        """
    def lookup(self, /, table: str) -> Expression:
        """
        Retrieve a value previously stored by Remember for this connection.
        
        Args:
            table: The name of the table used by Remember. This expression supplies
                the key, for example a channel ID assigned by the server.
        
        Returns:
            The remembered value, or None when the connection has no matching key.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            symbol = le.Field("channel").lookup("channels").get("symbol")
            ```
        """
    def lt(self, /, other: Any) -> Expression:
        """
        Test whether this numeric expression is less than another number.
        
        Args:
            other: A numeric constant or expression producing a number.
        
        Returns:
            A boolean expression using exact numeric comparison.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            is_ask = le.Field("signed_amount").lt(0)
            ```
        """
    def map(self, /, values: "dict[Any, Any]", *, default: Any |None = None) -> Expression:
        """
        Translate a source value through a fixed lookup dictionary.
        
        Args:
            values: Source values mapped to output values. Keys are converted to
                text, so integer wire codes can be used as dictionary keys.
            default: The expression or constant returned if no key matches.
                Defaults to None. A matching key mapped to None still matches.
        
        Returns:
            An expression yielding the mapped value, or the fallback for an unknown key.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            side = le.Field("side").map({"B": "buy", "S": "sell"})
            ```
        """
    def ne(self, /, other: Any) -> Expression:
        """
        Test whether this expression differs from another value.
        
        Args:
            other: An expression or constant to compare with this expression.
        
        Returns:
            A boolean expression that is true when the values are unequal.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            has_quantity = le.Field("quantity").ne(0)
            ```
        """
    def strip_prefix(self, /, prefix: str) -> Expression:
        """
        Remove a leading prefix from text when the prefix matches.
        
        Args:
            prefix: The literal prefix to remove. Other text remains unchanged.
        
        Returns:
            A text expression with at most one matching prefix removed.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            symbol = le.Field("symbol").strip_prefix("t")
            ```
        """
    def timestamp(self, /, unit: str = "ns") -> Expression:
        """
        Convert a source timestamp to nonnegative nanoseconds.
        
        Args:
            unit: "ns", "us", "ms", or "s" for unsigned source-time counts; use
                "rfc3339" for text such as "2026-01-01T09:30:00Z". Defaults to "ns".
        
        Returns:
            An integer expression suitable for an action's timestamp argument.
            Invalid values and overflow are errors when their messages are processed.
        
        Raises:
            ValueError: The declared unit is unsupported.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            execution_time = le.Field("time_ms").timestamp("ms")
            ```
        """
    def trim(self, /) -> Expression:
        """
        Remove whitespace from both ends of a text value.
        
        Returns:
            A text expression. Non-text input produces an error during processing.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            symbol = le.Field("symbol").trim()
            ```
        """

@final
class Field(Expression):
    """
    Select a value from the message or the current ForEach item.
    
    Args:
        *path: String object keys or integer array indices, in traversal order.
            Negative indices count from the end. An empty path selects the
            entire current item. Missing paths produce None.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
    
        price = le.Field("data", 0, "price")
        row = le.Field()  # Inside ForEach, this selects the current row.
        ```
    """
    def __new__(cls, /, *path: "str | int") -> Field:
        """
        Select a value from the message or the current ForEach item.
        
        Args:
            *path: String object keys or integer array indices, in traversal order.
                Negative indices count from the end. An empty path selects the
                entire current item. Missing paths produce None.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            price = le.Field("data", 0, "price")
            row = le.Field()  # Inside ForEach, this selects the current row.
            ```
        """

@final
class ForEach(Action):
    """
    Run a sequence of actions for every element of an array.
    
    Args:
        items: An expression yielding the array to traverse. Field reads from
            each item inside the loop; Root continues to read the full message.
        *actions: Actions to run in order for each item.
        order_by: An optional expression evaluated per item for an ascending
            sort before applying actions. Omit it when source order is already FIFO.
        unique_by: An optional per-item key for removing duplicate entries.
            Use it only when repeated snapshot rows represent the same item.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        bids = le.ForEach(le.Field("bids"),
            lm.Level(side="buy", price=le.Field(0).decimal(2), quantity=le.Field(1).decimal(8)))
        ```
    """
    def __new__(cls, /, items: Any, *actions: "Action", order_by: Any |None = None, unique_by: Any |None = None) -> ForEach:
        """
        Run a sequence of actions for every element of an array.
        
        Args:
            items: An expression yielding the array to traverse. Field reads from
                each item inside the loop; Root continues to read the full message.
            *actions: Actions to run in order for each item.
            order_by: An optional expression evaluated per item for an ascending
                sort before applying actions. Omit it when source order is already FIFO.
            unique_by: An optional per-item key for removing duplicate entries.
                Use it only when repeated snapshot rows represent the same item.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            bids = le.ForEach(le.Field("bids"),
                lm.Level(side="buy", price=le.Field(0).decimal(2), quantity=le.Field(1).decimal(8)))
            ```
        """

@final
class Let(Action):
    """
    Assign an expression result to a named protocol variable.
    
    Args:
        name: The name used later by Variable(name). Assignment replaces the
            previous value. Variables belong to the adapter; use Remember for
            a lookup table isolated to each connection and reset on reconnect.
        value: The expression or constant to store when this action executes.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
    
        save_symbol = le.Let("wire_symbol", le.Field("symbol"))
        ```
    """
    def __new__(cls, /, name: str, value: Any) -> Let:
        """
        Assign an expression result to a named protocol variable.
        
        Args:
            name: The name used later by Variable(name). Assignment replaces the
                previous value. Variables belong to the adapter; use Remember for
                a lookup table isolated to each connection and reset on reconnect.
            value: The expression or constant to store when this action executes.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            save_symbol = le.Let("wire_symbol", le.Field("symbol"))
            ```
        """

@final
class Remember(Action):
    """
    Store a value under a key in the current connection's named table.
    
    Args:
        table: The table name used later by expression.lookup(table).
        key: An expression yielding the lookup key, often a channel ID.
        value: The expression or constant to remember. Remembered values survive
            later packets; the connection's tables are cleared on reconnect.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
    
        remember = le.Remember("channels", le.Field("channel_id"), {"symbol": le.Field("symbol")})
        ```
    """
    def __new__(cls, /, table: str, key: Any, value: Any) -> Remember:
        """
        Store a value under a key in the current connection's named table.
        
        Args:
            table: The table name used later by expression.lookup(table).
            key: An expression yielding the lookup key, often a channel ID.
            value: The expression or constant to remember. Remembered values survive
                later packets; the connection's tables are cleared on reconnect.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            remember = le.Remember("channels", le.Field("channel_id"), {"symbol": le.Field("symbol")})
            ```
        """

@final
class Root(Expression):
    """
    Select a value from the complete incoming message, even inside a loop.
    
    Args:
        *path: String object keys or integer array indices. The traversal always
            starts at the root message. An empty path selects the whole message.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
    
        timestamp = le.Root("timestamp").timestamp("ms")
        ```
    """
    def __new__(cls, /, *path: "str | int") -> Root:
        """
        Select a value from the complete incoming message, even inside a loop.
        
        Args:
            *path: String object keys or integer array indices. The traversal always
                starts at the root message. An empty path selects the whole message.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            timestamp = le.Root("timestamp").timestamp("ms")
            ```
        """

@final
class Variable(Expression):
    """
    Refer to a named value supplied by the session or assigned by Let.
    
    Built-in names are symbol, connection, clock, price_decimals,
    quantity_decimals, and key. Book and subscription scopes refresh instrument
    metadata. clock is nanoseconds; binary records supply their source clock,
    while JSON packets initially use the session's wall clock unless overridden.
    Remember stores connection-specific lookup data; use it instead of Let
    for channel maps that must be cleared and rebuilt on reconnect.
    
    Args:
        name: The variable name. An unassigned variable yields None.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
    
        symbol = le.Variable("symbol")
        price = le.Field("price").decimal(le.Variable("price_decimals"))
        ```
    """
    def __new__(cls, /, name: str) -> Variable:
        """
        Refer to a named value supplied by the session or assigned by Let.
        
        Built-in names are symbol, connection, clock, price_decimals,
        quantity_decimals, and key. Book and subscription scopes refresh instrument
        metadata. clock is nanoseconds; binary records supply their source clock,
        while JSON packets initially use the session's wall clock unless overridden.
        Remember stores connection-specific lookup data; use it instead of Let
        for channel maps that must be cleared and rebuilt on reconnect.
        
        Args:
            name: The variable name. An unassigned variable yields None.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
        
            symbol = le.Variable("symbol")
            price = le.Field("price").decimal(le.Variable("price_decimals"))
            ```
        """

@final
class When(Action):
    """
    Choose which group of actions to run for the current message or loop item.
    
    Args:
        condition: An expression or constant; true selects actions.
        *actions: Actions to run, in order, when the condition is true.
        otherwise: Actions to run when the condition is not true. Defaults to
            an empty group. Only the selected branch executes.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        update = le.When(le.Field("deleted").eq(True), lm.Remove(id=le.Field("id")),
                      otherwise=(lm.Modify(id=le.Field("id"), quantity=le.Field("size")),))
        ```
    """
    def __new__(cls, /, condition: Any, *actions: "Action", otherwise: Iterable[Action] |None = None) -> When:
        """
        Choose which group of actions to run for the current message or loop item.
        
        Args:
            condition: An expression or constant; true selects actions.
            *actions: Actions to run, in order, when the condition is true.
            otherwise: Actions to run when the condition is not true. Defaults to
                an empty group. Only the selected branch executes.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            update = le.When(le.Field("deleted").eq(True), lm.Remove(id=le.Field("id")),
                          otherwise=(lm.Modify(id=le.Field("id"), quantity=le.Field("size")),))
            ```
        """

def expression(value: Any) -> Expression:
    """
    Turn a constant, container, or existing expression into an expression.
    
    Dictionaries and lists can contain expressions. For example, a Send action
    can combine fixed JSON keys with Variable("symbol") in a subscription request.
    Entirely constant containers remain constants in the compiled definition.
    
    Args:
        value: An expression, None, a boolean, integer, finite float, string,
            ASCII bytes, or a list, tuple, or dictionary containing these values.
            Dictionary keys are converted to strings.
    
    Returns:
        An immutable Expression describing the value to compute for a message.
    
    Raises:
        TypeError: The value is not supported by the declaration language.
        ValueError: A float is not finite or a byte string is not ASCII.
    
    Examples:
        ```python
        from lobo.replay.adapters.expressions import expression, Variable
        request = expression({"method": "subscribe", "symbol": Variable("symbol")})
        ```
    """
