"""
AUTOGENERATED FROM RUST. DO NOT EDIT.

Read NASDAQ ITCH replay files with the shipped Rust adapter.
"""

from typing import final

from _typeshed import Incomplete

@final
class ItchSource:
    """
    Select an instrument from a NASDAQ ITCH replay file.
    
    Pass this source to ReplayContext to reconstruct its book. The source can be
    reused for subsequent replays. Use all_available() to select every instrument
    in the file's directory with one shared input scan.
    
    Args:
        path: Filename containing length-prefixed ITCH messages, optionally gzip
            compressed. Intraday timestamps use the session date in the filename.
        ticker: Instrument symbol to reconstruct, such as "AAPL".
    
    Raises:
        FileNotFoundError: The input file does not exist.
        RuntimeError: The file is unreadable or ticker is absent from its directory.
    
    Examples:
        ```python
        from lobo.replay import ReplayContext
        from lobo.replay.adapters import itch
    
        source = itch.ItchSource("01302020.NASDAQ_ITCH50.gz", "AAPL")
        with ReplayContext(source=source, cutoff_time=None) as books:
            book = books["aapl"]
        ```
    """
    def __fspath__(self, /) -> str: ...
    def __new__(cls, /, path: str, ticker: str) -> ItchSource: ...
    def __repr__(self, /) -> str: ...
    def adapt(self, /) -> ReplayMessages:
        """
        Return only messages that can update a reconstructed order book.
        """
    @staticmethod
    def all_available(path: str) -> list[ItchSource]:
        """
        Select every instrument present in the file's directory.
        
        Args:
            path: The ITCH replay filename, optionally gzip compressed.
        
        Returns:
            Sources sharing the same input scan, one per available ticker.
        
        Raises:
            FileNotFoundError: The input file does not exist.
            RuntimeError: Reading or parsing the directory fails.
        """
    @property
    def path(self, /) -> str: ...
    @staticmethod
    def read_tickers(path: str) -> Incomplete:
        """
        Read the file's ticker directory into a Polars DataFrame.
        """
    @property
    def ticker(self, /) -> str: ...
    def to_lazy_frame(self, /) -> Incomplete:
        """
        Return a Polars LazyFrame containing every source message.
        """

@final
class ReplayMessages:
    """
    A replay-compatible native Polars lazy plan.
    """
    def __repr__(self, /) -> str: ...
    @classmethod
    def _from_lazy_frame(cls, /, lazy_frame: Incomplete) -> ReplayMessages: ...
    def to_lazy_frame(self, /) -> Incomplete: ...
