"""
AUTOGENERATED FROM RUST. DO NOT EDIT.

Configure and start the built-in Kraken feed.
"""

from typing import final

from . import AdapterSession
from .models import Source

@final
class KrakenSource:
    """
    Configure the Kraken Spot WebSocket v2 aggregate book feed.
    
    Construction prepares configuration without opening a connection. Call start()
    to receive messages and inspect books through the returned AdapterSession.
    Previously selected pairs retain their live subscriptions. All messages use the
    existing Kraken decoder, snapshot handling, checksum policy, and execution paths.
    
    Args:
        symbol: Initially selected pair, such as "BTC/USD". Defaults to "BTC/USD".
        depth: Number of levels per side: 10, 25, 100, 500, or 1000. Defaults to 10.
        source: Optional models.Source describing a WebSocket endpoint or recorded
            packets/JSON lines. None connects to the exchange's public WebSocket.
            Recorded input must include the exchange's directory and snapshot messages.
    
    Raises:
        ValueError: The symbol or source configuration is invalid.
    
    Examples:
        ```python
        from lobo.replay.adapters import kraken
    
        with kraken.KrakenSource("BTC/USD").start() as session:
            available = session.tickers()
        ```
    """
    def __new__(cls, /, symbol: str = "BTC/USD", depth: int = 10, *, source: Source |None = None) -> KrakenSource: ...
    @property
    def depth(self, /) -> int:
        """
        The number of subscribed aggregate price levels per side.
        """
    def start(self, /) -> AdapterSession:
        """
        Start receiving this source using the Kraken adapter.
        
        Returns:
            An AdapterSession with ticker selection, book levels, execution bars,
            and the simulations supported by this source's book level. Use it as a
            context manager to stop its worker automatically.
        
        Raises:
            RuntimeError: The adapter worker cannot start. Source and checksum errors
                encountered after startup are reported by the session's wait() method.
        """
    @property
    def symbol(self, /) -> str:
        """
        The normalized pair selected when a session starts.
        """
