"""
AUTOGENERATED FROM RUST. DO NOT EDIT.

Describe wire formats, book changes, instruments, and source capabilities.
Use these declarations inside Protocol and supply data-reading expressions
from lobo.replay.adapters.expressions for their incoming values.
"""

from collections.abc import Iterable, Mapping, Sequence
from os import PathLike
from typing import Any, Final, final

class Action:
    """
    An immutable declaration of a book change or source lifecycle operation.
    
    Use the named Python constructors, such as Add, Book, and Send, to describe
    what happens when a message matches. Creating an action does not execute it.
    
    Args:
        kind: For the low-level Action constructor, the serialized operation name.
        **fields: That operation's arguments, using exported expression dictionaries
            or expression objects. Prefer the named constructors for new definitions.
    
    Examples:
    ```python
    from lobo.replay.adapters import expressions as le
    from lobo.replay.adapters import models as lm
    
    action = lm.Add(id=le.Field("id"), side="buy", price=100, quantity=20)
    ```
    """
    def __new__(cls, /, kind: str, **fields) -> Action:
        """
        Restore an action using an operation name and exported argument values.
        
        Prefer the named constructors such as Add, Execute, and Book for a new
        adapter. This low-level constructor accepts the same fields as an exported
        operation; expression arguments must be declaration objects or exported
        expression dictionaries, rather than unwrapped numeric values.
        
        Args:
            kind: The operation name, such as "add" or "let".
            **fields: The fields of that operation in its exported representation.
        
        Raises:
            ValueError: The operation name or its field structure is invalid.
        """
    @property
    def data(self, /) -> Any:
        """
        Return a detached dictionary describing this operation and its arguments.
        
        Returns:
            A serializable dictionary. Editing it does not mutate this action.
        """

@final
class AdapterInfo:
    """
    Describe a source's identity and the capabilities its consumers may use.
    
    The adapter exposes equivalent information through CustomAdapter.info. Mode and
    level determine which replay, queue, and simulation controls a consumer can offer.
    This metadata does not define how messages are decoded; Protocol does that.
    
    Args:
        id: A stable identifier for the source, such as "my_feed".
        name: A human-readable source name shown to consumers.
        mode: FeedMode.Live for ongoing updates or FeedMode.Replay for a recorded session.
        level: BookLevel.L1 for best quotes, BookLevel.L2 for aggregate price levels,
            or BookLevel.L3 for individual resting orders.
        default_symbol: The initially selected instrument symbol.
        endpoint: The source's WebSocket URL, if it has one. Defaults to None.
        timezone: An IANA timezone name describing source timestamps, such as
            "America/New_York". Defaults to "UTC".
        supports_trades: Whether the protocol reports actual executions through Execute,
            Trade, or the order API. Defaults to True; quantity changes alone do not
            imply executions and should not advertise trade reporting.
    
    Raises:
        TypeError: mode or level is not the corresponding enum.
        ValueError: default_symbol is invalid.
    
    Examples:
        ```python
        from lobo.replay.adapters import models as lm
    
        info = lm.AdapterInfo("my_feed", "My feed", mode=lm.FeedMode.Live, level=lm.BookLevel.L2,
                           default_symbol="BTC/USD", supports_trades=True)
        ```
    """
    def __new__(cls, /, id: str, name: str, *, mode: FeedMode, level: BookLevel, default_symbol: str, endpoint: str |None = None, timezone: str = "UTC", supports_trades: bool = True) -> AdapterInfo: ...
    @property
    def default_symbol(self, /) -> str:
        """
        The instrument selected when the adapter starts.
        """
    @property
    def endpoint(self, /) -> str |None:
        """
        The source WebSocket URL, or None if no endpoint is declared.
        """
    @property
    def id(self, /) -> str:
        """
        The stable source identifier.
        """
    @property
    def level(self, /) -> BookLevel:
        """
        The source's BookLevel.L1, BookLevel.L2, or BookLevel.L3 detail.
        """
    @property
    def mode(self, /) -> FeedMode:
        """
        FeedMode.Live for ongoing updates or FeedMode.Replay for recorded input.
        """
    @property
    def name(self, /) -> str:
        """
        The display name of the source.
        """
    @property
    def supports_trades(self, /) -> bool:
        """
        Whether actual executions are reported by the declared protocol.
        """
    @property
    def timezone(self, /) -> str:
        """
        The source timezone name used to interpret recorded timestamps.
        """

@final
class Add(Action):
    """
    Insert a visible resting order without matching it against the other side.
    
    Use this for feeds that publish individual order additions. Register the
    instrument first and select it with Book or the current symbol variable.
    
    Args:
        id: An expression or constant yielding the order's unsigned integer ID
            or UUID text. Later changes must use the same ID.
        side: "buy" or "sell", or an expression producing that side.
        price: The positive limit price in integer price atoms.
        quantity: The order's visible quantity in integer quantity atoms.
        timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        add = lm.Add(id=le.Field("id"), side="buy", price=le.Field("price"), quantity=le.Field("size"))
        ```
    """
    def __new__(cls, /, *, id: Any, side: Any, price: Any, quantity: Any, timestamp: Any |None = None) -> Add:
        """
        Insert a visible resting order without matching it against the other side.
        
        Use this for feeds that publish individual order additions. Register the
        instrument first and select it with Book or the current symbol variable.
        
        Args:
            id: An expression or constant yielding the order's unsigned integer ID
                or UUID text. Later changes must use the same ID.
            side: "buy" or "sell", or an expression producing that side.
            price: The positive limit price in integer price atoms.
            quantity: The order's visible quantity in integer quantity atoms.
            timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            add = lm.Add(id=le.Field("id"), side="buy", price=le.Field("price"), quantity=le.Field("size"))
            ```
        """

@final
class Binary(Format):
    """
    Describe the framing and layouts of a binary message stream.
    
    Each record starts with a length prefix followed by its payload. The length
    counts payload bytes only. All other offsets are relative to the payload.
    Records whose tags are absent from records are skipped using their length.
    
    Args:
        length: A UInt at offset zero describing the length prefix.
        tag: A UInt identifying which Record layout to use.
        key: A UInt containing the routing key registered with Register.key.
        timestamp: A UInt containing the source timestamp in nanoseconds.
        records: A dictionary from integer tags or single-character strings to
            Record objects. A character tag is converted to its Unicode code point.
        max_record_size: The largest accepted payload size, in bytes. Defaults to
            512 and must be between 1 and 65535. This bounds framing buffers.
    
    Raises:
        TypeError: A field or record has the wrong declaration type.
        ValueError: A string tag contains more than one character. Protocol checks
            the completed layout's field ranges and record sizes during setup.
    
    Examples:
        ```python
        from lobo.replay.adapters import Protocol
        from lobo.replay.adapters import models as lm
    
        wire = lm.Binary(length=lm.UInt(0, 2), tag=lm.UInt(0, 1), key=lm.UInt(1, 2),
                      timestamp=lm.UInt(3, 8),
                      records={"H": lm.Record(size=11, fields={}, actions=())})
        protocol = Protocol(wire)
        ```
    """
    def __new__(cls, /, *, length: BinaryField, tag: BinaryField, key: BinaryField, timestamp: BinaryField, records: "dict[int | str, Record]", max_record_size: int = 512) -> Binary: ...

class BinaryField:
    """
    A byte range within a binary record or its length prefix.
    
    Use UInt(offset, size, byteorder="big") to read an unsigned integer, or
    Text(offset, size) to read trimmed UTF-8 text. These constructors provide the
    field kind; this shared base is not constructed directly from Python.
    
    Examples:
    ```python
    from lobo.replay.adapters import models as lm
    
    order_id = lm.UInt(offset=0, size=8)
    symbol = lm.Text(offset=8, size=8)
    ```
    """
    @property
    def data(self, /) -> Any:
        """
        Return this field's kind, offset, byte size, and byte order.
        
        Returns:
            A detached dictionary suitable for saving with the record definition.
        """

@final
class Book(Action):
    """
    Apply related actions to one instrument as a snapshot or an incremental update.
    
    Selects the book and its precision variables, runs the nested actions, then
    checks the completed checksum and synchronization state. A failed message
    invalidates the snapshot; this operation does not promise rollback of each
    individual mutation already applied before the failure.
    
    Args:
        symbol: An expression or constant naming a registered instrument.
        *actions: Operations applied in order to this instrument. In a snapshot,
            provide every retained order or level in the appropriate source order.
        snapshot: A boolean expression or constant. True clears the previous
            book before applying actions; false applies an incremental update.
        timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
        depth: The retained L2 depth per side after processing. Zero means no
            depth trimming. This is separate from Checksum.depth.
        checksum: An optional Checksum declaration checked after all actions.
        ready: Whether successful processing may mark the book synchronized.
            Use false while assembling an incomplete snapshot; the default is true.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        snapshot = lm.Book("XYZ", le.ForEach(le.Field("orders"),
            lm.Add(id=le.Field("id"), side=le.Field("side"), price=le.Field("price"), quantity=le.Field("size"))),
            snapshot=True, timestamp=le.Field("time").timestamp("ms"))
        ```
    """
    def __new__(cls, /, symbol: Any, *actions: "Action", snapshot: Any |None = None, timestamp: Any |None = None, depth: int = 0, checksum: Checksum |None = None, ready: bool = True) -> Book:
        """
        Apply related actions to one instrument as a snapshot or an incremental update.
        
        Selects the book and its precision variables, runs the nested actions, then
        checks the completed checksum and synchronization state. A failed message
        invalidates the snapshot; this operation does not promise rollback of each
        individual mutation already applied before the failure.
        
        Args:
            symbol: An expression or constant naming a registered instrument.
            *actions: Operations applied in order to this instrument. In a snapshot,
                provide every retained order or level in the appropriate source order.
            snapshot: A boolean expression or constant. True clears the previous
                book before applying actions; false applies an incremental update.
            timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
            depth: The retained L2 depth per side after processing. Zero means no
                depth trimming. This is separate from Checksum.depth.
            checksum: An optional Checksum declaration checked after all actions.
            ready: Whether successful processing may mark the book synchronized.
                Use false while assembling an incomplete snapshot; the default is true.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            snapshot = lm.Book("XYZ", le.ForEach(le.Field("orders"),
                lm.Add(id=le.Field("id"), side=le.Field("side"), price=le.Field("price"), quantity=le.Field("size"))),
                snapshot=True, timestamp=le.Field("time").timestamp("ms"))
            ```
        """

@final
class BookLevel:
    """
    Describe the order-book detail provided by a source, independently of timing.
    
    L1 provides the best bid and ask, L2 aggregates quantities at each price, and
    L3 identifies individual resting orders. Only L3 supports viewing order queues
    and simulating a resting limit order on an alternate timeline.
    
    Examples:
        ```python
        from lobo.replay.adapters import models as lm
        depth = lm.BookLevel.L2
        ```
    """
    L1: Final[BookLevel]
    """
    The best quoted price and aggregate quantity on each side.
    """
    L2: Final[BookLevel]
    """
    Aggregate quantities at the published price levels.
    """
    L3: Final[BookLevel]
    """
    Individual orders and their queue priority at each price.
    """
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class Bootstrap:
    """
    Fetch one HTTP JSON response before opening a live source's connections.
    
    A bootstrap request is a startup discovery step. For example, an exchange's
    instrument endpoint can provide symbols and decimal precision needed to register
    books before subscription. It is not automatically an order-book snapshot:
    actions explicitly decide what to do with the response. A feed that sends its
    snapshot over WebSocket should handle that snapshot with a Message and Book.
    
    Args:
        name: A unique name for this request within the protocol. Source.packets and
            Source.json_lines use this name to associate supplied discovery responses
            with their actions when replaying recorded messages.
        url: The HTTP or HTTPS URL to GET for a live WebSocket source. The response
            must be JSON and is available through Field and Root expressions.
        *actions: Actions applied to the response in order. ForEach and Register can
            turn an array of instruments into the adapter's ticker directory.
    
    Examples:
    ```python
    from lobo.replay.adapters import expressions as le
    from lobo.replay.adapters import models as lm
    
    directory = lm.Bootstrap(
        "instruments", "https://feed.example/instruments",
        le.ForEach(le.Field("symbols"), lm.Register(symbol=le.Field("name"),
                price_decimals=le.Field("price_dp"), quantity_decimals=0)),
    )
    ```
    """
    def __new__(cls, /, name: str, url: str, *actions: "Action") -> Bootstrap: ...
    @property
    def data(self, /) -> Any:
        """
        Return the discovery request's name, URL, and response actions.
        
        Returns:
            A detached dictionary representing this startup request.
        """

@final
class Cancel(Action):
    """
    Subtract a cancellation quantity from a resting order without a trade event.
    
    Args:
        id: The ID of the order being reduced.
        quantity: The amount cancelled by this message, not its new total.
        timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        cancel = lm.Cancel(id=le.Field("id"), quantity=le.Field("cancelled_size"))
        ```
    """
    def __new__(cls, /, *, id: Any, quantity: Any, timestamp: Any |None = None) -> Cancel:
        """
        Subtract a cancellation quantity from a resting order without a trade event.
        
        Args:
            id: The ID of the order being reduced.
            quantity: The amount cancelled by this message, not its new total.
            timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            cancel = lm.Cancel(id=le.Field("id"), quantity=le.Field("cancelled_size"))
            ```
        """

@final
class Checksum:
    """
    Compare a source-provided CRC32 with a configured view of the completed book.
    
    Pass this object to Book.checksum. The book's checksum policy maintains the
    required state; Book compares the result after its actions finish. A missing
    or null expected value skips comparison for that message. This describes the
    source's checksum convention, rather than choosing a different hash algorithm.
    
    Args:
        expected: An expression yielding the checksum sent by the source, or None
            for messages that do not carry one.
        view: "levels" aggregates by price; "orders" includes individual orders.
        depth: The positive maximum number of entries per side, starting at the best
            price. Defaults to ten. Choose the value required by the source protocol.
        sides: The order of sides to include. Defaults to ("sell", "buy") when None.
        fields: Fields emitted for each entry. Defaults to ("price", "quantity")
            when None. Supported fields are "id", "price", "quantity", and
            "signed_quantity". Signed quantities are negative for asks.
        separator: Text placed between emitted values. Defaults to no separator.
        interleave: If True, alternate entries between sides at each rank. If False,
            emit all entries from one side before the next.
        format: "decimal_digits" removes the decimal point and leading zeroes;
            "decimal" emits decimal text; "ecmascript" uses JavaScript number
            formatting. Match the source's representation to reproduce its checksum.
        signed: Whether the expected checksum is a signed 32-bit integer. False
            compares it as an unsigned CRC32.
        priority: For individual orders at a price, "fifo" uses queue order and
            "id" sorts by order ID. Defaults to "fifo".
        on_failure: Actions run when the checksum differs, such as Send requests to
            unsubscribe and resubscribe. Defaults to no recovery messages. A mismatch
            invalidates synchronization; it does not roll back the preceding changes.
    
    Examples:
    ```python
    from lobo.replay.adapters import expressions as le
    from lobo.replay.adapters import models as lm
    
    check = lm.Checksum(le.Field("checksum"), depth=10)
    update = lm.Book(le.Field("symbol"), checksum=check)
    ```
    """
    def __new__(cls, /, expected: Any, *, view: str = "levels", depth: int = 10, sides: Sequence[str] |None = None, fields: Sequence[str] |None = None, separator: str = "", interleave: bool = False, format: str = "decimal_digits", signed: bool = False, priority: str = "fifo", on_failure: Iterable[Action] |None = None) -> Checksum: ...
    @property
    def data(self, /) -> Any:
        """
        Return checksum operands and formatting options as a detached dictionary.
        
        Returns:
            The public checksum definition, excluding prepared book policy state.
        """

@final
class Directory(Action):
    """
    Replace the list of available instruments using a complete directory response.
    
    Instruments omitted from the replacement are removed. Use ForEach instead
    for a partial list that must not remove other instruments.
    
    Args:
        items: An expression yielding the array of directory entries.
        *actions: Actions to run for each entry, normally Register. Field reads
            from that entry; Root still reads the complete directory response.
        symbol: An expression identifying the symbol of the current entry.
        on_remove: Actions for each omitted instrument. Variable("symbol") names
            that instrument, allowing remembered protocol state to be cleared.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        directory = lm.Directory(le.Field("instruments"),
            lm.Register(symbol=le.Field("symbol"), price_decimals=2, quantity_decimals=0),
            symbol=le.Field("symbol"))
        ```
    """
    def __new__(cls, /, items: Any, *actions: "Action", symbol: Any, on_remove: Iterable[Action] |None = None) -> Directory:
        """
        Replace the list of available instruments using a complete directory response.
        
        Instruments omitted from the replacement are removed. Use ForEach instead
        for a partial list that must not remove other instruments.
        
        Args:
            items: An expression yielding the array of directory entries.
            *actions: Actions to run for each entry, normally Register. Field reads
                from that entry; Root still reads the complete directory response.
            symbol: An expression identifying the symbol of the current entry.
            on_remove: Actions for each omitted instrument. Variable("symbol") names
                that instrument, allowing remembered protocol state to be cleared.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            directory = lm.Directory(le.Field("instruments"),
                lm.Register(symbol=le.Field("symbol"), price_decimals=2, quantity_decimals=0),
                symbol=le.Field("symbol"))
            ```
        """

@final
class DirectoryComplete(Action):
    """
    Mark an explicitly delimited instrument directory as complete.
    
    Place this on the source's directory-end message when instruments arrive
    individually, for example as Register actions in successive binary records.
    The directory scanner can then stop collecting instrument metadata.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        end_directory = lm.Message(le.Field("event").eq("directory_end"), lm.DirectoryComplete())
        ```
    """
    def __new__(cls, /) -> DirectoryComplete:
        """
        Mark an explicitly delimited instrument directory as complete.
        
        Place this on the source's directory-end message when instruments arrive
        individually, for example as Register actions in successive binary records.
        The directory scanner can then stop collecting instrument metadata.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            end_directory = lm.Message(le.Field("event").eq("directory_end"), lm.DirectoryComplete())
            ```
        """

@final
class Execute(Action):
    """
    Consume quantity from a known resting order and publish an execution.
    
    Use this when the source explicitly identifies a fill. It supplies traded
    volume and execution prices to the existing bar and simulation machinery.
    
    Args:
        id: The ID of the resting order that traded.
        quantity: The quantity executed by this message, not the quantity left.
        price: The execution price in integer atoms. None uses the resting
            order's price; provide an expression when the feed reports another price.
        timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        execute = lm.Execute(id=le.Field("id"), quantity=le.Field("executed_size"))
        ```
    """
    def __new__(cls, /, *, id: Any, quantity: Any, price: Any |None = None, timestamp: Any |None = None) -> Execute:
        """
        Consume quantity from a known resting order and publish an execution.
        
        Use this when the source explicitly identifies a fill. It supplies traded
        volume and execution prices to the existing bar and simulation machinery.
        
        Args:
            id: The ID of the resting order that traded.
            quantity: The quantity executed by this message, not the quantity left.
            price: The execution price in integer atoms. None uses the resting
                order's price; provide an expression when the feed reports another price.
            timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            execute = lm.Execute(id=le.Field("id"), quantity=le.Field("executed_size"))
            ```
        """

@final
class Fail(Action):
    """
    Fail the current message with an explanation from the protocol definition.
    
    Args:
        message: The error text reported to the adapter caller. A live socket
            source reconnects after a processing error; a finite source reports
            the error through wait() or run().
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        reject = le.When(le.Field("status").eq("error"), lm.Fail("The feed rejected the subscription"))
        ```
    """
    def __new__(cls, /, message: str) -> Fail:
        """
        Fail the current message with an explanation from the protocol definition.
        
        Args:
            message: The error text reported to the adapter caller. A live socket
                source reconnects after a processing error; a finite source reports
                the error through wait() or run().
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            reject = le.When(le.Field("status").eq("error"), lm.Fail("The feed rejected the subscription"))
            ```
        """

@final
class FeedMode:
    """
    Describe whether a source advances recorded time or receives ongoing updates.
    
    Examples:
        ```python
        from lobo.replay.adapters import models as lm
        mode = lm.FeedMode.Live
        ```
    """
    Live: Final[FeedMode]
    """
    Ongoing updates received as the source publishes them.
    """
    Replay: Final[FeedMode]
    """
    Recorded messages whose source clock can advance independently of wall time.
    """
    def __eq__(self, /, other: object) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __repr__(self, /) -> str: ...

class Format:
    """
    The wire format stored by Binary or Json.
    
    Construct Binary for length-prefixed records or Json for JSON message rules.
    Both hold the same Rust format used by Protocol and the adapter compiler.
    This shared base is not constructed directly from Python.
    
    Examples:
        ```python
        from lobo.replay.adapters import models as lm
    
        messages = lm.Json()
        ```
    """
    @property
    def data(self, /) -> Any:
        """
        Return a detached dictionary containing this format and its message rules.
        
        Returns:
            The serializable format definition; editing it does not change the format.
        """

@final
class Instrument:
    """
    Describe one instrument's symbol, decimal precision, and book policy.
    
    Pass an iterable of Instrument objects to CustomAdapter when this information is
    known before the source starts. A generator is consumed once during construction.
    Sources that publish instrument metadata can use Register actions instead.
    
    Args:
        symbol: The ticker used to identify and select this book. Surrounding whitespace
            is removed and letters are normalized to uppercase.
        price_decimals: Number of fractional price digits. With two digits, an integer
            action price of 12345 represents 123.45.
        quantity_decimals: Number of fractional quantity digits. With three digits,
            an integer action quantity of 1250 represents 1.250 units.
        book_policy: "full" maintains user lookup and hidden quantities; "no_user_map"
            maintains hidden quantities only; "no_hidden_quantity" maintains user lookup
            only; "no_updates" maintains neither and is the default. Hidden-quantity
            policies are required to retain iceberg reserve quantities. This choice is
            applied when constructing the book, before messages are processed.
    
    Raises:
        ValueError: The symbol is invalid or book_policy is not a supported policy name.
        OverflowError: A decimal count is outside the unsigned-byte range.
    
    Examples:
        ```python
        from lobo.replay.adapters import models as lm
    
        instrument = lm.Instrument("AAPL", price_decimals=4, quantity_decimals=0)
        ```
    """
    def __new__(cls, /, symbol: str, price_decimals: int, quantity_decimals: int, *, book_policy: str = "no_updates") -> Instrument: ...
    @property
    def book_policy(self, /) -> str:
        """
        The policy selected for user lookup and hidden-quantity maintenance.
        """
    @property
    def price_decimals(self, /) -> int:
        """
        The number of fractional digits represented by integer price atoms.
        """
    @property
    def quantity_decimals(self, /) -> int:
        """
        The number of fractional digits represented by integer quantity atoms.
        """
    @property
    def symbol(self, /) -> str:
        """
        The normalized instrument symbol used for book routing.
        """

@final
class Json(Format):
    """
    Describe a JSON stream as an ordered collection of message rules.
    
    Every matching Message runs its actions, in declaration order. A message that
    matches no rule is ignored. Rules can distinguish control messages, snapshots,
    updates, and trades without assigning those shapes to separate adapters.
    
    Args:
        *messages: Message objects containing a condition and the actions it enables.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        wire = lm.Json(lm.Message(le.Field("type").eq("heartbeat"), le.Let("alive", True)))
        ```
    """
    def __new__(cls, /, *messages: "Message") -> Json: ...

@final
class Level(Action):
    """
    Set the total displayed quantity at one L2 price level.
    
    Args:
        side: "buy" or "sell", or an expression producing that side.
        price: The positive level price in integer atoms. decimal() expressions
            also preserve the source's decimal width for checksum calculation.
        quantity: The new absolute level quantity in integer atoms. Zero removes
            the level. This action does not invent executions from reductions.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        level = lm.Level(side="buy", price=le.Field("price").decimal(2),
                      quantity=le.Field("quantity").decimal(8))
        ```
    """
    def __new__(cls, /, *, side: Any, price: Any, quantity: Any) -> Level:
        """
        Set the total displayed quantity at one L2 price level.
        
        Args:
            side: "buy" or "sell", or an expression producing that side.
            price: The positive level price in integer atoms. decimal() expressions
                also preserve the source's decimal width for checksum calculation.
            quantity: The new absolute level quantity in integer atoms. Zero removes
                the level. This action does not invent executions from reductions.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            level = lm.Level(side="buy", price=le.Field("price").decimal(2),
                          quantity=le.Field("quantity").decimal(8))
            ```
        """

@final
class Message:
    """
    Apply a group of actions when a JSON message satisfies a condition.
    
    Json evaluates rules in order. All matching rules run, so use mutually exclusive
    conditions when a packet should follow only one path. Unmatched packets are ignored.
    
    Args:
        condition: A boolean expression evaluated against the incoming JSON message.
        *actions: Actions to execute in order when condition is true.
    
    Examples:
    ```python
    from lobo.replay.adapters import expressions as le
    from lobo.replay.adapters import models as lm
    
    rule = lm.Message(le.Field("type").eq("heartbeat"), le.Let("connected", True))
    ```
    """
    def __new__(cls, /, condition: Any, *actions: "Action") -> Message: ...
    @property
    def data(self, /) -> Any:
        """
        Return this rule's condition and ordered actions as a detached dictionary.
        
        Returns:
            The serializable rule definition.
        """

@final
class Modify(Action):
    """
    Set a known order's absolute visible quantity, retaining its price and side.
    
    Args:
        id: The ID of an existing resting order.
        quantity: The new visible total in integer atoms, not a delta. A
            decrease alone is not proof of a trade; use Execute for known fills.
        timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        modify = lm.Modify(id=le.Field("id"), quantity=le.Field("remaining_size"))
        ```
    """
    def __new__(cls, /, *, id: Any, quantity: Any, timestamp: Any |None = None) -> Modify:
        """
        Set a known order's absolute visible quantity, retaining its price and side.
        
        Args:
            id: The ID of an existing resting order.
            quantity: The new visible total in integer atoms, not a delta. A
                decrease alone is not proof of a trade; use Execute for known fills.
            timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            modify = lm.Modify(id=le.Field("id"), quantity=le.Field("remaining_size"))
            ```
        """

@final
class OrderCommand(Action):
    """
    Apply a message already shaped like the library's order API command.
    
    Args:
        value: An expression yielding the command object, including its op and
            the fields required by add, execute, cancel, remove, modify, fill,
            or simulate. The selected Book supplies the target instrument.
        timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        command = lm.OrderCommand(le.Field("command"), timestamp=le.Field("timestamp_ns"))
        ```
    """
    def __new__(cls, /, value: Any, *, timestamp: Any |None = None) -> OrderCommand:
        """
        Apply a message already shaped like the library's order API command.
        
        Args:
            value: An expression yielding the command object, including its op and
                the fields required by add, execute, cancel, remove, modify, fill,
                or simulate. The selected Book supplies the target instrument.
            timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            command = lm.OrderCommand(le.Field("command"), timestamp=le.Field("timestamp_ns"))
            ```
        """

@final
class Record:
    """
    Describe one binary record's payload and the actions it triggers.
    
    Named fields become available through Field("name") while its actions run.
    The enclosing Binary format supplies the record tag, routing key, and clock.
    
    Args:
        size: The exact payload size in bytes, excluding the length prefix.
        fields: A dictionary from field names to UInt or Text declarations. Offsets
            are relative to the start of the payload, not to the length prefix.
        actions: Actions to execute in order for this record type. An empty sequence
            can describe a record that affects no book state.
    
    Raises:
        ValueError: A field extends outside the payload or has an unsupported layout.
        TypeError: A field is not a UInt or Text, or an action is not an Action.
    
    Examples:
    ```python
    from lobo.replay.adapters import models as lm
    
    heartbeat = lm.Record(size=11, fields={"clock": lm.UInt(3, 8)}, actions=())
    ```
    """
    def __new__(cls, /, *, size: int, fields: Mapping[str, BinaryField], actions: Iterable[Action]) -> Record: ...
    @property
    def data(self, /) -> Any:
        """
        Return the payload size, named fields, and ordered actions as a dictionary.
        
        Returns:
            A detached representation of this record layout.
        """

@final
class Register(Action):
    """
    Register an instrument and the units and policies used to construct its book.
    
    Args:
        symbol: The instrument's ticker or pair name. Symbols are normalized by
            the context and also supply ticker autocomplete in the app.
        price_decimals: Decimal places represented by integer price atoms.
            A value of 2 means 12345 atoms represent 123.45.
        quantity_decimals: Decimal places represented by integer quantity atoms.
            Use 0 for whole shares and an appropriate scale for fractional units.
        key: An optional unsigned binary routing key, such as a stock locator.
            Later records carrying that key can select this book directly.
        policy: "full", "no_user_map", "no_hidden_quantity", or "no_updates".
            These choose user-map and hidden-quantity bookkeeping at book
            construction. "no_updates" disables both and is the default.
            Policies without hidden updates treat submitted reserves as absent.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        register = lm.Register(symbol=le.Field("symbol"), price_decimals=2,
                            quantity_decimals=0, key=le.Variable("key"))
        ```
    """
    def __new__(cls, /, *, symbol: Any, price_decimals: Any, quantity_decimals: Any, key: Any |None = None, policy: Any |None = None) -> Register:
        """
        Register an instrument and the units and policies used to construct its book.
        
        Args:
            symbol: The instrument's ticker or pair name. Symbols are normalized by
                the context and also supply ticker autocomplete in the app.
            price_decimals: Decimal places represented by integer price atoms.
                A value of 2 means 12345 atoms represent 123.45.
            quantity_decimals: Decimal places represented by integer quantity atoms.
                Use 0 for whole shares and an appropriate scale for fractional units.
            key: An optional unsigned binary routing key, such as a stock locator.
                Later records carrying that key can select this book directly.
            policy: "full", "no_user_map", "no_hidden_quantity", or "no_updates".
                These choose user-map and hidden-quantity bookkeeping at book
                construction. "no_updates" disables both and is the default.
                Policies without hidden updates treat submitted reserves as absent.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            register = lm.Register(symbol=le.Field("symbol"), price_decimals=2,
                                quantity_decimals=0, key=le.Variable("key"))
            ```
        """

@final
class Remove(Action):
    """
    Delete a resting order in full without reporting a trade.
    
    Args:
        id: The ID of the order to remove.
        timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        remove = lm.Remove(id=le.Field("order_id"))
        ```
    """
    def __new__(cls, /, *, id: Any, timestamp: Any |None = None) -> Remove:
        """
        Delete a resting order in full without reporting a trade.
        
        Args:
            id: The ID of the order to remove.
            timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            remove = lm.Remove(id=le.Field("order_id"))
            ```
        """

@final
class Replace(Action):
    """
    Replace an order with a new identity, limit price, and visible quantity.
    
    Args:
        id: The ID of the order being replaced.
        new_id: The ID assigned to the replacement order.
        price: The replacement's positive limit price in integer atoms.
        quantity: The replacement's complete visible quantity in integer atoms.
        timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        replace = lm.Replace(id=le.Field("old_id"), new_id=le.Field("new_id"),
                          price=le.Field("price"), quantity=le.Field("size"))
        ```
    """
    def __new__(cls, /, *, id: Any, new_id: Any, price: Any, quantity: Any, timestamp: Any |None = None) -> Replace:
        """
        Replace an order with a new identity, limit price, and visible quantity.
        
        Args:
            id: The ID of the order being replaced.
            new_id: The ID assigned to the replacement order.
            price: The replacement's positive limit price in integer atoms.
            quantity: The replacement's complete visible quantity in integer atoms.
            timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            replace = lm.Replace(id=le.Field("old_id"), new_id=le.Field("new_id"),
                              price=le.Field("price"), quantity=le.Field("size"))
            ```
        """

@final
class RestoreOrder(Action):
    """
    Restore one order from the server's resting-order snapshot representation.
    
    Apply these actions in the snapshot's FIFO order. No timestamp sorting is
    added, so replenished iceberg orders retain their correct queue positions.
    
    Args:
        value: An expression yielding an object with id, trader, side, price,
            quantity, created_at_ns, hidden_quantity, and peak_quantity. These
            are the fields of the server's RestingOrderState schema.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        snapshot_rows = le.ForEach(le.Field("orders"), lm.RestoreOrder(le.Field()))
        ```
    """
    def __new__(cls, /, value: Any) -> RestoreOrder:
        """
        Restore one order from the server's resting-order snapshot representation.
        
        Apply these actions in the snapshot's FIFO order. No timestamp sorting is
        added, so replenished iceberg orders retain their correct queue positions.
        
        Args:
            value: An expression yielding an object with id, trader, side, price,
                quantity, created_at_ns, hidden_quantity, and peak_quantity. These
                are the fields of the server's RestingOrderState schema.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            snapshot_rows = le.ForEach(le.Field("orders"), lm.RestoreOrder(le.Field()))
            ```
        """

@final
class Send(Action):
    """
    Queue a JSON control message for the current source connection.
    
    Args:
        message: A dictionary, list, constant, or expression describing the
            outgoing JSON value. Embedded expressions are evaluated when the
            action executes. This is commonly a subscription or ping request.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        subscribe = lm.Send({"method": "subscribe", "symbol": le.Variable("symbol")})
        ```
    """
    def __new__(cls, /, message: Any) -> Send:
        """
        Queue a JSON control message for the current source connection.
        
        Args:
            message: A dictionary, list, constant, or expression describing the
                outgoing JSON value. Embedded expressions are evaluated when the
                action executes. This is commonly a subscription or ping request.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            subscribe = lm.Send({"method": "subscribe", "symbol": le.Variable("symbol")})
            ```
        """

@final
class Source:
    """
    Specify where an adapter obtains its incoming messages.
    
    Use file for a binary replay file, http for an HTTP binary replay stream,
    websocket for a live feed, json_lines for recorded JSON messages, or packets for
    an in-memory collection of raw messages. Constructing a Source does not open it.
    CustomAdapter owns the source's lifecycle and obtains all book changes through
    its Protocol.
    
    Examples:
        ```python
        from lobo.replay.adapters import models as lm
    
        source = lm.Source.file("01302020.NASDAQ_ITCH50.gz")
        live = lm.Source.websocket("wss://feed.example/ws")
        ```
    """
    @property
    def _source_spec(self, /) -> str: ...
    @staticmethod
    def file(path: str |PathLike[str], *, chunk_size: int = 1048576) -> Source:
        """
        Describe a local binary replay file, optionally gzip-compressed.
        
        Args:
            path: A string or path-like filename. Date-based intraday formats need the
                session date in the filename, such as 01302020.NASDAQ_ITCH50.
            chunk_size: Bytes read per input chunk, between 1 and 4,194,304. Defaults
                to 1,048,576. This controls input buffering, not message or sink batch size.
        
        Returns:
            A Source that opens the file when its adapter starts or runs.
        
        Raises:
            ValueError: chunk_size is outside the supported range.
        
        Examples:
            ```python
            from lobo.replay.adapters import models as lm
        
            source = lm.Source.file("01302020.NASDAQ_ITCH50.gz")
            ```
        """
    @staticmethod
    def http(url: str, *, chunk_size: int = 1048576) -> Source:
        """
        Describe a binary replay streamed from an HTTP or HTTPS URL.
        
        The reader decompresses gzip content as it arrives. It does not save a local
        copy. Use start() and wait() for this streaming source; run() requires a local file.
        
        Args:
            url: The complete HTTP or HTTPS URL. Intraday date-based formats need a
                session date in the URL filename, just as a local replay file does.
            chunk_size: Maximum reader chunk size in bytes, from 1 through 4,194,304.
                Defaults to 1,048,576.
        
        Returns:
            A Source that requests the URL when the adapter starts.
        
        Raises:
            ValueError: The URL scheme or chunk_size is unsupported.
        
        Examples:
            ```python
            from lobo.replay.adapters import models as lm
        
            source = lm.Source.http("https://feed.example/01302020.NASDAQ_ITCH50.gz")
            ```
        """
    @staticmethod
    def json_lines(path: str |PathLike[str], *, bootstrap: Sequence[tuple[str, bytes]] = ...) -> Source:
        """
        Describe a recording with one complete JSON message on each line.
        
        Args:
            path: The string or path-like filename containing the recorded messages.
            bootstrap: Optional (request_name, response_bytes) pairs supplying startup
                discovery responses. Names must match Protocol.bootstrap declarations.
                These responses are applied before recorded messages; no discovery HTTP
                requests are made for this source. Defaults to an empty collection.
        
        Returns:
            A Source for streaming the recorded messages in file order.
        
        Examples:
            ```python
            from lobo.replay.adapters import models as lm
        
            source = lm.Source.json_lines("updates.jsonl")
            ```
        """
    @staticmethod
    def packets(packets: Sequence[bytes], *, bootstrap: Sequence[tuple[str, bytes]] = ...) -> Source:
        """
        Describe a finite sequence of raw messages already available in memory.
        
        Args:
            packets: A sequence of bytes objects containing complete JSON messages or
                chunks of a length-prefixed binary stream, in arrival order. Python
                supplies bytes; Protocol describes how they become book operations.
            bootstrap: Optional (request_name, response_bytes) pairs for the protocol's
                startup discovery requests, applied before packets. Defaults to none.
        
        Returns:
            A finite Source useful for examples, recordings, and deterministic tests.
        
        Examples:
            ```python
            from lobo.replay.adapters import models as lm
        
            source = lm.Source.packets([b'{"type":"heartbeat"}'])
            ```
        """
    @staticmethod
    def websocket(endpoint: str |None = None, *, heartbeat: TextHeartbeat |None = None) -> Source:
        """
        Describe a live WebSocket source.
        
        Args:
            endpoint: The ws:// or wss:// URL used for the live connection. None defers
                to an endpoint already provided by the adapter descriptor; a custom
                adapter constructed directly from Python should supply the URL here.
            heartbeat: Optional TextHeartbeat for a server that sends plain text
                control frames. The transport consumes matching replies before decoding.
                Omit it for feeds whose heartbeat is expressed by Protocol.keepalive.
        
        Returns:
            A Source that opens live connections when its adapter starts. The protocol's
            discovery, handshake, subscription, and keepalive actions control the feed.
        
        Examples:
            ```python
            from lobo.replay.adapters import models as lm
        
            source = lm.Source.websocket("wss://feed.example/ws")
            ```
        """

@final
class Subscribe(Action):
    """
    Allow subscriptions and send them for selected instruments that are known.
    
    This runs Protocol.subscriptions with Variable("symbol") and precision
    variables set for each requested instrument. Previously sent subscriptions
    are not repeated until reconnect. Place it in connect when the source is
    immediately ready, or after an acknowledgement when negotiation is required.
    
    Examples:
        ```python
        from lobo.replay.adapters import Protocol
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        protocol = Protocol(lm.Json(), connect=(lm.Subscribe(),),
            subscriptions=(lm.Send({"subscribe": le.Variable("symbol")}),))
        ```
    """
    def __new__(cls, /) -> Subscribe:
        """
        Allow subscriptions and send them for selected instruments that are known.
        
        This runs Protocol.subscriptions with Variable("symbol") and precision
        variables set for each requested instrument. Previously sent subscriptions
        are not repeated until reconnect. Place it in connect when the source is
        immediately ready, or after an acknowledgement when negotiation is required.
        
        Examples:
            ```python
            from lobo.replay.adapters import Protocol
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            protocol = Protocol(lm.Json(), connect=(lm.Subscribe(),),
                subscriptions=(lm.Send({"subscribe": le.Variable("symbol")}),))
            ```
        """

@final
class Text(BinaryField):
    """
    Read UTF-8 text from a fixed range of bytes and trim surrounding whitespace.
    
    Args:
        offset: The zero-based byte offset from the start of the record payload,
            excluding its length prefix.
        size: The positive number of bytes occupied by the text, including padding.
    
    Raises:
        ValueError: The size is zero or the byte range overflows.
    
    Examples:
        ```python
        from lobo.replay.adapters import models as lm
    
        stock = lm.Text(24, 8)
        ```
    """
    def __new__(cls, /, offset: int, size: int) -> Text: ...

@final
class TextHeartbeat:
    """
    Send and consume a source's application-level text heartbeat.
    
    Configure this on Source.websocket when the server expects a plain text frame,
    rather than a JSON message or a WebSocket Ping control frame. Matching replies
    are handled by the transport before market-data decoding.
    
    Args:
        request: The exact text sent to the server, without JSON quotation marks.
        reply: The exact reply text consumed by the transport.
        interval: Seconds between requests. Must be finite and positive. Defaults to 10.
    
    Raises:
        ValueError: The interval is invalid or either text is empty.
    
    Examples:
    ```python
    from lobo.replay.adapters import models as lm
    
    heartbeat = lm.TextHeartbeat("PING", "PONG", interval=10)
    source = lm.Source.websocket("wss://feed.example/ws", heartbeat=heartbeat)
    ```
    """
    def __new__(cls, /, request: str, reply: str, *, interval: float = 10.0) -> TextHeartbeat: ...

@final
class Trade(Action):
    """
    Report a public trade at its actual execution price.
    
    This feeds traded-volume bars and an active simulation. It does not reduce
    the main book again when a separate order or level update already did so.
    Trades are ignored until the instrument has a synchronized snapshot.
    
    Args:
        price: The execution price in integer price atoms.
        quantity: The executed quantity in integer quantity atoms.
        maker_side: The resting side that was consumed: "buy" for a resting bid
            or "sell" for a resting ask. This is opposite to the taker's side.
        timestamp: The trade's source time in nanoseconds.
        id: An optional monotonic unsigned trade ID. When supplied, IDs at or
            below the last accepted ID are ignored, preventing duplicate trades.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        trade = lm.Trade(price=le.Field("price"), quantity=le.Field("size"), maker_side="sell",
                      timestamp=le.Field("time").timestamp("ms"), id=le.Field("trade_id"))
        ```
    """
    def __new__(cls, /, *, price: Any, quantity: Any, maker_side: Any, timestamp: Any, id: Any |None = None) -> Trade:
        """
        Report a public trade at its actual execution price.
        
        This feeds traded-volume bars and an active simulation. It does not reduce
        the main book again when a separate order or level update already did so.
        Trades are ignored until the instrument has a synchronized snapshot.
        
        Args:
            price: The execution price in integer price atoms.
            quantity: The executed quantity in integer quantity atoms.
            maker_side: The resting side that was consumed: "buy" for a resting bid
                or "sell" for a resting ask. This is opposite to the taker's side.
            timestamp: The trade's source time in nanoseconds.
            id: An optional monotonic unsigned trade ID. When supplied, IDs at or
                below the last accepted ID are ignored, preventing duplicate trades.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            trade = lm.Trade(price=le.Field("price"), quantity=le.Field("size"), maker_side="sell",
                          timestamp=le.Field("time").timestamp("ms"), id=le.Field("trade_id"))
            ```
        """

@final
class TradeHistory(Action):
    """
    Advance the known trade ID without publishing a historical execution.
    
    Args:
        id: An expression or constant yielding an unsigned monotonic trade ID.
            The largest observed value is retained. Subsequent Trade actions
            ignore IDs at or below this value.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        history = le.ForEach(le.Field("recent_trades"), lm.TradeHistory(le.Field("id")))
        ```
    """
    def __new__(cls, /, id: Any) -> TradeHistory:
        """
        Advance the known trade ID without publishing a historical execution.
        
        Args:
            id: An expression or constant yielding an unsigned monotonic trade ID.
                The largest observed value is retained. Subsequent Trade actions
                ignore IDs at or below this value.
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            history = le.ForEach(le.Field("recent_trades"), lm.TradeHistory(le.Field("id")))
            ```
        """

@final
class UInt(BinaryField):
    """
    Read an unsigned integer from a fixed range of bytes.
    
    Args:
        offset: The zero-based offset from the start of the record payload. For
            Binary.length only, this is the offset in the length prefix and must be zero.
        size: The number of bytes occupied by the integer, from one through eight.
        byteorder: "big" for most-significant byte first, or "little" for the reverse.
    
    Raises:
        ValueError: The byte order or size is unsupported.
    
    Examples:
        ```python
        from lobo.replay.adapters import models as lm
    
        order_id = lm.UInt(11, 8)
        ```
    """
    def __new__(cls, /, offset: int, size: int, *, byteorder: str = "big") -> UInt: ...

@final
class Upsert(Action):
    """
    Apply an absolute order update, creating an order if its ID is new.
    
    A null price removes the ID. Live L3 feeds often publish this form of update
    and report trades separately. During an alternate simulation, the existing
    reconciliation policy coordinates these updates with Trade actions.
    
    Args:
        id: The source's persistent order ID.
        side: "buy" or "sell", or an expression producing that value.
        price: The limit price in integer atoms, or an expression producing None
            for removal. Translate a feed's deletion sentinel with Choose.
        quantity: The complete visible quantity in integer atoms.
        timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        update = lm.Upsert(id=le.Field("id"), side="buy", quantity=le.Field("size"),
                        price=le.Choose(le.Field("price").eq(0), None, le.Field("price")))
        ```
    """
    def __new__(cls, /, *, id: Any, side: Any, price: Any, quantity: Any, timestamp: Any |None = None) -> Upsert:
        """
        Apply an absolute order update, creating an order if its ID is new.
        
        A null price removes the ID. Live L3 feeds often publish this form of update
        and report trades separately. During an alternate simulation, the existing
        reconciliation policy coordinates these updates with Trade actions.
        
        Args:
            id: The source's persistent order ID.
            side: "buy" or "sell", or an expression producing that value.
            price: The limit price in integer atoms, or an expression producing None
                for removal. Translate a feed's deletion sentinel with Choose.
            quantity: The complete visible quantity in integer atoms.
            timestamp: Source time in nanoseconds. None or omission uses Variable("clock").
        
        Examples:
            ```python
            from lobo.replay.adapters import expressions as le
            from lobo.replay.adapters import models as lm
        
            update = lm.Upsert(id=le.Field("id"), side="buy", quantity=le.Field("size"),
                            price=le.Choose(le.Field("price").eq(0), None, le.Field("price")))
            ```
        """

def specification(value: Any) -> Any:
    """
    Export a declaration as ordinary Python dictionaries, lists, and constants.
    
    This is useful for saving a protocol definition or comparing it with another
    definition. Adapter construction accepts the Rust-backed objects directly;
    callers do not need to export a protocol before passing it to CustomAdapter.
    
    Args:
        value: A protocol, expression, action, format, or a list or dictionary
            containing declarations and JSON-compatible constants.
    
    Returns:
        A detached Python value that can be passed to json.dumps(). Mutating the
        returned value does not change the original declaration.
    
    Raises:
        TypeError: A value cannot be represented in a declaration.
        ValueError: A number is not finite or a byte string is not ASCII.
    
    Examples:
        ```python
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
        assert lm.specification(le.Field("price"))["path"] == ["price"]
        ```
    """
