# Not autogenerated.
"""Export the example declarations used by the Rust parity tests."""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from examples.bitfinex import adapter as bitfinex
from examples.itch import adapter as itch
from examples.kraken import adapter as kraken
from examples.order_feed import adapter as order_feed
from lobo.replay.adapters import models as lm


def export() -> None:
    """Write reproducible test inputs from the Python definitions."""
    target = (
        Path(__file__).resolve().parents[2]
        / "rust/crates/lobo_replay/tests/definitions"
    )
    for name, protocol in (
        ("itch", itch.protocol()),
        ("kraken", kraken.protocol(10)),
        ("bitfinex", bitfinex.protocol()),
        ("server", order_feed.protocol()),
    ):
        (target / f"{name}.json").write_text(
            json.dumps(lm.specification(protocol), indent=2) + "\n"
        )


if __name__ == "__main__":
    export()
