# Not autogenerated.
"""Launch the terminal for books created by this Python process."""

from threading import Event
from uuid import uuid4

from lobo import Book, server_context
from lobo.orders import LimitOrder, Side


def main() -> None:
    """Seed two native books, then accept API orders until interrupted."""
    with server_context(price_decimals=2) as server:
        books = [Book("AAPL"), Book("MSFT")]
        trader = uuid4()
        for book, midpoint in zip(books, [18960, 41000], strict=True):
            for level in range(1, 21):
                book.fill(
                    LimitOrder(midpoint - level, 100 + 10 * level, trader, Side.Buy)
                )
                book.fill(
                    LimitOrder(midpoint + level, 100 + 10 * level, trader, Side.Sell)
                )
        print(f"Terminal and API: {server.url}", flush=True)
        print(
            "Send orders to /api/books/AAPL/orders. Ctrl-C stops the server.",
            flush=True,
        )
        try:
            Event().wait()
        except KeyboardInterrupt:
            pass


if __name__ == "__main__":
    main()
