# Not autogenerated.
"""Discover Polymarket instruments and serve their live books in the terminal."""

import argparse
import logging
import webbrowser
from threading import Event

from lobo import server_context

if __package__:
    from .adapter import build_adapter
else:
    from adapter import build_adapter


def main() -> None:
    """Discover outcomes, then serve until interrupted."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument(
        "--open", action="store_true", help="Open the terminal in a browser"
    )
    parser.add_argument(
        "--token",
        action="append",
        nargs=2,
        metavar=("LABEL", "TOKEN_ID"),
        help="Optional explicit outcome; omit to discover available instruments",
    )
    args = parser.parse_args()
    tokens = dict(args.token) if args.token else None
    if tokens is not None and len(tokens) != len(args.token):
        parser.error("Each --token must have a different book label")
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    if tokens is None:
        print(
            "Discovering the 1,000 most liquid non-empty Polymarket markets...",
            flush=True,
        )
    try:
        adapter = build_adapter(tokens)
    except (RuntimeError, ValueError) as error:
        parser.error(str(error))

    with server_context(adapters=[adapter], port=args.port) as server:
        print(server.url, flush=True)
        if args.open:
            webbrowser.open(server.url)
        try:
            Event().wait()
        except KeyboardInterrupt:
            pass


if __name__ == "__main__":
    main()
