# Not autogenerated.
"""Kraken v2 defined using the custom adapter API."""

from lobo.replay.adapters import CustomAdapter, Protocol
from lobo.replay.adapters import expressions as le
from lobo.replay.adapters import models as lm


def protocol(depth: int = 100) -> Protocol:
    # The library supplies these variables for the instrument being processed.
    symbol = le.Variable("symbol")
    return Protocol(
        lm.Json(
            lm.Message(
                le.Field("success").eq(False), lm.Fail("Subscription request failed")
            ),
            lm.Message(
                le.Field("channel").eq("instrument"),
                # Instrument discovery supplies each pair's decimal precision.
                le.ForEach(
                    le.Field("data", "pairs"),
                    le.When(
                        le.Field("status").ne("delisted")
                        & le.Field("status").ne("work_in_progress"),
                        lm.Register(
                            symbol=le.Field("symbol"),
                            price_decimals=le.Field("price_precision"),
                            quantity_decimals=le.Field("qty_precision"),
                        ),
                    ),
                ),
                lm.Subscribe(),
            ),
            lm.Message(
                le.Field("channel").eq("book"),
                le.ForEach(
                    le.Field("data"),
                    lm.Book(
                        le.Field("symbol"),
                        # Level assigns absolute quantity; zero removes a level.
                        le.ForEach(
                            le.Field("asks"),
                            lm.Level(
                                side="sell",
                                price=le.Field("price").decimal(
                                    le.Variable("price_decimals")
                                ),
                                quantity=le.Field("qty").decimal(
                                    le.Variable("quantity_decimals")
                                ),
                            ),
                        ),
                        le.ForEach(
                            le.Field("bids"),
                            lm.Level(
                                side="buy",
                                price=le.Field("price").decimal(
                                    le.Variable("price_decimals")
                                ),
                                quantity=le.Field("qty").decimal(
                                    le.Variable("quantity_decimals")
                                ),
                            ),
                        ),
                        snapshot=le.Root("type").eq("snapshot"),
                        timestamp=le.Field("timestamp").timestamp("rfc3339"),
                        depth=depth,
                        checksum=lm.Checksum(
                            le.Field("checksum"),
                            depth=10,  # Kraken checks the best 10 levels per side,
                            # independently of the subscription depth.
                            on_failure=(
                                lm.Send(
                                    {
                                        "method": "unsubscribe",
                                        "params": {
                                            "channel": "book",
                                            "symbol": [symbol],
                                            "depth": depth,
                                        },
                                    }
                                ),
                                lm.Send(
                                    {
                                        "method": "subscribe",
                                        "params": {
                                            "channel": "book",
                                            "symbol": [symbol],
                                            "depth": depth,
                                            "snapshot": True,
                                        },
                                    }
                                ),
                            ),
                        ),
                    ),
                ),
            ),
            lm.Message(
                le.Field("channel").eq("trade") & le.Field("type").eq("update"),
                le.ForEach(
                    le.Field("data"),
                    lm.Book(
                        le.Field("symbol"),
                        lm.Trade(
                            id=le.Field("trade_id"),
                            price=le.Field("price").decimal(
                                le.Variable("price_decimals")
                            ),
                            quantity=le.Field("qty").decimal(
                                le.Variable("quantity_decimals")
                            ),
                            # Kraken reports the taker side; Trade needs the maker.
                            maker_side=le.Field("side").map(
                                {"buy": "sell", "sell": "buy"}
                            ),
                            timestamp=le.Field("timestamp").timestamp("rfc3339"),
                        ),
                        timestamp=le.Field("timestamp").timestamp("rfc3339"),
                        ready=False,
                    ),
                ),
            ),
        ),
        connect=(
            lm.Send(
                {
                    "method": "subscribe",
                    "params": {"channel": "instrument", "snapshot": True},
                }
            ),
        ),
        keepalive=(lm.Send({"method": "ping"}),),
        subscriptions=(
            lm.Send(
                {
                    "method": "subscribe",
                    "params": {
                        "channel": "book",
                        "symbol": [symbol],
                        "depth": depth,
                        "snapshot": True,
                    },
                }
            ),
            lm.Send(
                {
                    "method": "subscribe",
                    "params": {
                        "channel": "trade",
                        "symbol": [symbol],
                        "snapshot": False,
                    },
                }
            ),
        ),
    )


def build_adapter(*, symbol: str = "BTC/USD", depth: int = 100) -> CustomAdapter:
    return CustomAdapter(
        protocol(depth),
        lm.Source.websocket("wss://ws.kraken.com/v2"),
        symbol=symbol,
        scope=[symbol],
        name="Kraken Spot",
        level=lm.BookLevel.L2,
        mode=lm.FeedMode.Live,
    )
