# Not autogenerated.
"""Lazy Polars views over order-book price levels."""

from collections.abc import Generator
from typing import Protocol

import polars as pl
from polars.io.plugins import register_io_source

_LEVEL_SCHEMA = {
    "price": pl.UInt64,
    "quantity": pl.UInt64,
    "hidden_quantity": pl.UInt64,
    "order_count": pl.UInt64,
}


class _LevelSource(Protocol):
    """Storage view that can materialize price levels."""

    def _levels_df(self, n_rows: int | None) -> pl.DataFrame: ...


def levels_lazy(side: _LevelSource) -> pl.LazyFrame:
    """Expose a book side as a lazy Polars frame.

    Args:
        side: A standard or replay order-storage side.

    Returns:
        A lazy frame containing price-level aggregates.
    """

    def source(
        with_columns: list[str] | None,
        predicate: pl.Expr | None,
        n_rows: int | None,
        _batch_size: int | None,
    ) -> Generator[pl.DataFrame]:
        df = side._levels_df(n_rows)  # pyright: ignore[reportPrivateUsage]

        if predicate is not None:
            df = df.filter(predicate)

        if with_columns is not None:
            df = df.select(with_columns)

        yield df

    return register_io_source(
        io_source=source,
        schema=_LEVEL_SCHEMA,
    )
