use pyo3::pymodule;
mod context;
mod replay;
/// AUTOGENERATED FROM RUST. DO NOT EDIT.
#[pymodule]
#[pyo3(name = "_lobo")]
mod lobo {
    use pyo3::prelude::*;

    #[pymodule_export]
    use lobo_books::price_time_priority::PyBook;
    #[pymodule_export]
    use lobo_models::CheckSum;

    #[pymodule_export]
    use super::context_native;
    #[pymodule_export]
    use super::orders;
    #[pymodule_export]
    use super::server_native;
    #[pymodule_export]
    use super::sinks;

    #[pymodule_export]
    use super::replay_native;
    #[pymodule_export]
    use super::storage;
    #[pymodule_export]
    use lobo_books::price_time_priority::PyCancel;
    #[pymodule_export]
    use lobo_books::price_time_priority::PyExecution;
    #[pymodule_export]
    use lobo_books::price_time_priority::PyFill;
    #[pymodule_export]
    use lobo_books::price_time_priority::PyMarketImpact;
    #[pymodule_export]
    use lobo_books::price_time_priority::PyMatchedFill;
    #[pymodule_export]
    use lobo_books::price_time_priority::PyReport;
    #[pymodule_export]
    use lobo_books::price_time_priority::PyReports;
    #[pymodule_export]
    use lobo_books::price_time_priority::PySummary;

    #[pymodule_init]
    fn init(module: &Bound<'_, PyModule>) -> PyResult<()> {
        let py = module.py();
        let modules = py.import("sys")?.getattr("modules")?;

        let orders = module.getattr("orders")?;
        let replay = module.getattr("replay")?;
        let storage = module.getattr("storage")?;
        let sinks = module.getattr("sinks")?;
        let context = module.getattr("context")?;
        let adapters = replay.getattr("adapters")?;

        // Public native modules.
        modules.set_item("lobo.orders", &orders)?;
        modules.set_item("lobo.storage", &storage)?;
        modules.set_item("lobo.context", &context)?;
        modules.set_item("lobo._lobo.sinks", &sinks)?;
        modules.set_item("lobo._lobo.server", module.getattr("server")?)?;

        // Internal native replay modules.
        // Keep `lobo.replay` free for the real Python package at python/lobo/replay/.
        modules.set_item("lobo._lobo.replay", &replay)?;
        modules.set_item("lobo._lobo.replay.adapters", &adapters)?;
        Ok(())
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn module_init_requires_generated_submodules() {
            Python::initialize();
            Python::attach(|py| {
                let module = PyModule::new(py, "_lobo").unwrap();
                assert!(init(&module).is_err());
            });
        }
    }
}
/// AUTOGENERATED FROM RUST. DO NOT EDIT.
#[pymodule]
#[pyo3(name = "orders", submodule, module = "lobo")]
mod orders {
    #[pymodule_export]
    use lobo_models::Side;
    #[pymodule_export]
    use lobo_models::orders::core::PyOrder;
    #[pymodule_export]
    use lobo_models::orders::order_types::PyIcebergOrder;
    #[pymodule_export]
    use lobo_models::orders::order_types::PyLimitOrder;
    #[pymodule_export]
    use lobo_models::orders::order_types::PyMarketOrder;
}
/// AUTOGENERATED FROM RUST. DO NOT EDIT.
#[pymodule]
#[pyo3(name = "storage", submodule, module = "lobo")]
mod storage {
    #[pymodule_export]
    use lobo_books::price_time_priority::PyBidAskStoreView;
    #[pymodule_export]
    use lobo_books::price_time_priority::PyStorage;
    #[pymodule_export]
    use lobo_storage::UserOutstandingLiquidity;
}

/// AUTOGENERATED FROM RUST. DO NOT EDIT.
#[pymodule]
#[pyo3(name = "replay", submodule, module = "lobo")]
mod replay_native {
    #[pymodule_export]
    use super::adapters;
    #[pymodule_export]
    use crate::replay::PyReplayContext;
}

/// AUTOGENERATED FROM RUST. DO NOT EDIT.
#[pymodule]
#[pyo3(name = "adapters", submodule, module = "lobo.replay")]
mod adapters {
    #[pymodule_export]
    use super::{bitfinex, itch, kraken};
    #[pymodule_export]
    use lobo_replay::custom::definition::python::{expression_exports, models};
    #[pymodule_export]
    use lobo_replay::custom::definition::schema::Definition;
    #[pymodule_export]
    use lobo_replay::custom::python::PyAdapterSession;
    #[pymodule_export]
    use lobo_replay::custom::python::native;
}

/// AUTOGENERATED FROM RUST. DO NOT EDIT.
///
/// Read NASDAQ ITCH replay files with the shipped Rust adapter.
#[pymodule]
#[pyo3(name = "itch", submodule, module = "lobo.replay.adapters")]
mod itch {
    #[pymodule_export]
    use lobo_adapters::itch::python::PyItchSource;
    #[cfg(feature = "polars")]
    #[pymodule_export]
    use lobo_adapters::itch::python::PyReplayMessages;
}

/// AUTOGENERATED FROM RUST. DO NOT EDIT.
#[pymodule]
#[pyo3(name = "sinks", submodule, module = "lobo")]
mod sinks {
    #[pymodule_export]
    use lobo_context::python::PyFeatherSink;
    #[pymodule_export]
    use lobo_context::python::PyGpuSink;
}

/// AUTOGENERATED FROM RUST. DO NOT EDIT.
#[pymodule]
#[pyo3(name = "context", submodule, module = "lobo")]
mod context_native {
    #[pymodule_export]
    use crate::context::PyContext;
}

/// AUTOGENERATED FROM RUST. DO NOT EDIT.
#[pymodule]
#[pyo3(name = "server", submodule, module = "lobo")]
mod server_native {
    #[pymodule_export]
    use lobo_server::python::PyServerContext;
}

/// AUTOGENERATED FROM RUST. DO NOT EDIT.
///
/// Configure and start the built-in Kraken feed.
#[pymodule]
#[pyo3(name = "kraken", submodule, module = "lobo.replay.adapters")]
mod kraken {
    #[pymodule_export]
    use lobo_adapters::kraken::python::PyKrakenSource;
}

/// AUTOGENERATED FROM RUST. DO NOT EDIT.
///
/// Configure and start the built-in Bitfinex feed.
#[pymodule]
#[pyo3(name = "bitfinex", submodule, module = "lobo.replay.adapters")]
mod bitfinex {
    #[pymodule_export]
    use lobo_adapters::bitfinex::python::PyBitfinexSource;
}
