# Not autogenerated.
"""Serve the Bitfinex R0 live feed in the terminal."""

import argparse
from threading import Event

from lobo import server_context

if __package__:
    from .adapter import build_adapter
else:
    from adapter import build_adapter


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--symbol", default="BTCUSD")

    args = parser.parse_args()
    adapter = build_adapter(symbol=args.symbol)

    with server_context(adapters=[adapter], port=args.port) as server:
        print(server.url, flush=True)
        try:
            Event().wait()
        except KeyboardInterrupt:
            pass


if __name__ == "__main__":
    main()
