"""
AUTOGENERATED FROM RUST. DO NOT EDIT.

Connect a user-defined protocol to its source with CustomAdapter.
"""

from . import Protocol
from ...sinks import FeatherSink
from .models import BookLevel, FeedMode, Instrument, Source
from _typeshed import Incomplete
from collections.abc import Iterable, Sequence
from typing import Any, final

@final
class CustomAdapter:
    """
    Connect a user-defined Protocol to a source and expose its books.
    
    The declaration is prepared during construction. Use start() for a streaming
    session and run() for a complete local binary replay. A context manager closes
    the session and drains attached sinks on exit; entering it alone does not start
    reading. To expose the books in the app, pass this adapter to server_context.
    
    Args:
        protocol: A Protocol containing message layouts, actions, and lifecycle rules.
        source: A Source describing a file, HTTP stream, WebSocket, or recorded packets.
        instruments: An optional iterable or generator of Instrument objects. It is
            consumed once during construction. Omit it when Register actions discover
            instruments from the source.
        symbol: The initially selected ticker. Defaults to "BOOK" and is normalized
            like an Instrument symbol. It must be inside scope when scope is supplied.
        scope: An optional list of ticker symbols whose books may be created. None
            allows all discovered symbols. Scope restricts book construction, while
            symbol chooses which permitted book is currently displayed.
        name: The source name shown in the app. Defaults to "Custom adapter".
        mode: FeedMode.Live for an ongoing feed or FeedMode.Replay for recorded data.
            Defaults to FeedMode.Live.
        level: BookLevel.L1 for best quotes, BookLevel.L2 for aggregate levels, or
            BookLevel.L3 for individual orders. Defaults to BookLevel.L3.
            L2 supports market previews; L3 additionally supports queue views and
            alternate timelines for simulated resting limit orders.
        timezone: The IANA timezone used to interpret recorded source times. Defaults
            to "UTC". For a date-named file with intraday timestamps, use its exchange's
            timezone, such as "America/New_York".
        supports_trades: Whether actions report actual executions. Defaults to True.
            Set False for a source that supplies quantity updates without trade data.
    
    Raises:
        ValueError: The declaration cannot be prepared, metadata is invalid, or
            the selected symbol is outside scope.
        RuntimeError: The source cannot be prepared or its directory cannot be read.
        TypeError: The source, instruments, or declaration arguments have invalid types.
    
    Examples:
        ```python
        from lobo.replay.adapters import CustomAdapter, Protocol
        from lobo.replay.adapters import expressions as le
        from lobo.replay.adapters import models as lm
    
        protocol = Protocol(lm.Json(lm.Message(le.Field("type").eq("add"),
            lm.Book("BOOK", lm.Add(id=le.Field("id"), side=le.Field("side"),
                price=le.Field("price"), quantity=le.Field("quantity")), snapshot=True))))
        source = lm.Source.packets([
            b'{"type":"add","id":1,"side":"buy","price":10000,"quantity":20}'
        ])
        with CustomAdapter(protocol, source,
                           instruments=[lm.Instrument("BOOK", 2, 0)]) as adapter:
            adapter.start()
            adapter.wait()
            assert adapter.levels("BOOK")[0]["quantity"] == 20
        ```
    """
    def __enter__(self, /) -> CustomAdapter:
        """
        Enter a scope that closes this adapter automatically on exit.
        
        Returns:
            This adapter. Call start() or run() explicitly inside the scope.
        """
    def __exit__(self, /, _ty: Any, _value: Any, _trace: Any) -> None:
        """
        Close the adapter and attached sinks when leaving its context.
        
        Args:
            _ty: The exception type supplied by Python, or None on normal exit.
            _value: The exception instance supplied by Python, or None.
            _trace: The exception traceback supplied by Python, or None.
        
        Returns:
            None. Exceptions from the context body are not suppressed.
        """
    def __new__(cls, /, protocol: Protocol, source: Source, *, instruments: Iterable[Instrument] |None = None, symbol: str = "BOOK", scope: Sequence[str] |None = None, name: str = "Custom adapter", mode: FeedMode = ..., level: BookLevel = ..., timezone: str = "UTC", supports_trades: bool = True) -> CustomAdapter: ...
    def close(self, /) -> None:
        """
        Stop the background session and finish any attached sink writers.
        
        The method also disconnects publishers retained by bulk replay result books.
        Repeated calls are safe. Context-manager exit calls this method automatically.
        
        Raises:
            RuntimeError: Disconnecting a publisher or closing a sink fails.
        """
    def drain_bars(self, /) -> Any:
        """
        Take completed OHLC bars from the current timeline's output queue.
        
        Returns:
            A list of dictionaries with symbol, open, high, low, close, volume, ticks,
            index, start_ns, and end_ns. Price and volume use instrument atoms. Bars
            are removed from the queue, so a subsequent call returns only new output.
        
        Raises:
            RuntimeError: The adapter has no started session.
        """
    @property
    def finished(self, /) -> bool:
        """
        Whether the session created by start() has stopped consuming its source.
        
        Use wait() to surface an error from a completed worker. Access before start()
        raises RuntimeError. This property does not describe the separate run() result.
        """
    @property
    def info(self, /) -> Any:
        """
        A dictionary describing the adapter's identity, source mode, and capabilities.
        
        Keys are id, name, mode, level, endpoint, default_symbol, timezone, and
        supports_trades. Mode and level are FeedMode and BookLevel enum values.
        This property is available before start().
        """
    def levels(self, /, symbol: str) -> Any:
        """
        Read price levels from a book on the currently displayed timeline.
        
        Args:
            symbol: The registered book symbol to inspect.
        
        Returns:
            A list of dictionaries with side, price, quantity, hidden, and orders.
            Price is decimal text containing integer atoms; quantities are integer atoms.
            Hidden totals can be zero when their book policy disables maintenance.
        
        Raises:
            RuntimeError: The adapter has no started session or the book is unavailable.
        """
    def pause(self, /) -> Any:
        """
        Pause the worker; no further recorded changes apply after this returns.
        """
    def play(self, /) -> Any:
        """
        Resume a paced replay. EOF stays stopped until restart() or seek().
        """
    @property
    def playback(self, /) -> Any:
        """
        Read shared playback state, including the absolute source clock in nanoseconds.
        """
    def queue(self, /, symbol: str, side: str, min_price: int, max_price: int) -> list[tuple[int, int, int, int]]:
        """
        Read resting L3 orders within an inclusive range of price levels.
        
        The view preserves each level's queue priority, including replenished iceberg
        orders. It does not reconstruct priority by sorting original timestamps.
        
        Args:
            symbol: The registered book symbol to inspect.
            side: "buy" or "sell".
            min_price: The inclusive lower price bound in integer atoms.
            max_price: The inclusive upper price bound in integer atoms.
        
        Returns:
            Tuples of (order_id, price, visible_quantity, created_at_ns), in the store's
            level and queue order. IDs are integers; prices and quantities use atoms.
        
        Raises:
            RuntimeError: The adapter has no started session or the book is unavailable.
            ValueError: side is neither "buy" nor "sell".
        """
    def restart(self, /) -> Any:
        """
        Reconstruct the beginning of the recording, retaining pause and speed.
        """
    def return_to_main(self, /) -> None:
        """
        Discard the simulation branch and select the continuing main timeline.
        
        The main book has continued receiving source messages during the simulation.
        Calling this method does not restart the source or replay its earlier messages.
        
        Raises:
            RuntimeError: The adapter has no started session.
        """
    def run(self, /, *, concurrent: bool = True, collect_stats: bool = False, cutoff_time: Any |None = None, sinks: Sequence[FeatherSink] |None = None) -> Any:
        """
        Replay a complete local binary file into books, optionally publishing to sinks.
        
        This call waits for replay completion while allowing other Python threads to
        run. Create a fresh adapter for each run. Use a context manager so sink writers
        finish and release their publishers when the adapter leaves scope.
        
        Args:
            concurrent: Whether books replay concurrently using the existing worker
                pool. Defaults to True. False uses the sequential replay path.
            collect_stats: Whether to collect replay timing and count statistics,
                available through stats. Defaults to False.
            cutoff_time: Optional timezone-aware datetime at which replay stops. None
                processes the full session; naive datetime values are rejected.
            sinks: Optional sequence of FeatherSink instances receiving price-level
                events during replay. Defaults to no event sinks.
        
        Returns:
            A dictionary mapping ticker symbols to their completed book objects.
        
        Raises:
            RuntimeError: The adapter has already started, the source is not a
                supported local binary file, or replay encounters an input error.
            ValueError: cutoff_time has no timezone.
        
        Examples:
            ```python
            # With a declared binary protocol and its local Source:
            # with CustomAdapter(protocol, source, symbol="AAPL", mode="replay") as adapter:
            #     books = adapter.run(concurrent=False)
            ```
        """
    def seek(self, /, timestamp_ns: int) -> Any:
        """
        Rebuild from the beginning through an absolute source timestamp in ns.
        Earlier timestamps clamp to the source origin; beyond EOF stops at EOF.
        Returns only after reconstruction. Pause and speed are retained.

        Args:
            timestamp_ns: Absolute timestamp on the binary source's nanosecond axis.

        Returns:
            The shared playback state after reconstruction.
        """
    def select(self, /, symbol: str) -> None:
        """
        Select the active book and request its live subscription if needed.
        
        Args:
            symbol: A registered ticker inside the adapter's book scope. Previously
                visited live instruments retain their subscriptions.
        
        Raises:
            RuntimeError: The adapter has no started session, or the ticker is
                unavailable or outside scope.
        """
    def set_bar_aggregation(self, /, kind: str, size: int) -> None:
        """
        Choose how reported executions accumulate into OHLC bars.
        
        Changing aggregation resets the bar accumulator, including the simulation's
        accumulator when an alternate timeline exists.
        
        Args:
            kind: "volume" for quantity, "ticks" for execution count, "time" for
                source-time intervals, or "notional" for execution price times quantity.
            size: The positive bar threshold. Units are quantity atoms for volume,
                executions for ticks, nanoseconds for time, and price-atoms times
                quantity-atoms for notional.
        
        Raises:
            RuntimeError: The adapter has no started session.
            ValueError: kind is unknown or size is zero.
        """
    def set_speed(self, /, speed: float) -> Any:
        """
        Set a finite playback multiplier greater than zero and at most 1000.

        Args:
            speed: Source nanoseconds advanced per elapsed wall-clock nanosecond.

        Returns:
            The updated shared playback state.
        """
    def simulate(self, /, side: str, quantity: int, *, price: int |None = None) -> None:
        """
        Preview a market order or start a simulated L3 resting limit order.
        
        Market previews report immediate fills without creating an alternate timeline.
        L3 limit simulations retain a branch for any resting remainder while source
        messages continue. The main timeline remains available through return_to_main().
        
        Args:
            side: The incoming order side, "buy" or "sell".
            quantity: The requested positive quantity in integer quantity atoms.
            price: An optional limit price in integer price atoms. None creates a market
                preview. A limit price requires an L3 source with a synchronized book.
        
        Raises:
            RuntimeError: The adapter has no started session, the book is not
                synchronized, or its order and simulation rules reject the request.
            ValueError: side is neither "buy" nor "sell".
        """
    def simulation_report(self, /) -> Any:
        """
        Read simulated fills and the remaining quantity on the selected timeline.
        
        Returns:
            None before a simulation, otherwise a dictionary with simulated, order_id,
            symbol, requested, filled, remaining, average_price, complete,
            alternate_timeline, ignored, stopped, and executions. Prices use price atoms.
            Each execution contains simulated, timestamp_ns, price, quantity, and sequence.
            A stopped alternate timeline remains selected until return_to_main().
        
        Raises:
            RuntimeError: The adapter has no started session.
        """
    def start(self, /, *, paused: bool |None = None, speed: float = 1.0) -> None:
        """
        Start consuming the source on the adapter's background session.
        
        The method returns after starting the worker; it does not wait for replay or
        live discovery to finish. Use wait() for finite input and close() or a context
        manager to stop a live source. A session already started is left running.
        
        Args:
            paused: None starts unpaced processing. True or False enables paced
                replay, initially paused or playing respectively.
            speed: Playback multiplier in (0, 1000]. A value other than 1.0
                requires an explicit paused argument.

        Raises:
            RuntimeError: The source cannot be prepared or a worker cannot be started.
        Pass paused=True (or False) to enable paced replay controls. With no
        paused argument, start() retains its unpaced finite-source behavior.
        """
    @property
    def stats(self, /) -> Any:
        """
        Replay statistics from run(), or None before a bulk replay completes.
        
        With collect_stats=True, the dictionary includes counts and timing measurements;
        with False it contains only the result supplied by the replay path.
        """
    def status(self, /) -> Any:
        """
        Read session progress and synchronization for the selected book.
        
        Returns:
            A dictionary containing symbol, messages, bytes, clock_ns, complete,
            synchronized, checksum_checks, checksum_failures, and books. clock_ns uses
            the source timeline; complete describes source completion.
        
        Raises:
            RuntimeError: The adapter has no started session.
        """
    def tickers(self, /) -> list[str]:
        """
        List the symbols discovered or explicitly registered by this adapter.
        
        For a running session, read the current directory. Before start(), a local
        binary source can scan its directory records; explicit instruments are merged
        into the result. Live discovery requires starting the source first.
        
        Returns:
            A list of normalized symbols, suitable for ticker selection and autocomplete.
        
        Raises:
            RuntimeError: Directory discovery encounters an input or protocol error.
        """
    def to_lazy_frame(self, /, symbol: str |None = None) -> Incomplete:
        """
        Read named binary fields into a Polars LazyFrame for one instrument.
        
        Args:
            symbol: The ticker to extract. None uses the initially selected ticker.
                The symbol must be inside the adapter's book scope.
        
        Returns:
            A Polars LazyFrame containing the declared record fields for that ticker.
            This is a data extraction operation, rather than a replay into books.
        
        Raises:
            ValueError: symbol is invalid or outside scope.
            RuntimeError: The source or format cannot supply rows.
        """
    def wait(self, /) -> None:
        """
        Wait for a started finite source to finish, releasing Python while waiting.
        
        A live WebSocket normally runs until it is closed; waiting is therefore mainly
        useful for files and packet recordings.
        
        Raises:
            RuntimeError: start() has not created a session, or the worker reports
                an input or protocol error.
        """
