# Not autogenerated.
"""Serve a standalone book and accept orders through the HTTP API."""

import argparse
from threading import Event
from uuid import uuid4

from lobo import Book, server_context
from lobo.orders import LimitOrder, Side


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=8000)

    args = parser.parse_args()
    with server_context(port=args.port, price_decimals=2) as server:
        book = Book("TRADER")
        book.fill(LimitOrder(9995, 500, uuid4(), Side.Buy))
        book.fill(LimitOrder(10005, 500, uuid4(), Side.Sell))
        print(server.url, flush=True)
        try:
            Event().wait()
        except KeyboardInterrupt:
            pass


if __name__ == "__main__":
    main()
