"""
AUTOGENERATED FROM RUST. DO NOT EDIT.
"""

from os import PathLike
from pathlib import Path
from typing import final

@final
class FeatherSink:
    """
    Write price-level updates to Feather V2 on a native background worker.
    Create the sink first, then pass it in Context(sinks=[sink]) or
    ReplayContext(..., sinks=[sink]). Context.close()/exit drains and finalizes it.
    batch_size controls rows per write; the final partial batch is written on close.
    buffer_size controls the IO buffer in bytes. Existing files require overwrite=True.
    """
    def __fspath__(self, /) -> str: ...
    def __new__(cls, /, path: str |PathLike[str], *, batch_size: int = 8192, buffer_size: int = 262144, overwrite: bool = False, metrics: int = ...) -> FeatherSink: ...
    def __repr__(self, /) -> str: ...
    def _snapshot_ipc(self, /) -> bytes:
        """
        Read only committed batches from disk, encoded as a standalone IPC stream.
        Used by lobo.sinks.read_feather; no events are retained in a Python queue.
        """
    @property
    def batch_size(self, /) -> int: ...
    @property
    def batches_written(self, /) -> int: ...
    @property
    def buffer_size(self, /) -> int: ...
    @property
    def bytes_written(self, /) -> int: ...
    @property
    def error(self, /) -> str |None: ...
    @property
    def finished(self, /) -> bool: ...
    @property
    def metrics(self, /) -> int: ...
    @property
    def path(self, /) -> Path: ...
    @property
    def rows_written(self, /) -> int: ...
    @property
    def started(self, /) -> bool: ...

@final
class GpuSink:
    """
    Configure the GPU observer hosted by server_context. The browser owns the
    canvas/device; this sink selects metrics before that observer connects.
    """
    def __new__(cls, /, *, metrics: int = 0) -> GpuSink: ...
    @property
    def metrics(self, /) -> int: ...
