# Not autogenerated.
"""Adapters, protocol models, and expressions for connecting sources to books."""

import sys

from lobo._lobo.replay import adapters as _bindings

AdapterSession = _bindings.AdapterSession
Protocol = _bindings.Protocol
bitfinex = _bindings.bitfinex
custom = _bindings.custom
expressions = _bindings.expressions
itch = _bindings.itch
kraken = _bindings.kraken
models = _bindings.models
CustomAdapter = custom.CustomAdapter

# Expose the Rust modules at their public import paths.
for module in (bitfinex, custom, expressions, itch, kraken, models):
    sys.modules[f"{__name__}.{module.__name__.rsplit('.', 1)[-1]}"] = module

__all__ = [
    "AdapterSession",
    "CustomAdapter",
    "Protocol",
    "bitfinex",
    "custom",
    "expressions",
    "itch",
    "kraken",
    "models",
]
