# Not autogenerated.
"""Serve books and the GPU terminal from a Python construction scope."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .replay.adapters import CustomAdapter

from ._lobo.server import ServerContext
from ._lobo.sinks import GpuSink

__all__ = ["ServerContext", "server_context"]


def server_context(
    *,
    host: str = "127.0.0.1",
    port: int = 8000,
    price_decimals: int = 0,
    quantity_decimals: int = 0,
    queue_capacity: int = 8192,
    web_root: str | Path | None = None,
    sinks: list[GpuSink] | None = None,
    adapters: Sequence[CustomAdapter] | None = None,
) -> ServerContext:
    """Launch the order API and expose books created inside the ``with`` block.

    Pass ``adapters=[adapter]`` to start and expose custom adapters for the
    lifetime of this context. Attach adapters before calling their ``start()``.

    Prices and quantities remain integer atoms throughout the API.
    Precision controls their displayed units in the terminal. Pass ``port=0``
    to choose an available port; ``server.url`` contains the resulting URL.
    The server shuts down on context exit. Existing book references remain usable.

    Construction scopes follow Python ContextVars. Worker threads can explicitly
    obtain a shared book with ``server.book(name)``.
    Pass ``sinks=[GpuSink(metrics=PriceLevelMetrics.HIDDEN_QUANTITY)]`` to include
    reserves in the hosted depth chart; the default displays visible depth.
    """
    return ServerContext(
        Path(web_root) if web_root is not None else Path(__file__).with_name("_web"),
        host=host,
        port=port,
        price_decimals=price_decimals,
        quantity_decimals=quantity_decimals,
        queue_capacity=queue_capacity,
        sinks=sinks,
        adapters=adapters,
    )
