# Not autogenerated.
"""Native streaming destinations and snapshots of committed Feather updates."""

from enum import IntFlag
from io import BytesIO

import polars as pl

from ._lobo.sinks import FeatherSink, GpuSink

__all__ = ["FeatherSink", "GpuSink", "PriceLevelMetrics", "read_feather"]


class PriceLevelMetrics(IntFlag):
    """Optional observer fields; the native batcher applies these bit flags."""

    NONE = 0
    HIDDEN_QUANTITY = 1 << 0


def read_feather(sink: FeatherSink) -> pl.DataFrame:
    """Read the sink's committed batches while its Feather file is still open.

    This reads a consistent prefix from disk, including only batches that the
    writer has flushed. It does not flush a pending partial batch or wait for
    future messages. Context exit drains messages and writes the final partial
    batch and file footer; afterward ``pl.read_ipc(sink.path)`` also works.

    Prices retain the batcher's 16-byte big-endian integer encoding. The side
    column is UInt8: 0 is Buy and 1 is Sell. This explicit snapshot copies the
    committed file prefix; use it for inspection, outside the measured fill loop.
    """
    return pl.read_ipc_stream(BytesIO(sink._snapshot_ipc()))
