# Not autogenerated.
"""Serve NASDAQ ITCH 5.0 replay in the terminal."""

import argparse
from pathlib import Path
from threading import Event

from lobo import server_context
from lobo.replay.adapters import models as lm

if __package__:
    from .adapter import build_adapter
else:
    from adapter import build_adapter


def main() -> None:
    """Host a recorded session with shared playback controls."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--symbol", default="AAPL")
    parser.add_argument("--play", action="store_true", help="Start playing immediately")
    parser.add_argument(
        "--speed", type=float, default=1.0, help="Source-time multiplier"
    )
    parser.add_argument(
        "--start-ns",
        type=int,
        help="Reconstruct through this source timestamp in nanoseconds",
    )
    parser.add_argument(
        "--source",
        default=str(
            Path(__file__).resolve().parents[3] / "data/NASDAQ/01302020.NASDAQ_ITCH50"
        ),
        help="Local ITCH file or HTTP(S) gzip URL",
    )
    args = parser.parse_args()
    source = (
        lm.Source.http(args.source)
        if args.source.startswith(("http://", "https://"))
        else lm.Source.file(args.source)
    )
    adapter = build_adapter(source, symbol=args.symbol, scope=[args.symbol])

    with server_context(
        adapters=[adapter], port=args.port, replay_paused=True, replay_speed=args.speed
    ) as server:
        if args.start_ns is not None:
            adapter.seek(args.start_ns)
        if args.play:
            adapter.play()
        print(server.url, flush=True)
        try:
            Event().wait()
        except KeyboardInterrupt:
            pass


if __name__ == "__main__":
    main()
