"""
AUTOGENERATED FROM RUST. DO NOT EDIT.
"""

from collections.abc import Sequence
from typing import Any, final

from . import Book
from .sinks import FeatherSink

@final
class Context:
    """
    A context for generated orders and interactive fills.
    Create FeatherSink objects first, pass sinks=[...] at construction, then
    obtain books with context.book("name"). Exit/close drains every destination.
    """
    def __enter__(self, /) -> Context: ...
    def __exit__(self, /, _exception_type: Any, _exception: Any, _traceback: Any) -> bool: ...
    def __getitem__(self, /, name: str) -> Book: ...
    def __len__(self, /) -> int: ...
    def __new__(cls, /, *, sinks: Sequence[FeatherSink] |None = None) -> Context: ...
    def book(self, /, name: str) -> Book:
        """
        Return a named book, creating it and connecting its publisher if needed.
        """
    def close(self, /) -> None:
        """
        Drain pending updates and write every Feather footer. Safe to call twice.
        """
    @property
    def closed(self, /) -> bool: ...
    def keys(self, /) -> list[str]: ...
