# Not autogenerated.
"""Helpers shared by the adapter notebooks."""

from pathlib import Path
from time import monotonic, sleep

from lobo.replay.adapters import CustomAdapter


def repository_root() -> Path:
    """Find the checkout containing the notebook."""
    for path in (Path.cwd(), *Path.cwd().parents):
        if (path / "rust/crates/lobo_replay").is_dir():
            return path
    raise FileNotFoundError("Open this notebook from the lobo repository")


def wait_for_book(
    adapter: CustomAdapter, symbol: str, timeout: float = 30
) -> list[dict[str, object]]:
    """Wait for the first completed snapshot while the adapter runs."""
    deadline = monotonic() + timeout
    while monotonic() < deadline:
        if adapter.finished:
            adapter.wait()  # Surface a source error if the worker stopped.
        try:
            levels = adapter.levels(symbol)
            if {level["side"] for level in levels} == {
                "buy",
                "sell",
            } and adapter.status()["synchronized"]:
                return levels
        except RuntimeError:
            pass
        sleep(0.1)
    raise TimeoutError(f"No book received for {symbol} within {timeout:g} seconds")
